In [109]:
import pandas as pd
import os
import re
import numpy as np

In [110]:
SCRIPT_DIR_PATH = os.getcwd()
CB_DIR_PATH = os.path.dirname(SCRIPT_DIR_PATH)
SSP_MODELING_DIR_PATH = os.path.dirname(CB_DIR_PATH)
TORNADO_DATA_DIR_PATH = os.path.join(SCRIPT_DIR_PATH, "data")
INPUT_DATA_DIR_PATH = os.path.join(TORNADO_DATA_DIR_PATH, "input/whirlpool")
OUTPUT_DATA_DIR_PATH = os.path.join(TORNADO_DATA_DIR_PATH, "output/whirlpool")

In [111]:
def add_sector_and_transformation_fields(df: pd.DataFrame, strategy_col: str = "strategy") -> pd.DataFrame:
    df = df.copy()

    # Extrae el sector: lo que está entre TX: y el siguiente :
    # "Remove TX:AGRC:DEC_CH4_RICE_STRATEGY_NZ from NZ" -> "AGRC"
    df["sector"] = df[strategy_col].str.extract(r"TX:([A-Z]{3,6}):", expand=False)

    # Caso especial baseline
    df.loc[df[strategy_col].str.contains(r"TX:BASE", regex=True, na=False), "sector"] = "BASE"

    # Extrae transformation_name: lo que está después de TX:SECTOR:
    # "Remove TX:AGRC:DEC_CH4_RICE_STRATEGY_NZ from NZ" -> "DEC_CH4_RICE_STRATEGY_NZ from NZ"
    df["transformation_name"] = df[strategy_col].str.extract(r"TX:[A-Z]{3,6}:(\S+)", expand=False)

    # Si quieres solo hasta el espacio (sin "from NZ"), usa \S+ que ya captura hasta el primer espacio
    # Si quieres todo lo que sigue incluyendo "from NZ", cambia \S+ por (.+)

    # Caso baseline
    base_mask = df[strategy_col].str.contains(r"TX:BASE", regex=True, na=False)
    df.loc[base_mask, "transformation_name"] = "BASE"

    df["transformation_name"] = df["transformation_name"].fillna("").str.strip()

    return df

## Load and process emission data

In [112]:
# Load the decomposed emissions long format data
emissions_df = pd.read_csv(os.path.join(INPUT_DATA_DIR_PATH, "raw_emissions_uganda_2019_whirlpool_data_raw.csv"))
# emissions_df = pd.read_csv(os.path.join(INPUT_DATA_DIR_PATH, "decomposed_emissions_bulgaria_2022_trww_debug.csv"))
emissions_df.head()

,strategy_id,primary_id,Subsector_Category,CSC.Subsector,CSC.Sector,value,Year,Gas,design_id,future_id,strategy,Code,Contry,source
0,0.0,0.0,Agriculture and Managed Soil:ch4,Agriculture and Managed Soil,Non-LULUCF,0.241921,2019,ch4,0.0,0.0,Strategy TX:BASE,UGA,uganda,SISEPUEDE
1,0.0,0.0,Agriculture and Managed Soil:ch4,Agriculture and Managed Soil,Non-LULUCF,0.244762,2020,ch4,0.0,0.0,Strategy TX:BASE,UGA,uganda,SISEPUEDE
2,0.0,0.0,Agriculture and Managed Soil:ch4,Agriculture and Managed Soil,Non-LULUCF,0.252282,2021,ch4,0.0,0.0,Strategy TX:BASE,UGA,uganda,SISEPUEDE
3,0.0,0.0,Agriculture and Managed Soil:ch4,Agriculture and Managed Soil,Non-LULUCF,0.251119,2022,ch4,0.0,0.0,Strategy TX:BASE,UGA,uganda,SISEPUEDE
4,0.0,0.0,Agriculture and Managed Soil:ch4,Agriculture and Managed Soil,Non-LULUCF,0.252083,2023,ch4,0.0,0.0,Strategy TX:BASE,UGA,uganda,SISEPUEDE

In [113]:
print(emissions_df.primary_id.nunique())

61

In [114]:
# check unique strategy
emissions_df['strategy'].unique()

array(['Strategy TX:BASE', 'HBLE',
       'Remove TX:AGRC:DEC_CH4_RICE_STRATEGY_NZ from HBLE',
       'Remove TX:AGRC:DEC_LOSSES_SUPPLY_CHAIN_STRATEGY_NZ from HBLE',
       'Remove TX:AGRC:INC_CONSERVATION_AGRICULTURE_STRATEGY_NZ from HBLE',
       'Remove TX:AGRC:INC_PRODUCTIVITY_STRATEGY_NZ from HBLE',
       'Remove TX:ENTC:DEC_LOSSES_STRATEGY_NZ from HBLE',
       'Remove TX:ENTC:TARGET_CLEAN_HYDROGEN_STRATEGY_NZ from HBLE',
       'Remove TX:ENTC:TARGET_RENEWABLE_ELEC_STRATEGY_NZ from HBLE',
       'Remove TX:FGTV:DEC_LEAKS_STRATEGY_NZ from HBLE',
       'Remove TX:FGTV:INC_FLARE_STRATEGY_NZ from HBLE',
       'Remove TX:FRST:INCREASE_SEQUESTRATION_NZ from HBLE',
       'Remove TX:INEN:INC_EFFICIENCY_ENERGY_STRATEGY_NZ from HBLE',
       'Remove TX:INEN:SHIFT_FUEL_HEAT_STRATEGY_NZ from HBLE',
       'Remove TX:IPPU:DEC_CLINKER_STRATEGY_NZ from HBLE',
       'Remove TX:IPPU:DEC_HFCS_STRATEGY_NZ from HBLE',
       'Remove TX:IPPU:DEC_N2O_STRATEGY_NZ from HBLE',
       'Remove TX:IPPU:DEC_OTHER_FCS_STRATEGY_NZ from HBLE',
       'Remove TX:IPPU:DEC_PFCS_STRATEGY_NZ from HBLE',
       'Remove TX:LNDU:DEC_DEFORESTATION_STRATEGY_NZ from HBLE',
       'Remove TX:LNDU:DEC_WETLAND_LOSS_NZ from HBLE',
       'Remove TX:LNDU:INC_REFORESTATION_STRATEGY_NZ from HBLE',
       'Remove TX:LNDU:INC_SILVOPASTURE from HBLE',
       'Remove TX:LNDU:SET_WETLANDS_MINIMUM_NZ from HBLE',
       'Remove TX:LSMM:INC_CAPTURE_BIOGAS_STRATEGY_NZ from HBLE',
       'Remove TX:LSMM:INC_MANAGEMENT_CATTLE_PIGS_STRATEGY_NZ from HBLE',
       'Remove TX:LSMM:INC_MANAGEMENT_OTHER_STRATEGY_NZ from HBLE',
       'Remove TX:LSMM:INC_MANAGEMENT_POULTRY_STRATEGY_NZ from HBLE',
       'Remove TX:LVST:DEC_ENTERIC_FERMENTATION_STRATEGY_NZ from HBLE',
       'Remove TX:LVST:INC_PRODUCTIVITY_STRATEGY_NZ from HBLE',
       'Remove TX:PFLO:INC_HEALTHIER_DIETS from HBLE',
       'Remove TX:PFLO:INC_IND_CCS_STRATEGY_NZ from HBLE',
       'Remove TX:SCOE:DEC_DEMAND_HEAT_STRATEGY_NZ from HBLE',
       'Remove TX:SCOE:INC_EFFICIENCY_APPLIANCE_STRATEGY_NZ from HBLE',
       'Remove TX:SCOE:INC_EFFICIENCY_HEAT_NZ from HBLE',
       'Remove TX:SCOE:SHIFT_FUEL_HEAT_STRATEGY_NZ from HBLE',
       'Remove TX:SOIL:DEC_LIME_APPLIED_STRATEGY_NZ from HBLE',
       'Remove TX:SOIL:DEC_N_APPLIED_STRATEGY_NZ from HBLE',
       'Remove TX:TRDE:DEC_DEMAND_STRATEGY_NZ from HBLE',
       'Remove TX:TRNS:INC_EFFICIENCY_ELECTRIC_STRATEGY_NZ from HBLE',
       'Remove TX:TRNS:INC_EFFICIENCY_NON_ELECTRIC_STRATEGY_NZ from HBLE',
       'Remove TX:TRNS:INC_OCCUPANCY_LIGHT_DUTY_STRATEGY_NZ from HBLE',
       'Remove TX:TRNS:SHIFT_FUEL_LIGHT_DUTY_STRATEGY_NZ from HBLE',
       'Remove TX:TRNS:SHIFT_FUEL_MARITIME_STRATEGY_NZ from HBLE',
       'Remove TX:TRNS:SHIFT_FUEL_MEDIUM_DUTY_STRATEGY_NZ from HBLE',
       'Remove TX:TRNS:SHIFT_FUEL_RAIL_STRATEGY_NZ from HBLE',
       'Remove TX:TRNS:SHIFT_MODE_FREIGHT_STRATEGY_NZ from HBLE',
       'Remove TX:TRNS:SHIFT_MODE_PASSENGER_STRATEGY_NZ from HBLE',
       'Remove TX:TRNS:SHIFT_MODE_REGIONAL_STRATEGY_NZ from HBLE',
       'Remove TX:TRWW:INC_CAPTURE_BIOGAS_STRATEGY_NZ from HBLE',
       'Remove TX:TRWW:INC_COMPLIANCE_SEPTIC_STRATEGY_NZ from HBLE',
       'Remove TX:WALI:INC_TREATMENT_INDUSTRIAL_STRATEGY_NZ from HBLE',
       'Remove TX:WALI:INC_TREATMENT_RURAL_STRATEGY_NZ from HBLE',
       'Remove TX:WALI:INC_TREATMENT_URBAN_STRATEGY_NZ from HBLE',
       'Remove TX:WASO:DEC_CONSUMER_FOOD_WASTE_STRATEGY_NZ from HBLE',
       'Remove TX:WASO:INC_ANAEROBIC_AND_COMPOST_STRATEGY_NZ from HBLE',
       'Remove TX:WASO:INC_CAPTURE_BIOGAS_STRATEGY_NZ from HBLE',
       'Remove TX:WASO:INC_ENERGY_FROM_BIOGAS_STRATEGY_NZ from HBLE',
       'Remove TX:WASO:INC_ENERGY_FROM_INCINERATION_STRATEGY_NZ from HBLE',
       'Remove TX:WASO:INC_LANDFILLING_STRATEGY_NZ from HBLE',
       'Remove TX:WASO:INC_RECYCLING_STRATEGY_NZ from HBLE', 'Historical'],
      dtype=object)

In [115]:
# Drop historical and tx:base from df
filtered_emissions_df = emissions_df.loc[~emissions_df['strategy'].isin(['Historical', 'Strategy TX:BASE'])]
print(emissions_df['strategy'].nunique())
print(filtered_emissions_df['strategy'].nunique())

62
60

In [116]:
filtered_emissions_df["strategy"].unique()

array(['HBLE', 'Remove TX:AGRC:DEC_CH4_RICE_STRATEGY_NZ from HBLE',
       'Remove TX:AGRC:DEC_LOSSES_SUPPLY_CHAIN_STRATEGY_NZ from HBLE',
       'Remove TX:AGRC:INC_CONSERVATION_AGRICULTURE_STRATEGY_NZ from HBLE',
       'Remove TX:AGRC:INC_PRODUCTIVITY_STRATEGY_NZ from HBLE',
       'Remove TX:ENTC:DEC_LOSSES_STRATEGY_NZ from HBLE',
       'Remove TX:ENTC:TARGET_CLEAN_HYDROGEN_STRATEGY_NZ from HBLE',
       'Remove TX:ENTC:TARGET_RENEWABLE_ELEC_STRATEGY_NZ from HBLE',
       'Remove TX:FGTV:DEC_LEAKS_STRATEGY_NZ from HBLE',
       'Remove TX:FGTV:INC_FLARE_STRATEGY_NZ from HBLE',
       'Remove TX:FRST:INCREASE_SEQUESTRATION_NZ from HBLE',
       'Remove TX:INEN:INC_EFFICIENCY_ENERGY_STRATEGY_NZ from HBLE',
       'Remove TX:INEN:SHIFT_FUEL_HEAT_STRATEGY_NZ from HBLE',
       'Remove TX:IPPU:DEC_CLINKER_STRATEGY_NZ from HBLE',
       'Remove TX:IPPU:DEC_HFCS_STRATEGY_NZ from HBLE',
       'Remove TX:IPPU:DEC_N2O_STRATEGY_NZ from HBLE',
       'Remove TX:IPPU:DEC_OTHER_FCS_STRATEGY_NZ from HBLE',
       'Remove TX:IPPU:DEC_PFCS_STRATEGY_NZ from HBLE',
       'Remove TX:LNDU:DEC_DEFORESTATION_STRATEGY_NZ from HBLE',
       'Remove TX:LNDU:DEC_WETLAND_LOSS_NZ from HBLE',
       'Remove TX:LNDU:INC_REFORESTATION_STRATEGY_NZ from HBLE',
       'Remove TX:LNDU:INC_SILVOPASTURE from HBLE',
       'Remove TX:LNDU:SET_WETLANDS_MINIMUM_NZ from HBLE',
       'Remove TX:LSMM:INC_CAPTURE_BIOGAS_STRATEGY_NZ from HBLE',
       'Remove TX:LSMM:INC_MANAGEMENT_CATTLE_PIGS_STRATEGY_NZ from HBLE',
       'Remove TX:LSMM:INC_MANAGEMENT_OTHER_STRATEGY_NZ from HBLE',
       'Remove TX:LSMM:INC_MANAGEMENT_POULTRY_STRATEGY_NZ from HBLE',
       'Remove TX:LVST:DEC_ENTERIC_FERMENTATION_STRATEGY_NZ from HBLE',
       'Remove TX:LVST:INC_PRODUCTIVITY_STRATEGY_NZ from HBLE',
       'Remove TX:PFLO:INC_HEALTHIER_DIETS from HBLE',
       'Remove TX:PFLO:INC_IND_CCS_STRATEGY_NZ from HBLE',
       'Remove TX:SCOE:DEC_DEMAND_HEAT_STRATEGY_NZ from HBLE',
       'Remove TX:SCOE:INC_EFFICIENCY_APPLIANCE_STRATEGY_NZ from HBLE',
       'Remove TX:SCOE:INC_EFFICIENCY_HEAT_NZ from HBLE',
       'Remove TX:SCOE:SHIFT_FUEL_HEAT_STRATEGY_NZ from HBLE',
       'Remove TX:SOIL:DEC_LIME_APPLIED_STRATEGY_NZ from HBLE',
       'Remove TX:SOIL:DEC_N_APPLIED_STRATEGY_NZ from HBLE',
       'Remove TX:TRDE:DEC_DEMAND_STRATEGY_NZ from HBLE',
       'Remove TX:TRNS:INC_EFFICIENCY_ELECTRIC_STRATEGY_NZ from HBLE',
       'Remove TX:TRNS:INC_EFFICIENCY_NON_ELECTRIC_STRATEGY_NZ from HBLE',
       'Remove TX:TRNS:INC_OCCUPANCY_LIGHT_DUTY_STRATEGY_NZ from HBLE',
       'Remove TX:TRNS:SHIFT_FUEL_LIGHT_DUTY_STRATEGY_NZ from HBLE',
       'Remove TX:TRNS:SHIFT_FUEL_MARITIME_STRATEGY_NZ from HBLE',
       'Remove TX:TRNS:SHIFT_FUEL_MEDIUM_DUTY_STRATEGY_NZ from HBLE',
       'Remove TX:TRNS:SHIFT_FUEL_RAIL_STRATEGY_NZ from HBLE',
       'Remove TX:TRNS:SHIFT_MODE_FREIGHT_STRATEGY_NZ from HBLE',
       'Remove TX:TRNS:SHIFT_MODE_PASSENGER_STRATEGY_NZ from HBLE',
       'Remove TX:TRNS:SHIFT_MODE_REGIONAL_STRATEGY_NZ from HBLE',
       'Remove TX:TRWW:INC_CAPTURE_BIOGAS_STRATEGY_NZ from HBLE',
       'Remove TX:TRWW:INC_COMPLIANCE_SEPTIC_STRATEGY_NZ from HBLE',
       'Remove TX:WALI:INC_TREATMENT_INDUSTRIAL_STRATEGY_NZ from HBLE',
       'Remove TX:WALI:INC_TREATMENT_RURAL_STRATEGY_NZ from HBLE',
       'Remove TX:WALI:INC_TREATMENT_URBAN_STRATEGY_NZ from HBLE',
       'Remove TX:WASO:DEC_CONSUMER_FOOD_WASTE_STRATEGY_NZ from HBLE',
       'Remove TX:WASO:INC_ANAEROBIC_AND_COMPOST_STRATEGY_NZ from HBLE',
       'Remove TX:WASO:INC_CAPTURE_BIOGAS_STRATEGY_NZ from HBLE',
       'Remove TX:WASO:INC_ENERGY_FROM_BIOGAS_STRATEGY_NZ from HBLE',
       'Remove TX:WASO:INC_ENERGY_FROM_INCINERATION_STRATEGY_NZ from HBLE',
       'Remove TX:WASO:INC_LANDFILLING_STRATEGY_NZ from HBLE',
       'Remove TX:WASO:INC_RECYCLING_STRATEGY_NZ from HBLE'], dtype=object)

In [117]:
filtered_emissions_df.head()

,strategy_id,primary_id,Subsector_Category,CSC.Subsector,CSC.Sector,value,Year,Gas,design_id,future_id,strategy,Code,Contry,source
2808,6004.0,700070.0,Agriculture and Managed Soil:ch4,Agriculture and Managed Soil,Non-LULUCF,0.241921,2019,ch4,0.0,0.0,HBLE,UGA,uganda,SISEPUEDE
2809,6004.0,700070.0,Agriculture and Managed Soil:ch4,Agriculture and Managed Soil,Non-LULUCF,0.244762,2020,ch4,0.0,0.0,HBLE,UGA,uganda,SISEPUEDE
2810,6004.0,700070.0,Agriculture and Managed Soil:ch4,Agriculture and Managed Soil,Non-LULUCF,0.252282,2021,ch4,0.0,0.0,HBLE,UGA,uganda,SISEPUEDE
2811,6004.0,700070.0,Agriculture and Managed Soil:ch4,Agriculture and Managed Soil,Non-LULUCF,0.251119,2022,ch4,0.0,0.0,HBLE,UGA,uganda,SISEPUEDE
2812,6004.0,700070.0,Agriculture and Managed Soil:ch4,Agriculture and Managed Soil,Non-LULUCF,0.252083,2023,ch4,0.0,0.0,HBLE,UGA,uganda,SISEPUEDE

In [118]:
filtered_emissions_df.tail()

,strategy_id,primary_id,Subsector_Category,CSC.Subsector,CSC.Sector,value,Year,Gas,design_id,future_id,strategy,Code,Contry,source
171283,6617.0,1930193.0,Wetlands:co2,Wetlands,LULUCF,0.0,2066,co2,0.0,0.0,Remove TX:WASO:INC_RECYCLING_STRATEGY_NZ from ...,UGA,uganda,SISEPUEDE
171284,6617.0,1930193.0,Wetlands:co2,Wetlands,LULUCF,0.0,2067,co2,0.0,0.0,Remove TX:WASO:INC_RECYCLING_STRATEGY_NZ from ...,UGA,uganda,SISEPUEDE
171285,6617.0,1930193.0,Wetlands:co2,Wetlands,LULUCF,0.0,2068,co2,0.0,0.0,Remove TX:WASO:INC_RECYCLING_STRATEGY_NZ from ...,UGA,uganda,SISEPUEDE
171286,6617.0,1930193.0,Wetlands:co2,Wetlands,LULUCF,0.0,2069,co2,0.0,0.0,Remove TX:WASO:INC_RECYCLING_STRATEGY_NZ from ...,UGA,uganda,SISEPUEDE
171287,6617.0,1930193.0,Wetlands:co2,Wetlands,LULUCF,0.0,2070,co2,0.0,0.0,Remove TX:WASO:INC_RECYCLING_STRATEGY_NZ from ...,UGA,uganda,SISEPUEDE

In [119]:
# Now concat the original base df and the filtered emissions df
tornado_emissions_df = filtered_emissions_df
tornado_emissions_df['strategy'].unique()

array(['HBLE', 'Remove TX:AGRC:DEC_CH4_RICE_STRATEGY_NZ from HBLE',
       'Remove TX:AGRC:DEC_LOSSES_SUPPLY_CHAIN_STRATEGY_NZ from HBLE',
       'Remove TX:AGRC:INC_CONSERVATION_AGRICULTURE_STRATEGY_NZ from HBLE',
       'Remove TX:AGRC:INC_PRODUCTIVITY_STRATEGY_NZ from HBLE',
       'Remove TX:ENTC:DEC_LOSSES_STRATEGY_NZ from HBLE',
       'Remove TX:ENTC:TARGET_CLEAN_HYDROGEN_STRATEGY_NZ from HBLE',
       'Remove TX:ENTC:TARGET_RENEWABLE_ELEC_STRATEGY_NZ from HBLE',
       'Remove TX:FGTV:DEC_LEAKS_STRATEGY_NZ from HBLE',
       'Remove TX:FGTV:INC_FLARE_STRATEGY_NZ from HBLE',
       'Remove TX:FRST:INCREASE_SEQUESTRATION_NZ from HBLE',
       'Remove TX:INEN:INC_EFFICIENCY_ENERGY_STRATEGY_NZ from HBLE',
       'Remove TX:INEN:SHIFT_FUEL_HEAT_STRATEGY_NZ from HBLE',
       'Remove TX:IPPU:DEC_CLINKER_STRATEGY_NZ from HBLE',
       'Remove TX:IPPU:DEC_HFCS_STRATEGY_NZ from HBLE',
       'Remove TX:IPPU:DEC_N2O_STRATEGY_NZ from HBLE',
       'Remove TX:IPPU:DEC_OTHER_FCS_STRATEGY_NZ from HBLE',
       'Remove TX:IPPU:DEC_PFCS_STRATEGY_NZ from HBLE',
       'Remove TX:LNDU:DEC_DEFORESTATION_STRATEGY_NZ from HBLE',
       'Remove TX:LNDU:DEC_WETLAND_LOSS_NZ from HBLE',
       'Remove TX:LNDU:INC_REFORESTATION_STRATEGY_NZ from HBLE',
       'Remove TX:LNDU:INC_SILVOPASTURE from HBLE',
       'Remove TX:LNDU:SET_WETLANDS_MINIMUM_NZ from HBLE',
       'Remove TX:LSMM:INC_CAPTURE_BIOGAS_STRATEGY_NZ from HBLE',
       'Remove TX:LSMM:INC_MANAGEMENT_CATTLE_PIGS_STRATEGY_NZ from HBLE',
       'Remove TX:LSMM:INC_MANAGEMENT_OTHER_STRATEGY_NZ from HBLE',
       'Remove TX:LSMM:INC_MANAGEMENT_POULTRY_STRATEGY_NZ from HBLE',
       'Remove TX:LVST:DEC_ENTERIC_FERMENTATION_STRATEGY_NZ from HBLE',
       'Remove TX:LVST:INC_PRODUCTIVITY_STRATEGY_NZ from HBLE',
       'Remove TX:PFLO:INC_HEALTHIER_DIETS from HBLE',
       'Remove TX:PFLO:INC_IND_CCS_STRATEGY_NZ from HBLE',
       'Remove TX:SCOE:DEC_DEMAND_HEAT_STRATEGY_NZ from HBLE',
       'Remove TX:SCOE:INC_EFFICIENCY_APPLIANCE_STRATEGY_NZ from HBLE',
       'Remove TX:SCOE:INC_EFFICIENCY_HEAT_NZ from HBLE',
       'Remove TX:SCOE:SHIFT_FUEL_HEAT_STRATEGY_NZ from HBLE',
       'Remove TX:SOIL:DEC_LIME_APPLIED_STRATEGY_NZ from HBLE',
       'Remove TX:SOIL:DEC_N_APPLIED_STRATEGY_NZ from HBLE',
       'Remove TX:TRDE:DEC_DEMAND_STRATEGY_NZ from HBLE',
       'Remove TX:TRNS:INC_EFFICIENCY_ELECTRIC_STRATEGY_NZ from HBLE',
       'Remove TX:TRNS:INC_EFFICIENCY_NON_ELECTRIC_STRATEGY_NZ from HBLE',
       'Remove TX:TRNS:INC_OCCUPANCY_LIGHT_DUTY_STRATEGY_NZ from HBLE',
       'Remove TX:TRNS:SHIFT_FUEL_LIGHT_DUTY_STRATEGY_NZ from HBLE',
       'Remove TX:TRNS:SHIFT_FUEL_MARITIME_STRATEGY_NZ from HBLE',
       'Remove TX:TRNS:SHIFT_FUEL_MEDIUM_DUTY_STRATEGY_NZ from HBLE',
       'Remove TX:TRNS:SHIFT_FUEL_RAIL_STRATEGY_NZ from HBLE',
       'Remove TX:TRNS:SHIFT_MODE_FREIGHT_STRATEGY_NZ from HBLE',
       'Remove TX:TRNS:SHIFT_MODE_PASSENGER_STRATEGY_NZ from HBLE',
       'Remove TX:TRNS:SHIFT_MODE_REGIONAL_STRATEGY_NZ from HBLE',
       'Remove TX:TRWW:INC_CAPTURE_BIOGAS_STRATEGY_NZ from HBLE',
       'Remove TX:TRWW:INC_COMPLIANCE_SEPTIC_STRATEGY_NZ from HBLE',
       'Remove TX:WALI:INC_TREATMENT_INDUSTRIAL_STRATEGY_NZ from HBLE',
       'Remove TX:WALI:INC_TREATMENT_RURAL_STRATEGY_NZ from HBLE',
       'Remove TX:WALI:INC_TREATMENT_URBAN_STRATEGY_NZ from HBLE',
       'Remove TX:WASO:DEC_CONSUMER_FOOD_WASTE_STRATEGY_NZ from HBLE',
       'Remove TX:WASO:INC_ANAEROBIC_AND_COMPOST_STRATEGY_NZ from HBLE',
       'Remove TX:WASO:INC_CAPTURE_BIOGAS_STRATEGY_NZ from HBLE',
       'Remove TX:WASO:INC_ENERGY_FROM_BIOGAS_STRATEGY_NZ from HBLE',
       'Remove TX:WASO:INC_ENERGY_FROM_INCINERATION_STRATEGY_NZ from HBLE',
       'Remove TX:WASO:INC_LANDFILLING_STRATEGY_NZ from HBLE',
       'Remove TX:WASO:INC_RECYCLING_STRATEGY_NZ from HBLE'], dtype=object)

In [120]:
tornado_emissions_df.head()

,strategy_id,primary_id,Subsector_Category,CSC.Subsector,CSC.Sector,value,Year,Gas,design_id,future_id,strategy,Code,Contry,source
2808,6004.0,700070.0,Agriculture and Managed Soil:ch4,Agriculture and Managed Soil,Non-LULUCF,0.241921,2019,ch4,0.0,0.0,HBLE,UGA,uganda,SISEPUEDE
2809,6004.0,700070.0,Agriculture and Managed Soil:ch4,Agriculture and Managed Soil,Non-LULUCF,0.244762,2020,ch4,0.0,0.0,HBLE,UGA,uganda,SISEPUEDE
2810,6004.0,700070.0,Agriculture and Managed Soil:ch4,Agriculture and Managed Soil,Non-LULUCF,0.252282,2021,ch4,0.0,0.0,HBLE,UGA,uganda,SISEPUEDE
2811,6004.0,700070.0,Agriculture and Managed Soil:ch4,Agriculture and Managed Soil,Non-LULUCF,0.251119,2022,ch4,0.0,0.0,HBLE,UGA,uganda,SISEPUEDE
2812,6004.0,700070.0,Agriculture and Managed Soil:ch4,Agriculture and Managed Soil,Non-LULUCF,0.252083,2023,ch4,0.0,0.0,HBLE,UGA,uganda,SISEPUEDE

In [121]:
# Aggregate by strategy_id, primary_id and strategy, and sum value
tornado_emissions_agg_df = tornado_emissions_df.groupby(
    ['strategy_id', 'primary_id', 'strategy']
)['value'].sum().reset_index()

tornado_emissions_agg_df.head()

,strategy_id,primary_id,strategy,value
0,6004.0,700070.0,HBLE,4901.538826
1,6559.0,1350135.0,Remove TX:AGRC:DEC_CH4_RICE_STRATEGY_NZ from HBLE,4903.261177
2,6560.0,1360136.0,Remove TX:AGRC:DEC_LOSSES_SUPPLY_CHAIN_STRATEG...,4994.242403
3,6561.0,1370137.0,Remove TX:AGRC:INC_CONSERVATION_AGRICULTURE_ST...,4899.663997
4,6562.0,1380138.0,Remove TX:AGRC:INC_PRODUCTIVITY_STRATEGY_NZ fr...,5186.463871

In [122]:
tornado_emissions_agg_df.tail()

,strategy_id,primary_id,strategy,value
55,6613.0,1890189.0,Remove TX:WASO:INC_CAPTURE_BIOGAS_STRATEGY_NZ ...,5086.195151
56,6614.0,1900190.0,Remove TX:WASO:INC_ENERGY_FROM_BIOGAS_STRATEGY...,4899.448463
57,6615.0,1910191.0,Remove TX:WASO:INC_ENERGY_FROM_INCINERATION_ST...,4902.594597
58,6616.0,1920192.0,Remove TX:WASO:INC_LANDFILLING_STRATEGY_NZ fro...,4903.590804
59,6617.0,1930193.0,Remove TX:WASO:INC_RECYCLING_STRATEGY_NZ from ...,4923.610319

In [123]:
# check if strategy id nunique matches amount of rows
print(tornado_emissions_agg_df['strategy_id'].nunique())
print(tornado_emissions_agg_df.shape[0])

60
60

In [124]:
# rename value to emission_total
tornado_emissions_agg_df = tornado_emissions_agg_df.rename(columns={'value': 'emission_total'})

# create base_emission_total column by setting it to the strategy_id == 0 value
base_emission_total = (tornado_emissions_agg_df.loc[tornado_emissions_agg_df['strategy_id'] == 6004, 'emission_total'].values[0])
tornado_emissions_agg_df['base_emission_total'] = base_emission_total 

base_emission_total

np.float64(4901.5388259237225)

In [125]:
# calculate emission difference column
tornado_emissions_agg_df['emission_diff'] =  tornado_emissions_agg_df['emission_total'] - tornado_emissions_agg_df['base_emission_total']
tornado_emissions_agg_df.head()

,strategy_id,primary_id,strategy,emission_total,base_emission_total,emission_diff
0,6004.0,700070.0,HBLE,4901.538826,4901.538826,0.000000
1,6559.0,1350135.0,Remove TX:AGRC:DEC_CH4_RICE_STRATEGY_NZ from HBLE,4903.261177,4901.538826,1.722351
2,6560.0,1360136.0,Remove TX:AGRC:DEC_LOSSES_SUPPLY_CHAIN_STRATEG...,4994.242403,4901.538826,92.703577
3,6561.0,1370137.0,Remove TX:AGRC:INC_CONSERVATION_AGRICULTURE_ST...,4899.663997,4901.538826,-1.874829
4,6562.0,1380138.0,Remove TX:AGRC:INC_PRODUCTIVITY_STRATEGY_NZ fr...,5186.463871,4901.538826,284.925045

In [126]:
tornado_emissions_agg_extended_df = add_sector_and_transformation_fields(tornado_emissions_agg_df)
tornado_emissions_agg_extended_df.head()

,strategy_id,primary_id,strategy,emission_total,base_emission_total,emission_diff,sector,transformation_name
0,6004.0,700070.0,HBLE,4901.538826,4901.538826,0.000000,NaN,
1,6559.0,1350135.0,Remove TX:AGRC:DEC_CH4_RICE_STRATEGY_NZ from HBLE,4903.261177,4901.538826,1.722351,AGRC,DEC_CH4_RICE_STRATEGY_NZ
2,6560.0,1360136.0,Remove TX:AGRC:DEC_LOSSES_SUPPLY_CHAIN_STRATEG...,4994.242403,4901.538826,92.703577,AGRC,DEC_LOSSES_SUPPLY_CHAIN_STRATEGY_NZ
3,6561.0,1370137.0,Remove TX:AGRC:INC_CONSERVATION_AGRICULTURE_ST...,4899.663997,4901.538826,-1.874829,AGRC,INC_CONSERVATION_AGRICULTURE_STRATEGY_NZ
4,6562.0,1380138.0,Remove TX:AGRC:INC_PRODUCTIVITY_STRATEGY_NZ fr...,5186.463871,4901.538826,284.925045,AGRC,INC_PRODUCTIVITY_STRATEGY_NZ

In [127]:
tornado_emissions_agg_extended_df.to_clipboard(index=False)

## Load and process CB data

In [128]:
# cb_raw_df = pd.read_csv(os.path.join(INPUT_DATA_DIR_PATH, "costs_benefits_sisepuede_results_sisepuede_run_2026-01-29T15;28;40.322709_tornado_raw.csv"))
cb_raw_df = pd.read_csv(os.path.join(INPUT_DATA_DIR_PATH, "cba_results_ssp_modeling_whirlpool.csv"))
cb_raw_df.head()

,strategy_code,future_id,region,time_period,difference_variable,variable_value_baseline,variable_value_pathway,difference_value,variable,value
0,PFLO:HBLE,0,uganda,4,pop_unimproved_rural,1.932346e+07,1.932346e+07,0.0,cb:wali:technical_cost:sanitation:unimp_rural,0.0
1,PFLO:HBLE,0,uganda,5,pop_unimproved_rural,1.951974e+07,1.951974e+07,0.0,cb:wali:technical_cost:sanitation:unimp_rural,0.0
2,PFLO:HBLE,0,uganda,6,pop_unimproved_rural,1.896047e+07,1.896047e+07,0.0,cb:wali:technical_cost:sanitation:unimp_rural,0.0
3,PFLO:HBLE,0,uganda,7,pop_unimproved_rural,1.837001e+07,1.837001e+07,0.0,cb:wali:technical_cost:sanitation:unimp_rural,0.0
4,PFLO:HBLE,0,uganda,8,pop_unimproved_rural,1.774752e+07,1.774752e+07,0.0,cb:wali:technical_cost:sanitation:unimp_rural,0.0

In [129]:
# --- Create a copy of the raw data ---
cb_data = cb_raw_df.copy()

# Split 'variable' into components: name, sector, cb_type, item_1, item_2
# (Assumes exactly 5 colon-separated parts; if there are more colons inside the last field,
# they will be kept in item_2 thanks to n=4)
cb_chars = cb_data["variable"].astype(str).str.split(":", n=4, expand=True)
cb_chars.columns = ["name", "sector", "cb_type", "item_1", "item_2"]
cb_data = pd.concat([cb_data, cb_chars], axis=1)
cb_data.head()

,strategy_code,future_id,region,time_period,difference_variable,variable_value_baseline,variable_value_pathway,difference_value,variable,value,name,sector,cb_type,item_1,item_2
0,PFLO:HBLE,0,uganda,4,pop_unimproved_rural,1.932346e+07,1.932346e+07,0.0,cb:wali:technical_cost:sanitation:unimp_rural,0.0,cb,wali,technical_cost,sanitation,unimp_rural
1,PFLO:HBLE,0,uganda,5,pop_unimproved_rural,1.951974e+07,1.951974e+07,0.0,cb:wali:technical_cost:sanitation:unimp_rural,0.0,cb,wali,technical_cost,sanitation,unimp_rural
2,PFLO:HBLE,0,uganda,6,pop_unimproved_rural,1.896047e+07,1.896047e+07,0.0,cb:wali:technical_cost:sanitation:unimp_rural,0.0,cb,wali,technical_cost,sanitation,unimp_rural
3,PFLO:HBLE,0,uganda,7,pop_unimproved_rural,1.837001e+07,1.837001e+07,0.0,cb:wali:technical_cost:sanitation:unimp_rural,0.0,cb,wali,technical_cost,sanitation,unimp_rural
4,PFLO:HBLE,0,uganda,8,pop_unimproved_rural,1.774752e+07,1.774752e+07,0.0,cb:wali:technical_cost:sanitation:unimp_rural,0.0,cb,wali,technical_cost,sanitation,unimp_rural

In [130]:
# Scale value from USD to billions (divide by 1e9)
if "value" in cb_data.columns:
    cb_data["value"] = cb_data["value"] / 1e9

# --- Remove "shifted" entries ---
# # Remove rows where item_2 contains "shifted"
# cb_data = cb_data[~cb_data["item_2"].astype(str).str.contains("shifted", na=False)]

# # Remove any remaining rows where variable contains "shifted2"
# cb_data = cb_data[~cb_data["variable"].astype(str).str.contains("shifted2", na=False)]

# --- Add Year column (Year = time_period + 2015) ---
cb_data["Year"] = cb_data["time_period"] + 2015

cb_data.head()

,strategy_code,future_id,region,time_period,difference_variable,variable_value_baseline,variable_value_pathway,difference_value,variable,value,name,sector,cb_type,item_1,item_2,Year
0,PFLO:HBLE,0,uganda,4,pop_unimproved_rural,1.932346e+07,1.932346e+07,0.0,cb:wali:technical_cost:sanitation:unimp_rural,0.0,cb,wali,technical_cost,sanitation,unimp_rural,2019
1,PFLO:HBLE,0,uganda,5,pop_unimproved_rural,1.951974e+07,1.951974e+07,0.0,cb:wali:technical_cost:sanitation:unimp_rural,0.0,cb,wali,technical_cost,sanitation,unimp_rural,2020
2,PFLO:HBLE,0,uganda,6,pop_unimproved_rural,1.896047e+07,1.896047e+07,0.0,cb:wali:technical_cost:sanitation:unimp_rural,0.0,cb,wali,technical_cost,sanitation,unimp_rural,2021
3,PFLO:HBLE,0,uganda,7,pop_unimproved_rural,1.837001e+07,1.837001e+07,0.0,cb:wali:technical_cost:sanitation:unimp_rural,0.0,cb,wali,technical_cost,sanitation,unimp_rural,2022
4,PFLO:HBLE,0,uganda,8,pop_unimproved_rural,1.774752e+07,1.774752e+07,0.0,cb:wali:technical_cost:sanitation:unimp_rural,0.0,cb,wali,technical_cost,sanitation,unimp_rural,2023

In [131]:
# Load attribute strategy
attribute_strategy_df = pd.read_csv(os.path.join(INPUT_DATA_DIR_PATH, "ATTRIBUTE_STRATEGY.csv"))
attribute_strategy_df = attribute_strategy_df[["strategy_id", "strategy_code"]]
attribute_strategy_df.head()

   strategy_id                                      strategy_code
0            0                                               BASE
1         6004                                          PFLO:HBLE
2         6559  WHIRLPOOL_PFLO_HBLE:TX:AGRC:DEC_CH4_RICE_STRAT...
3         6560  WHIRLPOOL_PFLO_HBLE:TX:AGRC:DEC_LOSSES_SUPPLY_...
4         6561  WHIRLPOOL_PFLO_HBLE:TX:AGRC:INC_CONSERVATION_A...

In [132]:
attribute_strategy_df.strategy_id.unique()

array([   0, 6004, 6559, 6560, 6561, 6562, 6563, 6564, 6565, 6566, 6567,
       6568, 6569, 6570, 6571, 6572, 6573, 6574, 6575, 6576, 6577, 6578,
       6579, 6580, 6581, 6582, 6583, 6584, 6585, 6586, 6587, 6588, 6589,
       6590, 6591, 6592, 6593, 6594, 6595, 6596, 6597, 6598, 6599, 6600,
       6601, 6602, 6603, 6604, 6605, 6606, 6607, 6608, 6609, 6610, 6611,
       6612, 6613, 6614, 6615, 6616, 6617])

In [133]:
attribute_strategy_df.strategy_code.unique()

array(['BASE', 'PFLO:HBLE',
       'WHIRLPOOL_PFLO_HBLE:TX:AGRC:DEC_CH4_RICE_STRATEGY_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:AGRC:DEC_LOSSES_SUPPLY_CHAIN_STRATEGY_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:AGRC:INC_CONSERVATION_AGRICULTURE_STRATEGY_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:AGRC:INC_PRODUCTIVITY_STRATEGY_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:ENTC:DEC_LOSSES_STRATEGY_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:ENTC:TARGET_CLEAN_HYDROGEN_STRATEGY_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:ENTC:TARGET_RENEWABLE_ELEC_STRATEGY_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:FGTV:DEC_LEAKS_STRATEGY_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:FGTV:INC_FLARE_STRATEGY_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:FRST:INCREASE_SEQUESTRATION_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:INEN:INC_EFFICIENCY_ENERGY_STRATEGY_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:INEN:SHIFT_FUEL_HEAT_STRATEGY_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:IPPU:DEC_CLINKER_STRATEGY_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:IPPU:DEC_HFCS_STRATEGY_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:IPPU:DEC_N2O_STRATEGY_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:IPPU:DEC_OTHER_FCS_STRATEGY_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:IPPU:DEC_PFCS_STRATEGY_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:LNDU:DEC_DEFORESTATION_STRATEGY_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:LNDU:DEC_WETLAND_LOSS_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:LNDU:INC_REFORESTATION_STRATEGY_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:LNDU:INC_SILVOPASTURE',
       'WHIRLPOOL_PFLO_HBLE:TX:LNDU:SET_WETLANDS_MINIMUM_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:LSMM:INC_CAPTURE_BIOGAS_STRATEGY_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:LSMM:INC_MANAGEMENT_CATTLE_PIGS_STRATEGY_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:LSMM:INC_MANAGEMENT_OTHER_STRATEGY_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:LSMM:INC_MANAGEMENT_POULTRY_STRATEGY_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:LVST:DEC_ENTERIC_FERMENTATION_STRATEGY_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:LVST:INC_PRODUCTIVITY_STRATEGY_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:PFLO:INC_HEALTHIER_DIETS',
       'WHIRLPOOL_PFLO_HBLE:TX:PFLO:INC_IND_CCS_STRATEGY_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:SCOE:DEC_DEMAND_HEAT_STRATEGY_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:SCOE:INC_EFFICIENCY_APPLIANCE_STRATEGY_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:SCOE:INC_EFFICIENCY_HEAT_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:SCOE:SHIFT_FUEL_HEAT_STRATEGY_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:SOIL:DEC_LIME_APPLIED_STRATEGY_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:SOIL:DEC_N_APPLIED_STRATEGY_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:TRDE:DEC_DEMAND_STRATEGY_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:TRNS:INC_EFFICIENCY_ELECTRIC_STRATEGY_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:TRNS:INC_EFFICIENCY_NON_ELECTRIC_STRATEGY_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:TRNS:INC_OCCUPANCY_LIGHT_DUTY_STRATEGY_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:TRNS:SHIFT_FUEL_LIGHT_DUTY_STRATEGY_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:TRNS:SHIFT_FUEL_MARITIME_STRATEGY_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:TRNS:SHIFT_FUEL_MEDIUM_DUTY_STRATEGY_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:TRNS:SHIFT_FUEL_RAIL_STRATEGY_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:TRNS:SHIFT_MODE_FREIGHT_STRATEGY_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:TRNS:SHIFT_MODE_PASSENGER_STRATEGY_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:TRNS:SHIFT_MODE_REGIONAL_STRATEGY_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:TRWW:INC_CAPTURE_BIOGAS_STRATEGY_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:TRWW:INC_COMPLIANCE_SEPTIC_STRATEGY_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:WALI:INC_TREATMENT_INDUSTRIAL_STRATEGY_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:WALI:INC_TREATMENT_RURAL_STRATEGY_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:WALI:INC_TREATMENT_URBAN_STRATEGY_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:WASO:DEC_CONSUMER_FOOD_WASTE_STRATEGY_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:WASO:INC_ANAEROBIC_AND_COMPOST_STRATEGY_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:WASO:INC_CAPTURE_BIOGAS_STRATEGY_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:WASO:INC_ENERGY_FROM_BIOGAS_STRATEGY_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:WASO:INC_ENERGY_FROM_INCINERATION_STRATEGY_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:WASO:INC_LANDFILLING_STRATEGY_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:WASO:INC_RECYCLING_STRATEGY_NZ'],
      dtype=object)

In [134]:
# Merge with cb_data on strategy_code
cb_data = cb_data.merge(attribute_strategy_df, on="strategy_code", how="left")
cb_data.head()

,strategy_code,future_id,region,time_period,difference_variable,variable_value_baseline,variable_value_pathway,difference_value,variable,value,name,sector,cb_type,item_1,item_2,Year,strategy_id
0,PFLO:HBLE,0,uganda,4,pop_unimproved_rural,1.932346e+07,1.932346e+07,0.0,cb:wali:technical_cost:sanitation:unimp_rural,0.0,cb,wali,technical_cost,sanitation,unimp_rural,2019,6004
1,PFLO:HBLE,0,uganda,5,pop_unimproved_rural,1.951974e+07,1.951974e+07,0.0,cb:wali:technical_cost:sanitation:unimp_rural,0.0,cb,wali,technical_cost,sanitation,unimp_rural,2020,6004
2,PFLO:HBLE,0,uganda,6,pop_unimproved_rural,1.896047e+07,1.896047e+07,0.0,cb:wali:technical_cost:sanitation:unimp_rural,0.0,cb,wali,technical_cost,sanitation,unimp_rural,2021,6004
3,PFLO:HBLE,0,uganda,7,pop_unimproved_rural,1.837001e+07,1.837001e+07,0.0,cb:wali:technical_cost:sanitation:unimp_rural,0.0,cb,wali,technical_cost,sanitation,unimp_rural,2022,6004
4,PFLO:HBLE,0,uganda,8,pop_unimproved_rural,1.774752e+07,1.774752e+07,0.0,cb:wali:technical_cost:sanitation:unimp_rural,0.0,cb,wali,technical_cost,sanitation,unimp_rural,2023,6004

In [135]:
cb_data.strategy_code.unique()

array(['PFLO:HBLE',
       'WHIRLPOOL_PFLO_HBLE:TX:AGRC:DEC_CH4_RICE_STRATEGY_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:AGRC:DEC_LOSSES_SUPPLY_CHAIN_STRATEGY_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:AGRC:INC_CONSERVATION_AGRICULTURE_STRATEGY_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:AGRC:INC_PRODUCTIVITY_STRATEGY_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:ENTC:DEC_LOSSES_STRATEGY_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:ENTC:TARGET_CLEAN_HYDROGEN_STRATEGY_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:ENTC:TARGET_RENEWABLE_ELEC_STRATEGY_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:FGTV:DEC_LEAKS_STRATEGY_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:FGTV:INC_FLARE_STRATEGY_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:FRST:INCREASE_SEQUESTRATION_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:INEN:INC_EFFICIENCY_ENERGY_STRATEGY_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:INEN:SHIFT_FUEL_HEAT_STRATEGY_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:IPPU:DEC_CLINKER_STRATEGY_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:IPPU:DEC_HFCS_STRATEGY_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:IPPU:DEC_N2O_STRATEGY_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:IPPU:DEC_OTHER_FCS_STRATEGY_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:IPPU:DEC_PFCS_STRATEGY_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:LNDU:DEC_DEFORESTATION_STRATEGY_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:LNDU:DEC_WETLAND_LOSS_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:LNDU:INC_REFORESTATION_STRATEGY_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:LNDU:INC_SILVOPASTURE',
       'WHIRLPOOL_PFLO_HBLE:TX:LNDU:SET_WETLANDS_MINIMUM_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:LSMM:INC_CAPTURE_BIOGAS_STRATEGY_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:LSMM:INC_MANAGEMENT_CATTLE_PIGS_STRATEGY_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:LSMM:INC_MANAGEMENT_OTHER_STRATEGY_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:LSMM:INC_MANAGEMENT_POULTRY_STRATEGY_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:LVST:DEC_ENTERIC_FERMENTATION_STRATEGY_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:LVST:INC_PRODUCTIVITY_STRATEGY_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:PFLO:INC_HEALTHIER_DIETS',
       'WHIRLPOOL_PFLO_HBLE:TX:PFLO:INC_IND_CCS_STRATEGY_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:SCOE:DEC_DEMAND_HEAT_STRATEGY_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:SCOE:INC_EFFICIENCY_APPLIANCE_STRATEGY_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:SCOE:INC_EFFICIENCY_HEAT_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:SCOE:SHIFT_FUEL_HEAT_STRATEGY_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:SOIL:DEC_LIME_APPLIED_STRATEGY_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:SOIL:DEC_N_APPLIED_STRATEGY_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:TRDE:DEC_DEMAND_STRATEGY_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:TRNS:INC_EFFICIENCY_ELECTRIC_STRATEGY_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:TRNS:INC_EFFICIENCY_NON_ELECTRIC_STRATEGY_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:TRNS:INC_OCCUPANCY_LIGHT_DUTY_STRATEGY_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:TRNS:SHIFT_FUEL_LIGHT_DUTY_STRATEGY_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:TRNS:SHIFT_FUEL_MARITIME_STRATEGY_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:TRNS:SHIFT_FUEL_MEDIUM_DUTY_STRATEGY_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:TRNS:SHIFT_FUEL_RAIL_STRATEGY_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:TRNS:SHIFT_MODE_FREIGHT_STRATEGY_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:TRNS:SHIFT_MODE_PASSENGER_STRATEGY_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:TRNS:SHIFT_MODE_REGIONAL_STRATEGY_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:TRWW:INC_CAPTURE_BIOGAS_STRATEGY_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:TRWW:INC_COMPLIANCE_SEPTIC_STRATEGY_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:WALI:INC_TREATMENT_INDUSTRIAL_STRATEGY_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:WALI:INC_TREATMENT_RURAL_STRATEGY_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:WALI:INC_TREATMENT_URBAN_STRATEGY_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:WASO:DEC_CONSUMER_FOOD_WASTE_STRATEGY_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:WASO:INC_ANAEROBIC_AND_COMPOST_STRATEGY_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:WASO:INC_CAPTURE_BIOGAS_STRATEGY_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:WASO:INC_ENERGY_FROM_BIOGAS_STRATEGY_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:WASO:INC_ENERGY_FROM_INCINERATION_STRATEGY_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:WASO:INC_LANDFILLING_STRATEGY_NZ',
       'WHIRLPOOL_PFLO_HBLE:TX:WASO:INC_RECYCLING_STRATEGY_NZ'],
      dtype=object)

In [136]:
cb_data.strategy_id.unique()

array([6004, 6559, 6560, 6561, 6562, 6563, 6564, 6565, 6566, 6567, 6568,
       6569, 6570, 6571, 6572, 6573, 6574, 6575, 6576, 6577, 6578, 6579,
       6580, 6581, 6582, 6583, 6584, 6585, 6586, 6587, 6588, 6589, 6590,
       6591, 6592, 6593, 6594, 6595, 6596, 6597, 6598, 6599, 6600, 6601,
       6602, 6603, 6604, 6605, 6606, 6607, 6608, 6609, 6610, 6611, 6612,
       6613, 6614, 6615, 6616, 6617])

In [137]:
# check for nans in strategy_id
cb_data[cb_data['strategy_id'].isna()]['strategy_code'].unique()

array([], dtype=object)

In [138]:
cb_data["sector"].unique()

array(['wali', 'entc', 'trns', 'lndu', 'waso', 'trww', 'lvst', 'agrc',
       'ccsq', 'inen', 'scoe', 'ippu', 'soil', 'lsmm', 'fgtv', 'pflo'],
      dtype=object)

In [139]:
cb_data.head()

,strategy_code,future_id,region,time_period,difference_variable,variable_value_baseline,variable_value_pathway,difference_value,variable,value,name,sector,cb_type,item_1,item_2,Year,strategy_id
0,PFLO:HBLE,0,uganda,4,pop_unimproved_rural,1.932346e+07,1.932346e+07,0.0,cb:wali:technical_cost:sanitation:unimp_rural,0.0,cb,wali,technical_cost,sanitation,unimp_rural,2019,6004
1,PFLO:HBLE,0,uganda,5,pop_unimproved_rural,1.951974e+07,1.951974e+07,0.0,cb:wali:technical_cost:sanitation:unimp_rural,0.0,cb,wali,technical_cost,sanitation,unimp_rural,2020,6004
2,PFLO:HBLE,0,uganda,6,pop_unimproved_rural,1.896047e+07,1.896047e+07,0.0,cb:wali:technical_cost:sanitation:unimp_rural,0.0,cb,wali,technical_cost,sanitation,unimp_rural,2021,6004
3,PFLO:HBLE,0,uganda,7,pop_unimproved_rural,1.837001e+07,1.837001e+07,0.0,cb:wali:technical_cost:sanitation:unimp_rural,0.0,cb,wali,technical_cost,sanitation,unimp_rural,2022,6004
4,PFLO:HBLE,0,uganda,8,pop_unimproved_rural,1.774752e+07,1.774752e+07,0.0,cb:wali:technical_cost:sanitation:unimp_rural,0.0,cb,wali,technical_cost,sanitation,unimp_rural,2023,6004

In [140]:
# filter sectors
# target_sectors = ["wali", "trww", "waso", "soil", "ippu", "lvst", "agrc", "lndu", "lsmm"]
# cb_data = cb_data[cb_data["sector"].isin(target_sectors)].copy()
cb_data.head()

,strategy_code,future_id,region,time_period,difference_variable,variable_value_baseline,variable_value_pathway,difference_value,variable,value,name,sector,cb_type,item_1,item_2,Year,strategy_id
0,PFLO:HBLE,0,uganda,4,pop_unimproved_rural,1.932346e+07,1.932346e+07,0.0,cb:wali:technical_cost:sanitation:unimp_rural,0.0,cb,wali,technical_cost,sanitation,unimp_rural,2019,6004
1,PFLO:HBLE,0,uganda,5,pop_unimproved_rural,1.951974e+07,1.951974e+07,0.0,cb:wali:technical_cost:sanitation:unimp_rural,0.0,cb,wali,technical_cost,sanitation,unimp_rural,2020,6004
2,PFLO:HBLE,0,uganda,6,pop_unimproved_rural,1.896047e+07,1.896047e+07,0.0,cb:wali:technical_cost:sanitation:unimp_rural,0.0,cb,wali,technical_cost,sanitation,unimp_rural,2021,6004
3,PFLO:HBLE,0,uganda,7,pop_unimproved_rural,1.837001e+07,1.837001e+07,0.0,cb:wali:technical_cost:sanitation:unimp_rural,0.0,cb,wali,technical_cost,sanitation,unimp_rural,2022,6004
4,PFLO:HBLE,0,uganda,8,pop_unimproved_rural,1.774752e+07,1.774752e+07,0.0,cb:wali:technical_cost:sanitation:unimp_rural,0.0,cb,wali,technical_cost,sanitation,unimp_rural,2023,6004

In [141]:
# aggregate sum(value) grouped by strategy_id and cb_type
cb_data = (
    cb_data.groupby(["strategy_id", "cb_type"], as_index=False)["value"]
      .sum()
      .rename(columns={"value": "cumulative"})
)
cb_data.head(20)

    strategy_id             cb_type  cumulative
0          6004       air_pollution   26.625151
1          6004          congestion   20.962109
2          6004    consumer_savings  645.328072
3          6004          crop_value   74.746558
4          6004  ecosystem_services   21.386132
5          6004       env_pollution   99.385001
6          6004           fuel_cost  145.671458
7          6004        human_health  733.968321
8          6004          ippu_value    1.017973
9          6004      land_pollution    0.537227
10         6004          lvst_value  -77.804845
11         6004         road_safety   28.616772
12         6004     sector_specific   95.235397
13         6004         system_cost  279.293719
14         6004      technical_cost -868.755470
15         6004   technical_savings  159.455876
16         6004     water_pollution  187.468079
17         6559       air_pollution   26.625151
18         6559          congestion   20.962109
19         6559    consumer_savings  645.328072

In [142]:
# unique cb_data types
cb_cats = cb_data["cb_type"].unique().tolist()

# long -> wide (R dcast equivalent)
wide_cb = (
    cb_data.pivot(index="strategy_id", columns="cb_type", values="cumulative")
      .reset_index()
)

# optional: remove column name from pivot for nicer printing
wide_cb.columns.name = None
wide_cb.head()

,strategy_id,air_pollution,congestion,consumer_savings,crop_value,ecosystem_services,env_pollution,fuel_cost,human_health,ippu_value,land_pollution,lvst_value,road_safety,sector_specific,system_cost,technical_cost,technical_savings,water_pollution
0,6004,26.625151,20.962109,645.328072,74.746558,21.386132,99.385001,145.671458,733.968321,1.017973,0.537227,-77.804845,28.616772,95.235397,279.293719,-868.755470,159.455876,187.468079
1,6559,26.625151,20.962109,645.328072,74.746558,21.386132,99.385001,145.671458,733.968321,1.017973,0.537227,-77.804845,28.616772,95.235397,279.293719,-868.599909,159.455876,187.468079
2,6560,26.620185,20.962109,682.695948,141.580738,19.255938,98.512880,149.917212,733.968321,1.017973,0.489859,-78.609346,28.616772,95.230210,279.293719,-892.079956,10.903235,187.468078
3,6561,26.625151,20.962109,606.052311,74.746558,21.386132,99.385001,145.671458,733.968321,1.017973,0.537227,-77.804845,28.616772,95.235397,279.293719,-868.755470,154.855001,187.468079
4,6562,26.661374,20.962109,657.698461,-55.932584,9.867836,99.385001,144.842012,733.968321,1.017973,0.265388,-88.891365,28.616772,95.639963,279.293719,-864.643483,160.875975,187.468080

In [143]:
cb_cats

['air_pollution',
 'congestion',
 'consumer_savings',
 'crop_value',
 'ecosystem_services',
 'env_pollution',
 'fuel_cost',
 'human_health',
 'ippu_value',
 'land_pollution',
 'lvst_value',
 'road_safety',
 'sector_specific',
 'system_cost',
 'technical_cost',
 'technical_savings',
 'water_pollution']

In [144]:
# --- 1) net_benefit = rowSums over all cb categories ---
wide_cb["net_benefit"] = wide_cb[cb_cats].sum(axis=1, skipna=True)

# --- 2) additional_benefits = rowSums excluding "technical_cost" ---
benefit_cols = [c for c in cb_cats if c != "technical_cost"]
wide_cb["additional_benefits"] = wide_cb[benefit_cols].sum(axis=1, skipna=True)

# --- 3) total_transformation_costs = rowSums over specific cols ---
cost_cols = ["technical_cost", "technical_savings", "fuel_cost"]

# (safe version: only use cols that exist in the df)
cost_cols = [c for c in cost_cols if c in wide_cb.columns]

wide_cb["total_transformation_costs"] = wide_cb[cost_cols].sum(axis=1, skipna=True)
wide_cb.head()

,strategy_id,air_pollution,congestion,consumer_savings,crop_value,ecosystem_services,env_pollution,fuel_cost,human_health,ippu_value,...,lvst_value,road_safety,sector_specific,system_cost,technical_cost,technical_savings,water_pollution,net_benefit,additional_benefits,total_transformation_costs
0,6004,26.625151,20.962109,645.328072,74.746558,21.386132,99.385001,145.671458,733.968321,1.017973,...,-77.804845,28.616772,95.235397,279.293719,-868.755470,159.455876,187.468079,1573.137529,2441.892999,-563.628136
1,6559,26.625151,20.962109,645.328072,74.746558,21.386132,99.385001,145.671458,733.968321,1.017973,...,-77.804845,28.616772,95.235397,279.293719,-868.599909,159.455876,187.468079,1573.293091,2441.892999,-563.472575
2,6560,26.620185,20.962109,682.695948,141.580738,19.255938,98.512880,149.917212,733.968321,1.017973,...,-78.609346,28.616772,95.230210,279.293719,-892.079956,10.903235,187.468078,1505.843875,2397.923831,-731.259509
3,6561,26.625151,20.962109,606.052311,74.746558,21.386132,99.385001,145.671458,733.968321,1.017973,...,-77.804845,28.616772,95.235397,279.293719,-868.755470,154.855001,187.468079,1529.260894,2398.016364,-568.229011
4,6562,26.661374,20.962109,657.698461,-55.932584,9.867836,99.385001,144.842012,733.968321,1.017973,...,-88.891365,28.616772,95.639963,279.293719,-864.643483,160.875975,187.468080,1437.095550,2301.739033,-558.925497

## Merge emissions and cb data and save

In [145]:
tornado_emissions_agg_extended_df[tornado_emissions_agg_extended_df.strategy == "NZ"]

Empty DataFrame
Columns: [strategy_id, primary_id, strategy, emission_total, base_emission_total, emission_diff, sector, transformation_name]
Index: []

In [146]:
wide_cb.strategy_id.unique()

array([6004, 6559, 6560, 6561, 6562, 6563, 6564, 6565, 6566, 6567, 6568,
       6569, 6570, 6571, 6572, 6573, 6574, 6575, 6576, 6577, 6578, 6579,
       6580, 6581, 6582, 6583, 6584, 6585, 6586, 6587, 6588, 6589, 6590,
       6591, 6592, 6593, 6594, 6595, 6596, 6597, 6598, 6599, 6600, 6601,
       6602, 6603, 6604, 6605, 6606, 6607, 6608, 6609, 6610, 6611, 6612,
       6613, 6614, 6615, 6616, 6617])

In [147]:
print(wide_cb.shape)
print(tornado_emissions_agg_extended_df.shape)

(60, 21)
(60, 8)

In [148]:
df_merged = pd.merge(
    tornado_emissions_agg_extended_df,
    wide_cb,
    on="strategy_id",
    how="inner"
)

df_merged.head()

,strategy_id,primary_id,strategy,emission_total,base_emission_total,emission_diff,sector,transformation_name,air_pollution,congestion,...,lvst_value,road_safety,sector_specific,system_cost,technical_cost,technical_savings,water_pollution,net_benefit,additional_benefits,total_transformation_costs
0,6004.0,700070.0,HBLE,4901.538826,4901.538826,0.000000,NaN,,26.625151,20.962109,...,-77.804845,28.616772,95.235397,279.293719,-868.755470,159.455876,187.468079,1573.137529,2441.892999,-563.628136
1,6559.0,1350135.0,Remove TX:AGRC:DEC_CH4_RICE_STRATEGY_NZ from HBLE,4903.261177,4901.538826,1.722351,AGRC,DEC_CH4_RICE_STRATEGY_NZ,26.625151,20.962109,...,-77.804845,28.616772,95.235397,279.293719,-868.599909,159.455876,187.468079,1573.293091,2441.892999,-563.472575
2,6560.0,1360136.0,Remove TX:AGRC:DEC_LOSSES_SUPPLY_CHAIN_STRATEG...,4994.242403,4901.538826,92.703577,AGRC,DEC_LOSSES_SUPPLY_CHAIN_STRATEGY_NZ,26.620185,20.962109,...,-78.609346,28.616772,95.230210,279.293719,-892.079956,10.903235,187.468078,1505.843875,2397.923831,-731.259509
3,6561.0,1370137.0,Remove TX:AGRC:INC_CONSERVATION_AGRICULTURE_ST...,4899.663997,4901.538826,-1.874829,AGRC,INC_CONSERVATION_AGRICULTURE_STRATEGY_NZ,26.625151,20.962109,...,-77.804845,28.616772,95.235397,279.293719,-868.755470,154.855001,187.468079,1529.260894,2398.016364,-568.229011
4,6562.0,1380138.0,Remove TX:AGRC:INC_PRODUCTIVITY_STRATEGY_NZ fr...,5186.463871,4901.538826,284.925045,AGRC,INC_PRODUCTIVITY_STRATEGY_NZ,26.661374,20.962109,...,-88.891365,28.616772,95.639963,279.293719,-864.643483,160.875975,187.468080,1437.095550,2301.739033,-558.925497

In [149]:
df_merged = df_merged[df_merged['strategy'] != 'HBLE']

df_merged.head()

,strategy_id,primary_id,strategy,emission_total,base_emission_total,emission_diff,sector,transformation_name,air_pollution,congestion,...,lvst_value,road_safety,sector_specific,system_cost,technical_cost,technical_savings,water_pollution,net_benefit,additional_benefits,total_transformation_costs
1,6559.0,1350135.0,Remove TX:AGRC:DEC_CH4_RICE_STRATEGY_NZ from HBLE,4903.261177,4901.538826,1.722351,AGRC,DEC_CH4_RICE_STRATEGY_NZ,26.625151,20.962109,...,-77.804845,28.616772,95.235397,279.293719,-868.599909,159.455876,187.468079,1573.293091,2441.892999,-563.472575
2,6560.0,1360136.0,Remove TX:AGRC:DEC_LOSSES_SUPPLY_CHAIN_STRATEG...,4994.242403,4901.538826,92.703577,AGRC,DEC_LOSSES_SUPPLY_CHAIN_STRATEGY_NZ,26.620185,20.962109,...,-78.609346,28.616772,95.230210,279.293719,-892.079956,10.903235,187.468078,1505.843875,2397.923831,-731.259509
3,6561.0,1370137.0,Remove TX:AGRC:INC_CONSERVATION_AGRICULTURE_ST...,4899.663997,4901.538826,-1.874829,AGRC,INC_CONSERVATION_AGRICULTURE_STRATEGY_NZ,26.625151,20.962109,...,-77.804845,28.616772,95.235397,279.293719,-868.755470,154.855001,187.468079,1529.260894,2398.016364,-568.229011
4,6562.0,1380138.0,Remove TX:AGRC:INC_PRODUCTIVITY_STRATEGY_NZ fr...,5186.463871,4901.538826,284.925045,AGRC,INC_PRODUCTIVITY_STRATEGY_NZ,26.661374,20.962109,...,-88.891365,28.616772,95.639963,279.293719,-864.643483,160.875975,187.468080,1437.095550,2301.739033,-558.925497
5,6563.0,1390139.0,Remove TX:ENTC:DEC_LOSSES_STRATEGY_NZ from HBLE,4902.499773,4901.538826,0.960948,ENTC,DEC_LOSSES_STRATEGY_NZ,26.625006,20.962109,...,-77.804845,28.616772,95.235300,279.293719,-869.307054,159.770482,187.468079,1572.900309,2442.207363,-563.865114

In [150]:
print(df_merged.shape)

(59, 28)

### Below we have some hardcoded fixed exclusive of this study case to replace incorrect tranformation names

In [151]:
df_merged.columns

Index(['strategy_id', 'primary_id', 'strategy', 'emission_total',
       'base_emission_total', 'emission_diff', 'sector', 'transformation_name',
       'air_pollution', 'congestion', 'consumer_savings', 'crop_value',
       'ecosystem_services', 'env_pollution', 'fuel_cost', 'human_health',
       'ippu_value', 'land_pollution', 'lvst_value', 'road_safety',
       'sector_specific', 'system_cost', 'technical_cost', 'technical_savings',
       'water_pollution', 'net_benefit', 'additional_benefits',
       'total_transformation_costs'],
      dtype='object')

In [152]:
# Get the base technical cost from wide_cb (strategy_id 6004)
base_technical_cost = (wide_cb[wide_cb['strategy_id'] == 6004]['technical_cost'].values[0])*-1
base_technical_cost

np.float64(868.7554699905073)

In [153]:
# multiply technical_cost by -1 to get positive costs
df_merged['technical_cost'] = df_merged['technical_cost'] * -1

df_merged['technical_cost'] = base_technical_cost - df_merged['technical_cost'] 

# create marginal total abatement cost column
df_merged['marginal_total_abatement_cost_(USD/tCO2e)'] = (df_merged['technical_cost'] / df_merged['emission_diff'])*1000

# If technical_cost is positive then marginal_total_abatement_cost should be positive too.
df_merged["marginal_total_abatement_cost_(USD/tCO2e)"] = df_merged["marginal_total_abatement_cost_(USD/tCO2e)"].abs() * np.sign(df_merged["technical_cost"])

In [154]:
df_merged.head()

,strategy_id,primary_id,strategy,emission_total,base_emission_total,emission_diff,sector,transformation_name,air_pollution,congestion,...,road_safety,sector_specific,system_cost,technical_cost,technical_savings,water_pollution,net_benefit,additional_benefits,total_transformation_costs,marginal_total_abatement_cost_(USD/tCO2e)
1,6559.0,1350135.0,Remove TX:AGRC:DEC_CH4_RICE_STRATEGY_NZ from HBLE,4903.261177,4901.538826,1.722351,AGRC,DEC_CH4_RICE_STRATEGY_NZ,26.625151,20.962109,...,28.616772,95.235397,279.293719,0.155561,159.455876,187.468079,1573.293091,2441.892999,-563.472575,90.319228
2,6560.0,1360136.0,Remove TX:AGRC:DEC_LOSSES_SUPPLY_CHAIN_STRATEG...,4994.242403,4901.538826,92.703577,AGRC,DEC_LOSSES_SUPPLY_CHAIN_STRATEGY_NZ,26.620185,20.962109,...,28.616772,95.230210,279.293719,-23.324486,10.903235,187.468078,1505.843875,2397.923831,-731.259509,-251.602872
3,6561.0,1370137.0,Remove TX:AGRC:INC_CONSERVATION_AGRICULTURE_ST...,4899.663997,4901.538826,-1.874829,AGRC,INC_CONSERVATION_AGRICULTURE_STRATEGY_NZ,26.625151,20.962109,...,28.616772,95.235397,279.293719,0.000000,154.855001,187.468079,1529.260894,2398.016364,-568.229011,0.000000
4,6562.0,1380138.0,Remove TX:AGRC:INC_PRODUCTIVITY_STRATEGY_NZ fr...,5186.463871,4901.538826,284.925045,AGRC,INC_PRODUCTIVITY_STRATEGY_NZ,26.661374,20.962109,...,28.616772,95.639963,279.293719,4.111987,160.875975,187.468080,1437.095550,2301.739033,-558.925497,14.431821
5,6563.0,1390139.0,Remove TX:ENTC:DEC_LOSSES_STRATEGY_NZ from HBLE,4902.499773,4901.538826,0.960948,ENTC,DEC_LOSSES_STRATEGY_NZ,26.625006,20.962109,...,28.616772,95.235300,279.293719,-0.551584,159.770482,187.468079,1572.900309,2442.207363,-563.865114,-573.999959

In [155]:
df_merged["strategy"].unique()

array(['Remove TX:AGRC:DEC_CH4_RICE_STRATEGY_NZ from HBLE',
       'Remove TX:AGRC:DEC_LOSSES_SUPPLY_CHAIN_STRATEGY_NZ from HBLE',
       'Remove TX:AGRC:INC_CONSERVATION_AGRICULTURE_STRATEGY_NZ from HBLE',
       'Remove TX:AGRC:INC_PRODUCTIVITY_STRATEGY_NZ from HBLE',
       'Remove TX:ENTC:DEC_LOSSES_STRATEGY_NZ from HBLE',
       'Remove TX:ENTC:TARGET_CLEAN_HYDROGEN_STRATEGY_NZ from HBLE',
       'Remove TX:ENTC:TARGET_RENEWABLE_ELEC_STRATEGY_NZ from HBLE',
       'Remove TX:FGTV:DEC_LEAKS_STRATEGY_NZ from HBLE',
       'Remove TX:FGTV:INC_FLARE_STRATEGY_NZ from HBLE',
       'Remove TX:FRST:INCREASE_SEQUESTRATION_NZ from HBLE',
       'Remove TX:INEN:INC_EFFICIENCY_ENERGY_STRATEGY_NZ from HBLE',
       'Remove TX:INEN:SHIFT_FUEL_HEAT_STRATEGY_NZ from HBLE',
       'Remove TX:IPPU:DEC_CLINKER_STRATEGY_NZ from HBLE',
       'Remove TX:IPPU:DEC_HFCS_STRATEGY_NZ from HBLE',
       'Remove TX:IPPU:DEC_N2O_STRATEGY_NZ from HBLE',
       'Remove TX:IPPU:DEC_OTHER_FCS_STRATEGY_NZ from HBLE',
       'Remove TX:IPPU:DEC_PFCS_STRATEGY_NZ from HBLE',
       'Remove TX:LNDU:DEC_DEFORESTATION_STRATEGY_NZ from HBLE',
       'Remove TX:LNDU:DEC_WETLAND_LOSS_NZ from HBLE',
       'Remove TX:LNDU:INC_REFORESTATION_STRATEGY_NZ from HBLE',
       'Remove TX:LNDU:INC_SILVOPASTURE from HBLE',
       'Remove TX:LNDU:SET_WETLANDS_MINIMUM_NZ from HBLE',
       'Remove TX:LSMM:INC_CAPTURE_BIOGAS_STRATEGY_NZ from HBLE',
       'Remove TX:LSMM:INC_MANAGEMENT_CATTLE_PIGS_STRATEGY_NZ from HBLE',
       'Remove TX:LSMM:INC_MANAGEMENT_OTHER_STRATEGY_NZ from HBLE',
       'Remove TX:LSMM:INC_MANAGEMENT_POULTRY_STRATEGY_NZ from HBLE',
       'Remove TX:LVST:DEC_ENTERIC_FERMENTATION_STRATEGY_NZ from HBLE',
       'Remove TX:LVST:INC_PRODUCTIVITY_STRATEGY_NZ from HBLE',
       'Remove TX:PFLO:INC_HEALTHIER_DIETS from HBLE',
       'Remove TX:PFLO:INC_IND_CCS_STRATEGY_NZ from HBLE',
       'Remove TX:SCOE:DEC_DEMAND_HEAT_STRATEGY_NZ from HBLE',
       'Remove TX:SCOE:INC_EFFICIENCY_APPLIANCE_STRATEGY_NZ from HBLE',
       'Remove TX:SCOE:INC_EFFICIENCY_HEAT_NZ from HBLE',
       'Remove TX:SCOE:SHIFT_FUEL_HEAT_STRATEGY_NZ from HBLE',
       'Remove TX:SOIL:DEC_LIME_APPLIED_STRATEGY_NZ from HBLE',
       'Remove TX:SOIL:DEC_N_APPLIED_STRATEGY_NZ from HBLE',
       'Remove TX:TRDE:DEC_DEMAND_STRATEGY_NZ from HBLE',
       'Remove TX:TRNS:INC_EFFICIENCY_ELECTRIC_STRATEGY_NZ from HBLE',
       'Remove TX:TRNS:INC_EFFICIENCY_NON_ELECTRIC_STRATEGY_NZ from HBLE',
       'Remove TX:TRNS:INC_OCCUPANCY_LIGHT_DUTY_STRATEGY_NZ from HBLE',
       'Remove TX:TRNS:SHIFT_FUEL_LIGHT_DUTY_STRATEGY_NZ from HBLE',
       'Remove TX:TRNS:SHIFT_FUEL_MARITIME_STRATEGY_NZ from HBLE',
       'Remove TX:TRNS:SHIFT_FUEL_MEDIUM_DUTY_STRATEGY_NZ from HBLE',
       'Remove TX:TRNS:SHIFT_FUEL_RAIL_STRATEGY_NZ from HBLE',
       'Remove TX:TRNS:SHIFT_MODE_FREIGHT_STRATEGY_NZ from HBLE',
       'Remove TX:TRNS:SHIFT_MODE_PASSENGER_STRATEGY_NZ from HBLE',
       'Remove TX:TRNS:SHIFT_MODE_REGIONAL_STRATEGY_NZ from HBLE',
       'Remove TX:TRWW:INC_CAPTURE_BIOGAS_STRATEGY_NZ from HBLE',
       'Remove TX:TRWW:INC_COMPLIANCE_SEPTIC_STRATEGY_NZ from HBLE',
       'Remove TX:WALI:INC_TREATMENT_INDUSTRIAL_STRATEGY_NZ from HBLE',
       'Remove TX:WALI:INC_TREATMENT_RURAL_STRATEGY_NZ from HBLE',
       'Remove TX:WALI:INC_TREATMENT_URBAN_STRATEGY_NZ from HBLE',
       'Remove TX:WASO:DEC_CONSUMER_FOOD_WASTE_STRATEGY_NZ from HBLE',
       'Remove TX:WASO:INC_ANAEROBIC_AND_COMPOST_STRATEGY_NZ from HBLE',
       'Remove TX:WASO:INC_CAPTURE_BIOGAS_STRATEGY_NZ from HBLE',
       'Remove TX:WASO:INC_ENERGY_FROM_BIOGAS_STRATEGY_NZ from HBLE',
       'Remove TX:WASO:INC_ENERGY_FROM_INCINERATION_STRATEGY_NZ from HBLE',
       'Remove TX:WASO:INC_LANDFILLING_STRATEGY_NZ from HBLE',
       'Remove TX:WASO:INC_RECYCLING_STRATEGY_NZ from HBLE'], dtype=object)

In [156]:
df_merged['transformation_name_sector'] = df_merged['transformation_name'] + " - " + df_merged['sector']

In [157]:
df_merged.to_csv(os.path.join(OUTPUT_DATA_DIR_PATH, "tornado_plot_whirlpool.csv"), index=False)

### Create a QA version

In [158]:
df_merged.head()

,strategy_id,primary_id,strategy,emission_total,base_emission_total,emission_diff,sector,transformation_name,air_pollution,congestion,...,sector_specific,system_cost,technical_cost,technical_savings,water_pollution,net_benefit,additional_benefits,total_transformation_costs,marginal_total_abatement_cost_(USD/tCO2e),transformation_name_sector
1,6559.0,1350135.0,Remove TX:AGRC:DEC_CH4_RICE_STRATEGY_NZ from HBLE,4903.261177,4901.538826,1.722351,AGRC,DEC_CH4_RICE_STRATEGY_NZ,26.625151,20.962109,...,95.235397,279.293719,0.155561,159.455876,187.468079,1573.293091,2441.892999,-563.472575,90.319228,DEC_CH4_RICE_STRATEGY_NZ - AGRC
2,6560.0,1360136.0,Remove TX:AGRC:DEC_LOSSES_SUPPLY_CHAIN_STRATEG...,4994.242403,4901.538826,92.703577,AGRC,DEC_LOSSES_SUPPLY_CHAIN_STRATEGY_NZ,26.620185,20.962109,...,95.230210,279.293719,-23.324486,10.903235,187.468078,1505.843875,2397.923831,-731.259509,-251.602872,DEC_LOSSES_SUPPLY_CHAIN_STRATEGY_NZ - AGRC
3,6561.0,1370137.0,Remove TX:AGRC:INC_CONSERVATION_AGRICULTURE_ST...,4899.663997,4901.538826,-1.874829,AGRC,INC_CONSERVATION_AGRICULTURE_STRATEGY_NZ,26.625151,20.962109,...,95.235397,279.293719,0.000000,154.855001,187.468079,1529.260894,2398.016364,-568.229011,0.000000,INC_CONSERVATION_AGRICULTURE_STRATEGY_NZ - AGRC
4,6562.0,1380138.0,Remove TX:AGRC:INC_PRODUCTIVITY_STRATEGY_NZ fr...,5186.463871,4901.538826,284.925045,AGRC,INC_PRODUCTIVITY_STRATEGY_NZ,26.661374,20.962109,...,95.639963,279.293719,4.111987,160.875975,187.468080,1437.095550,2301.739033,-558.925497,14.431821,INC_PRODUCTIVITY_STRATEGY_NZ - AGRC
5,6563.0,1390139.0,Remove TX:ENTC:DEC_LOSSES_STRATEGY_NZ from HBLE,4902.499773,4901.538826,0.960948,ENTC,DEC_LOSSES_STRATEGY_NZ,26.625006,20.962109,...,95.235300,279.293719,-0.551584,159.770482,187.468079,1572.900309,2442.207363,-563.865114,-573.999959,DEC_LOSSES_STRATEGY_NZ - ENTC

In [159]:
df_merged.sector.unique()

array(['AGRC', 'ENTC', 'FGTV', 'FRST', 'INEN', 'IPPU', 'LNDU', 'LSMM',
       'LVST', 'PFLO', 'SCOE', 'SOIL', 'TRDE', 'TRNS', 'TRWW', 'WALI',
       'WASO'], dtype=object)

In [160]:
relevant_fields = [
    "transformation_name",
    "sector",
    "base_emission_total",
    "emission_total",
    "emission_diff",
    "technical_cost",
    "marginal_total_abatement_cost_(USD/tCO2e)"
]

# keep only relevant fields
df_merged_filtered = df_merged[relevant_fields]
df_merged_filtered.head()

,transformation_name,sector,base_emission_total,emission_total,emission_diff,technical_cost,marginal_total_abatement_cost_(USD/tCO2e)
1,DEC_CH4_RICE_STRATEGY_NZ,AGRC,4901.538826,4903.261177,1.722351,0.155561,90.319228
2,DEC_LOSSES_SUPPLY_CHAIN_STRATEGY_NZ,AGRC,4901.538826,4994.242403,92.703577,-23.324486,-251.602872
3,INC_CONSERVATION_AGRICULTURE_STRATEGY_NZ,AGRC,4901.538826,4899.663997,-1.874829,0.000000,0.000000
4,INC_PRODUCTIVITY_STRATEGY_NZ,AGRC,4901.538826,5186.463871,284.925045,4.111987,14.431821
5,DEC_LOSSES_STRATEGY_NZ,ENTC,4901.538826,4902.499773,0.960948,-0.551584,-573.999959

In [161]:
df_merged_filtered

,transformation_name,sector,base_emission_total,emission_total,emission_diff,technical_cost,marginal_total_abatement_cost_(USD/tCO2e)
1,DEC_CH4_RICE_STRATEGY_NZ,AGRC,4901.538826,4903.261177,1.722351e+00,0.155561,9.031923e+01
2,DEC_LOSSES_SUPPLY_CHAIN_STRATEGY_NZ,AGRC,4901.538826,4994.242403,9.270358e+01,-23.324486,-2.516029e+02
3,INC_CONSERVATION_AGRICULTURE_STRATEGY_NZ,AGRC,4901.538826,4899.663997,-1.874829e+00,0.000000,0.000000e+00
4,INC_PRODUCTIVITY_STRATEGY_NZ,AGRC,4901.538826,5186.463871,2.849250e+02,4.111987,1.443182e+01
5,DEC_LOSSES_STRATEGY_NZ,ENTC,4901.538826,4902.499773,9.609476e-01,-0.551584,-5.740000e+02
6,TARGET_CLEAN_HYDROGEN_STRATEGY_NZ,ENTC,4901.538826,4901.538826,0.000000e+00,0.000000,NaN
7,TARGET_RENEWABLE_ELEC_STRATEGY_NZ,ENTC,4901.538826,4997.819521,9.628069e+01,-7.800535,-8.101868e+01
8,DEC_LEAKS_STRATEGY_NZ,FGTV,4901.538826,4910.389075,8.850249e+00,0.074521,8.420182e+00
9,INC_FLARE_STRATEGY_NZ,FGTV,4901.538826,4901.550832,1.200617e-02,-0.013862,-1.154550e+03
10,INCREASE_SEQUESTRATION_NZ,FRST,4901.538826,4981.944477,8.040565e+01,-0.000248,-3.084372e-03
11,INC_EFFICIENCY_ENERGY_STRATEGY_NZ,INEN,4901.538826,4976.549133,7.501031e+01,20.575229,2.742987e+02
12,SHIFT_FUEL_HEAT_STRATEGY_NZ,INEN,4901.538826,5179.261545,2.777227e+02,11.350500,4.086990e+01
13,DEC_CLINKER_STRATEGY_NZ,IPPU,4901.538826,4903.232071,1.693245e+00,-0.000248,-1.464661e-01
14,DEC_HFCS_STRATEGY_NZ,IPPU,4901.538826,4901.538826,9.094947e-13,-0.000248,-2.726805e+11
15,DEC_N2O_STRATEGY_NZ,IPPU,4901.538826,4901.538826,5.456968e-12,-0.000248,-4.544677e+10
16,DEC_OTHER_FCS_STRATEGY_NZ,IPPU,4901.538826,4901.538826,9.094947e-13,-0.000248,-2.726822e+11
17,DEC_PFCS_STRATEGY_NZ,IPPU,4901.538826,4901.538826,1.818989e-12,-0.000248,-1.363398e+11
18,DEC_DEFORESTATION_STRATEGY_NZ,LNDU,4901.538826,5544.667214,6.431284e+02,3.304316,5.137879e+00
19,DEC_WETLAND_LOSS_NZ,LNDU,4901.538826,4925.259034,2.372021e+01,-1.623115,-6.842750e+01
20,INC_REFORESTATION_STRATEGY_NZ,LNDU,4901.538826,4997.962388,9.642356e+01,6.398983,6.636327e+01
21,INC_SILVOPASTURE,LNDU,4901.538826,4902.955340,1.416514e+00,3.074640,2.170568e+03
22,SET_WETLANDS_MINIMUM_NZ,LNDU,4901.538826,4901.538826,0.000000e+00,-0.000248,-inf
23,INC_CAPTURE_BIOGAS_STRATEGY_NZ,LSMM,4901.538826,4925.578374,2.403955e+01,-0.495593,-2.061572e+01
24,INC_MANAGEMENT_CATTLE_PIGS_STRATEGY_NZ,LSMM,4901.538826,5053.252645,1.517138e+02,10.135554,6.680706e+01
25,INC_MANAGEMENT_OTHER_STRATEGY_NZ,LSMM,4901.538826,4932.958301,3.141948e+01,-0.305908,-9.736252e+00
26,INC_MANAGEMENT_POULTRY_STRATEGY_NZ,LSMM,4901.538826,4925.298567,2.375974e+01,0.325725,1.370910e+01
27,DEC_ENTERIC_FERMENTATION_STRATEGY_NZ,LVST,4901.538826,5414.068141,5.125293e+02,9.934785,1.938384e+01
28,INC_PRODUCTIVITY_STRATEGY_NZ,LVST,4901.538826,4857.179086,-4.435974e+01,0.355759,8.019868e+00
29,INC_HEALTHIER_DIETS,PFLO,4901.538826,5247.043532,3.455047e+02,2.133028,6.173658e+00
30,INC_IND_CCS_STRATEGY_NZ,PFLO,4901.538826,4915.966434,1.442761e+01,6.000732,4.159201e+02
31,DEC_DEMAND_HEAT_STRATEGY_NZ,SCOE,4901.538826,5117.220113,2.156813e+02,17.555944,8.139762e+01
32,INC_EFFICIENCY_APPLIANCE_STRATEGY_NZ,SCOE,4901.538826,4901.795571,2.567451e-01,65.526681,2.552207e+05
33,INC_EFFICIENCY_HEAT_NZ,SCOE,4901.538826,4938.080175,3.654135e+01,1.615971,4.422307e+01
34,SHIFT_FUEL_HEAT_STRATEGY_NZ,SCOE,4901.538826,5675.008997,7.734702e+02,84.721051,1.095337e+02
35,DEC_LIME_APPLIED_STRATEGY_NZ,SOIL,4901.538826,4901.538826,9.094947e-13,-0.000248,-2.726805e+11
36,DEC_N_APPLIED_STRATEGY_NZ,SOIL,4901.538826,4905.122352,3.583526e+00,-0.400836,-1.118551e+02
37,DEC_DEMAND_STRATEGY_NZ,TRDE,4901.538826,4981.490036,7.995121e+01,-34.248122,-4.283628e+02
38,INC_EFFICIENCY_ELECTRIC_STRATEGY_NZ,TRNS,4901.538826,4902.242101,7.032755e-01,-13.509292,-1.920910e+04
39,INC_EFFICIENCY_NON_ELECTRIC_STRATEGY_NZ,TRNS,4901.538826,5008.693220,1.071544e+02,5.822534,5.433780e+01
40,INC_OCCUPANCY_LIGHT_DUTY_STRATEGY_NZ,TRNS,4901.538826,4907.244056,5.705230e+00,-0.269474,-4.723284e+01
41,SHIFT_FUEL_LIGHT_DUTY_STRATEGY_NZ,TRNS,4901.538826,4925.633830,2.409500e+01,0.611603,2.538299e+01
42,SHIFT_FUEL_MARITIME_STRATEGY_NZ,TRNS,4901.538826,4919.430212,1.789139e+01,0.348321,1.946866e+01
43,SHIFT_FUEL_MEDIUM_DUTY_STRATEGY_NZ,TRNS,4901.538826,4940.184502,3.864568e+01,1.478109,3.824771e+01
44,SHIFT_FUEL_RAIL_STRATEGY_NZ,TRNS,4901.538826,4911.625496,1.008667e+01,-20.711657,-2.053369e+03
45,SHIFT_MODE_FREIGHT_STRATEGY_NZ,TRNS,4901.538826,4906.158458,4.619632e+00,4.035202,8.734900e+02
46,SHIFT_MODE_PASSENGER_STRATEGY_NZ,TRNS,4901.538826,4913.827984,1.228916e+01,-0.782827,-6.370062e+01
47,SHIFT_MODE_REGIONAL_STRATEGY_NZ,TRNS,4901.538826,4902.081480,5.426542e-01,-0.006364,-1.172746e+01
48,INC_CAPTURE_BIOGAS_STRATEGY_NZ,TRWW,4901.538826,5262.285105,3.607463e+02,140.602892,3.897556e+02
49,INC_COMPLIANCE_SEPTIC_STRATEGY_NZ,TRWW,4901.538826,4938.579218,3.704039e+01,0.539943,1.457713e+01
50,INC_TREATMENT_INDUSTRIAL_STRATEGY_NZ,WALI,4901.538826,4914.457655,1.291883e+01,53.233267,4.120595e+03
51,INC_TREATMENT_RURAL_STRATEGY_NZ,WALI,4901.538826,4998.663520,9.712469e+01,51.030248,5.254096e+02
52,INC_TREATMENT_URBAN_STRATEGY_NZ,WALI,4901.538826,5021.745479,1.202067e+02,412.226696,3.429317e+03
53,DEC_CONSUMER_FOOD_WASTE_STRATEGY_NZ,WASO,4901.538826,4951.479367,4.994054e+01,-46.288017,-9.268625e+02
54,INC_ANAEROBIC_AND_COMPOST_STRATEGY_NZ,WASO,4901.538826,4949.304018,4.776519e+01,-51.823605,-1.084966e+03
55,INC_CAPTURE_BIOGAS_STRATEGY_NZ,WASO,4901.538826,5086.195151,1.846563e+02,52.358239,2.835443e+02
56,INC_ENERGY_FROM_BIOGAS_STRATEGY_NZ,WASO,4901.538826,4899.448463,-2.090363e+00,21.072761,1.008091e+04
57,INC_ENERGY_FROM_INCINERATION_STRATEGY_NZ,WASO,4901.538826,4902.594597,1.055771e+00,0.015398,1.458482e+01
58,INC_LANDFILLING_STRATEGY_NZ,WASO,4901.538826,4903.590804,2.051978e+00,60.767847,2.961428e+04
59,INC_RECYCLING_STRATEGY_NZ,WASO,4901.538826,4923.610319,2.207149e+01,-8.509044,-3.855219e+02

In [162]:
df_merged_filtered.to_clipboard(index=False)

In [163]:
df_merged_filtered.to_csv(os.path.join(OUTPUT_DATA_DIR_PATH, "tornado_plot_for_QA_whirlpool.csv"), index=False)