In [8]:
# Load packages
from costs_benefits_ssp.cb_calculate import CostBenefits
import pandas as pd
import os
import pathlib
import numpy as np

In [9]:
# Define paths
SSP_PATH = pathlib.Path(os.getcwd()).parent.parent.as_posix()
SSP_RUN  = os.path.join(SSP_PATH, "tornado/ssp_run_output/sisepuede_run_2025-11-12t22;19;28.194097")


CB_DEFAULT_DEFINITION_PATH = os.path.join(SSP_PATH,"tornado/cb/cb_cost_factors")
CB_DEFAULT_DEFINITION_FILE_PATH = os.path.join(CB_DEFAULT_DEFINITION_PATH, "cb_config_params.xlsx")

CB_OUTPUT = os.path.join(SSP_PATH,"tornado/cb/cb_results")

In [10]:
# Load data
ssp_data = pd.read_csv(os.path.join(SSP_RUN, "uganda.csv"))
att_primary = pd.read_csv(os.path.join(SSP_RUN,"ATTRIBUTE_PRIMARY.csv"))
att_strategy = pd.read_csv(os.path.join(SSP_RUN,"ATTRIBUTE_STRATEGY.csv"))
strategy_code_base = "BASE"

In [11]:
att_primary

      primary_id  design_id  strategy_id  future_id
0              0          0            0          0
1          70070          0         6004          0
2          74074          0         6008          0
3          75075          0         6009          0
4         298299          3         6004          1
...          ...        ...          ...        ...
2062       62062          0         4003          0
2063       63063          0         4004          0
2064       64064          0         4005          0
2065       66066          0         6000          0
2066       67067          0         6001          0

[2067 rows x 4 columns]

In [12]:
# Instantiate CostBenefits object
cb = CostBenefits(ssp_data, att_primary, att_strategy, strategy_code_base)

# The export_db_to_excel method saves the initial configuration of the cost tables to an excel file.
# Each sheet represents a table in the cost and benefit program database.
# If the Excel file name is not given, the file will be saved with the default name cb_config_params.xlsx on the current python session.

#cb.export_db_to_excel(CB_DEFAULT_DEFINITION_FILE_PATH)

# Once that the excel file has been updated, we can reload it in order to update the cost factors database
cb.load_cb_parameters(CB_DEFAULT_DEFINITION_FILE_PATH)

The TX TX:FRST:INCREASE_SEQUESTRATION_NZ is missing on AttTransformationCode
The TX TX:LNDU:DEC_WETLAND_LOSS_NZ is missing on AttTransformationCode
The TX TX:LNDU:SET_WETLANDS_MINIMUM_NZ is missing on AttTransformationCode
The TX TX:SCOE:INC_EFFICIENCY_HEAT_NZ is missing on AttTransformationCode
The TX TX:FRST:INCREASE_SEQUESTRATION_NDC_2 is missing on AttTransformationCode
The TX TX:LNDU:DEC_WETLAND_LOSS_NDC_2 is missing on AttTransformationCode
The TX TX:LNDU:SET_WETLANDS_MINIMUM_NDC_2 is missing on AttTransformationCode
The TX TX:SCOE:INC_EFFICIENCY_HEAT_NDC_2 is missing on AttTransformationCode
The TX TX:FRST:INCREASE_SEQUESTRATION_NDC_25 is missing on AttTransformationCode
The TX TX:LNDU:DEC_WETLAND_LOSS_NDC_25 is missing on AttTransformationCode
The TX TX:LNDU:SET_WETLANDS_MINIMUM_NDC_25 is missing on AttTransformationCode
The TX TX:SCOE:INC_EFFICIENCY_HEAT_NDC_25 is missing on AttTransformationCode
Cargamos configuración de archivo excel
Se actualizó la base de datos

In [13]:
# Compute System Costs
results_system = cb.compute_system_cost_for_all_strategies()

************************************
*Strategy : PFLO:NDC_2_2020_TUNED (0/65)
************************************

---------Costs for: cb:wali:technical_cost:sanitation:unimp_rural.
La variable se evalúa en System Cost
---------Costs for: cb:wali:technical_cost:sanitation:imp_rural.
La variable se evalúa en System Cost
---------Costs for: cb:wali:technical_cost:sanitation:safeman_rural.
La variable se evalúa en System Cost
---------Costs for: cb:wali:technical_cost:sanitation:unimp_urban.
La variable se evalúa en System Cost
---------Costs for: cb:wali:technical_cost:sanitation:imp_urban.
La variable se evalúa en System Cost
---------Costs for: cb:wali:technical_cost:sanitation:safeman_urban.
La variable se evalúa en System Cost
---------Costs for: cb:wali:technical_cost:sanitation:omit_rural.
La variable se evalúa en System Cost
---------Costs for: cb:entc:technical_cost:electricity:capex.
La variable se evalúa en System Cost
---------Costs for: cb:entc:technical_cost:electricity:opex.
La variable se evalúa en System Cost
---------Costs for: cb:entc:technical_cost:electricity:transmission.
La variable se evalúa en System Cost
---------Costs for: change_in_emissions.
La variable se evalúa en System Cost
---------Costs for: cb:trns:air_pollution:X:diesel.
La variable se evalúa en System Cost
---------Costs for: cb:trns:air_pollution:X:gasoline.
La variable se evalúa en System Cost
---------Costs for: cb:trns:air_pollution:X:biofuels.
La variable se evalúa en System Cost
---------Costs for: cb:lndu:ecosystem_services:forests:primary.
La variable se evalúa en System Cost
---------Costs for: cb:lndu:ecosystem_services:forests:secondary.
La variable se evalúa en System Cost
---------Costs for: cb:trns:system_cost:freight_transport:aviation.
La variable se evalúa en System Cost
---------Costs for: cb:trns:system_cost:freight_transport:rail.
La variable se evalúa en System Cost
---------Costs for: cb:trns:system_cost:freight_transport:road_heavy.
La variable se evalúa en System Cost
---------Costs for: cb:trns:system_cost:freight_transport:water_borne.
La variable se evalúa en System Cost
---------Costs for: cb:waso:technical_cost:waste_management:biogas.
La variable se evalúa en System Cost
---------Costs for: cb:waso:technical_cost:waste_management:compost.
La variable se evalúa en System Cost
---------Costs for: cb:waso:technical_cost:waste_management:incinerated.
La variable se evalúa en System Cost
---------Costs for: cb:waso:technical_cost:waste_management:landfilled.
La variable se evalúa en System Cost
---------Costs for: cb:waso:technical_cost:waste_management:open_dump.
La variable se evalúa en System Cost
---------Costs for: cb:waso:technical_cost:waste_management:recycled.
La variable se evalúa en System Cost
---------Costs for: cb:trww:technical_cost:wastewater_treatment:tertiary_aerobic.
La variable se evalúa en System Cost
---------Costs for: cb:trww:technical_cost:wastewater_treatment:tertiary_anaerobic.
La variable se evalúa en System Cost
---------Costs for: cb:trww:technical_cost:wastewater_treatment:primary.
La variable se evalúa en System Cost
---------Costs for: cb:trww:technical_cost:wastewater_treatment:secondary_aerobic.
La variable se evalúa en System Cost
---------Costs for: cb:trww:technical_cost:wastewater_treatment:secondary_anaerobic.
La variable se evalúa en System Cost
---------Costs for: cb:trww:technical_cost:wastewater_treatment:untreated_with_sewerage.
La variable se evalúa en System Cost
---------Costs for: cb:wali:human_health:safe_sanitation:X.
La variable se evalúa en System Cost
---------Costs for: cb:lvst:lvst_value:livestock_produced:buffalo.
La variable se evalúa en System Cost
---------Costs for: cb:lvst:lvst_value:livestock_produced:cattle_dairy.
La variable se evalúa en System Cost
---------Costs for: cb:lvst:lvst_value:livestock_produced:cattle_nondairy.
La variable se evalúa en System Cost
---------Costs for: cb:lvst:lvst_value:livestock_produced:chickens.
La variable se evalúa en System Cost
---------Costs for: cb:lvst:lvst_value:livestock_produced:goats.
La variable se evalúa en System Cost
---------Costs for: cb:lvst:lvst_value:livestock_produced:horses.
La variable se evalúa en System Cost
---------Costs for: cb:lvst:lvst_value:livestock_produced:mules.
La variable se evalúa en System Cost
---------Costs for: cb:lvst:lvst_value:livestock_produced:pigs.
La variable se evalúa en System Cost
---------Costs for: cb:lvst:lvst_value:livestock_produced:sheep.
La variable se evalúa en System Cost
---------Costs for: cb:agrc:crop_value:crops_produced:bevs_and_spices.
La variable se evalúa en System Cost
---------Costs for: cb:agrc:crop_value:crops_produced:cereals.
La variable se evalúa en System Cost
---------Costs for: cb:agrc:crop_value:crops_produced:fibers.
La variable se evalúa en System Cost
---------Costs for: cb:agrc:crop_value:crops_produced:fruits.
La variable se evalúa en System Cost
---------Costs for: cb:agrc:crop_value:crops_produced:herbs.
La variable se evalúa en System Cost
---------Costs for: cb:agrc:crop_value:crops_produced:nuts.
La variable se evalúa en System Cost
---------Costs for: cb:agrc:crop_value:crops_produced:other_annual.
La variable se evalúa en System Cost
---------Costs for: cb:agrc:crop_value:crops_produced:other_woody_perennial.
La variable se evalúa en System Cost
---------Costs for: cb:agrc:crop_value:crops_produced:pulses.
La variable se evalúa en System Cost
---------Costs for: cb:agrc:crop_value:crops_produced:rice.
La variable se evalúa en System Cost
---------Costs for: cb:agrc:crop_value:crops_produced:sugar_cane.
La variable se evalúa en System Cost
---------Costs for: cb:agrc:crop_value:crops_produced:tubers.
La variable se evalúa en System Cost
---------Costs for: cb:agrc:crop_value:crops_produced:vegetables.
La variable se evalúa en System Cost
---------Costs for: cb:trww:technical_cost:waste_to_energy:X.
La variable se evalúa en System Cost
---------Costs for: cb:trww:fuel_cost:waste_to_energy_value:X.
La variable se evalúa en System Cost
---------Costs for: cb:ccsq:sector_specific:fuel_cost:X.
La variable se evalúa en System Cost
---------Costs for: cb:inen:sector_specific:fuel_cost:X.
La variable se evalúa en System Cost
---------Costs for: cb:scoe:sector_specific:fuel_cost:X.
La variable se evalúa en System Cost
---------Costs for: cb:entc:sector_specific:fuel_cost:X.
La variable se evalúa en System Cost
---------Costs for: cb:trns:sector_specific:fuel_cost:X.
La variable se evalúa en System Cost
---------Costs for: cb:ippu:air_pollution:X:cement.
La variable se evalúa en System Cost
---------Costs for: cb:trns:system_cost:passenger_transport:aviation.
La variable se evalúa en System Cost
---------Costs for: cb:trns:system_cost:passenger_transport:powered_bikes.
La variable se evalúa en System Cost
---------Costs for: cb:trns:system_cost:passenger_transport:public.
La variable se evalúa en System Cost
---------Costs for: cb:trns:system_cost:passenger_transport:rail_passenger.
La variable se evalúa en System Cost
---------Costs for: cb:trns:system_cost:passenger_transport:road_heavy_regional.
La variable se evalúa en System Cost
---------Costs for: cb:trns:system_cost:passenger_transport:road_light.
La variable se evalúa en System Cost
---------Costs for: cb:waso:env_pollution:open_dumping:X.
La variable se evalúa en System Cost
---------Costs for: cb:ippu:ippu_value:industrial_products:cement.
La variable se evalúa en System Cost
---------Costs for: cb:ippu:ippu_value:industrial_products:steel.
La variable se evalúa en System Cost
---------Costs for: cb:ccsq:sector_specific:electricity_cost:X.
La variable se evalúa en System Cost
---------Costs for: cb:inen:sector_specific:electricity_cost:X.
La variable se evalúa en System Cost
---------Costs for: cb:scoe:sector_specific:electricity_cost:X.
La variable se evalúa en System Cost
---------Costs for: cb:trns:sector_specific:electricity_cost:X.
La variable se evalúa en System Cost
---------Costs for: cb:waso:technical_cost:waste_to_energy:incineration.
La variable se evalúa en System Cost
---------Costs for: cb:waso:technical_cost:waste_to_energy:anaerobic.
La variable se evalúa en System Cost
---------Costs for: cb:waso:technical_cost:waste_to_energy:landfill.
La variable se evalúa en System Cost
---------Costs for: cb:waso:fuel_cost:waste_to_energy_value:anaerobic.
La variable se evalúa en System Cost
---------Costs for: cb:waso:fuel_cost:waste_to_energy_value:landfill.
La variable se evalúa en System Cost
---------Costs for: cb:entc:air_pollution:X:diesel.
La variable se evalúa en System Cost
---------Costs for: cb:entc:air_pollution:X:gasoline.
La variable se evalúa en System Cost
---------Costs for: cb:entc:air_pollution:X:biofuels.
La variable se evalúa en System Cost
---------Costs for: cb:trns:congestion:X:diesel.
La variable se evalúa en System Cost
---------Costs for: cb:trns:congestion:X:gasoline.
La variable se evalúa en System Cost
---------Costs for: cb:trns:congestion:X:biofuels.
La variable se evalúa en System Cost
---------Costs for: cb:trns:congestion:X:electricity.
La variable se evalúa en System Cost
---------Costs for: cb:waso:technical_cost:waste_collection:biogas.
La variable se evalúa en System Cost
---------Costs for: cb:waso:technical_cost:waste_collection:compost.
La variable se evalúa en System Cost
---------Costs for: cb:waso:technical_cost:waste_collection:incinerated.
La variable se evalúa en System Cost
---------Costs for: cb:waso:technical_cost:waste_collection:landfilled.
La variable se evalúa en System Cost
---------Costs for: cb:waso:technical_cost:waste_collection:open_dump.
La variable se evalúa en System Cost
---------Costs for: cb:waso:technical_cost:waste_collection:recycled.
La variable se evalúa en System Cost
---------Costs for: cb:soil:technical_cost:agriculture_inputs:fertilizer.
La variable se evalúa en System Cost
---------Costs for: cb:soil:land_pollution:N_leaching:fertilizer.
La variable se evalúa en System Cost
---------Costs for: cb:inen:air_pollution:X:diesel.
La variable se evalúa en System Cost
---------Costs for: cb:inen:air_pollution:X:gasoline.
La variable se evalúa en System Cost
---------Costs for: cb:inen:air_pollution:X:biomass.
La variable se evalúa en System Cost
---------Costs for: cb:inen:air_pollution:X:coal.
La variable se evalúa en System Cost
---------Costs for: cb:inen:air_pollution:X:coke.
La variable se evalúa en System Cost
---------Costs for: cb:inen:air_pollution:X:natural_gas.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:X:X.
La variable se evalúa en System Cost
---------Costs for: cb:trns:road_safety:X:diesel.
La variable se evalúa en System Cost
---------Costs for: cb:trns:road_safety:X:gasoline.
La variable se evalúa en System Cost
---------Costs for: cb:trns:road_safety:X:biofuels.
La variable se evalúa en System Cost
---------Costs for: cb:trns:road_safety:X:electricity.
La variable se evalúa en System Cost
---------Costs for: cb:trww:water_pollution:wastewater_treatment:P.
La variable se evalúa en System Cost
---------Costs for: cb:trww:water_pollution:wastewater_treatment:N.
La variable se evalúa en System Cost
---------Costs for: cb:trww:water_pollution:wastewater_treatment:COD.
La variable se evalúa en System Cost
---------Costs for: cb:trww:water_pollution:wastewater_treatment:BOD.
La variable se evalúa en System Cost
---------Costs for: cb:lsmm:fuel_cost:waste_to_energy_value:X.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:ccsq:electricity.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:ccsq:hydrogen.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:ccsq:natural_gas.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:entc:biofuels.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:entc:biogas.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:entc:biomass.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:entc:coal.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:entc:coke.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:entc:diesel.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:entc:electricity.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:entc:gasoline.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:entc:hydrocarbon_gas_liquids.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:entc:hydrogen.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:entc:kerosene.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:entc:natural_gas.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:entc:nuclear.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:entc:oil.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:entc:other.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:entc:waste.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:inen:biomass.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:inen:coal.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:inen:coke.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:inen:diesel.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:inen:electricity.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:inen:gasoline.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:inen:hydrocarbon_gas_liquids.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:inen:hydrogen.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:inen:kerosene.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:inen:natural_gas.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:inen:oil.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:scoe:biomass.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:scoe:coal.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:scoe:diesel.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:scoe:electricity.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:scoe:gasoline.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:scoe:hydrocarbon_gas_liquids.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:scoe:hydrogen.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:scoe:kerosene.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:scoe:natural_gas.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:trns:biofuels.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:trns:diesel.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:trns:electricity.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:trns:gasoline.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:trns:hydrocarbon_gas_liquids.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:trns:hydrogen.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:trns:kerosene.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:trns:natural_gas.
La variable se evalúa en System Cost

************************************
*Strategy : PFLO:NDC_2_2025_TUNED (1/65)
************************************

---------Costs for: cb:wali:technical_cost:sanitation:unimp_rural.
La variable se evalúa en System Cost
---------Costs for: cb:wali:technical_cost:sanitation:imp_rural.
La variable se evalúa en System Cost
---------Costs for: cb:wali:technical_cost:sanitation:safeman_rural.
La variable se evalúa en System Cost
---------Costs for: cb:wali:technical_cost:sanitation:unimp_urban.
La variable se evalúa en System Cost
---------Costs for: cb:wali:technical_cost:sanitation:imp_urban.
La variable se evalúa en System Cost
---------Costs for: cb:wali:technical_cost:sanitation:safeman_urban.
La variable se evalúa en System Cost
---------Costs for: cb:wali:technical_cost:sanitation:omit_rural.
La variable se evalúa en System Cost
---------Costs for: cb:entc:technical_cost:electricity:capex.
La variable se evalúa en System Cost
---------Costs for: cb:entc:technical_cost:electricity:opex.
La variable se evalúa en System Cost
---------Costs for: cb:entc:technical_cost:electricity:transmission.
La variable se evalúa en System Cost
---------Costs for: change_in_emissions.
La variable se evalúa en System Cost
---------Costs for: cb:trns:air_pollution:X:diesel.
La variable se evalúa en System Cost
---------Costs for: cb:trns:air_pollution:X:gasoline.
La variable se evalúa en System Cost
---------Costs for: cb:trns:air_pollution:X:biofuels.
La variable se evalúa en System Cost
---------Costs for: cb:lndu:ecosystem_services:forests:primary.
La variable se evalúa en System Cost
---------Costs for: cb:lndu:ecosystem_services:forests:secondary.
La variable se evalúa en System Cost
---------Costs for: cb:trns:system_cost:freight_transport:aviation.
La variable se evalúa en System Cost
---------Costs for: cb:trns:system_cost:freight_transport:rail.
La variable se evalúa en System Cost
---------Costs for: cb:trns:system_cost:freight_transport:road_heavy.
La variable se evalúa en System Cost
---------Costs for: cb:trns:system_cost:freight_transport:water_borne.
La variable se evalúa en System Cost
---------Costs for: cb:waso:technical_cost:waste_management:biogas.
La variable se evalúa en System Cost
---------Costs for: cb:waso:technical_cost:waste_management:compost.
La variable se evalúa en System Cost
---------Costs for: cb:waso:technical_cost:waste_management:incinerated.
La variable se evalúa en System Cost
---------Costs for: cb:waso:technical_cost:waste_management:landfilled.
La variable se evalúa en System Cost
---------Costs for: cb:waso:technical_cost:waste_management:open_dump.
La variable se evalúa en System Cost
---------Costs for: cb:waso:technical_cost:waste_management:recycled.
La variable se evalúa en System Cost
---------Costs for: cb:trww:technical_cost:wastewater_treatment:tertiary_aerobic.
La variable se evalúa en System Cost
---------Costs for: cb:trww:technical_cost:wastewater_treatment:tertiary_anaerobic.
La variable se evalúa en System Cost
---------Costs for: cb:trww:technical_cost:wastewater_treatment:primary.
La variable se evalúa en System Cost
---------Costs for: cb:trww:technical_cost:wastewater_treatment:secondary_aerobic.
La variable se evalúa en System Cost
---------Costs for: cb:trww:technical_cost:wastewater_treatment:secondary_anaerobic.
La variable se evalúa en System Cost
---------Costs for: cb:trww:technical_cost:wastewater_treatment:untreated_with_sewerage.
La variable se evalúa en System Cost
---------Costs for: cb:wali:human_health:safe_sanitation:X.
La variable se evalúa en System Cost
---------Costs for: cb:lvst:lvst_value:livestock_produced:buffalo.
La variable se evalúa en System Cost
---------Costs for: cb:lvst:lvst_value:livestock_produced:cattle_dairy.
La variable se evalúa en System Cost
---------Costs for: cb:lvst:lvst_value:livestock_produced:cattle_nondairy.
La variable se evalúa en System Cost
---------Costs for: cb:lvst:lvst_value:livestock_produced:chickens.
La variable se evalúa en System Cost
---------Costs for: cb:lvst:lvst_value:livestock_produced:goats.
La variable se evalúa en System Cost
---------Costs for: cb:lvst:lvst_value:livestock_produced:horses.
La variable se evalúa en System Cost

In [14]:
# Compute Technical Costs
results_tx = cb.compute_technical_cost_for_all_strategies()

************************************
*Strategy : PFLO:NDC_2_2020_TUNED (0/65)
************************************

---------Costs for: cb:inen:technical_cost:fuel_switch:lo_heat.
La variable se evalúa en Transformation Cost
---------Costs for: cb:inen:technical_savings:fuel_switch:lo_heat.
La variable se evalúa en Transformation Cost
---------Costs for: cb:inen:technical_cost:fuel_switch:hi_heat.
La variable se evalúa en Transformation Cost
---------Costs for: cb:inen:technical_savings:fuel_switch:hi_heat.
La variable se evalúa en Transformation Cost
---------Costs for: cb:inen:technical_cost:fuel_switch:all.
La variable se evalúa en Transformation Cost
---------Costs for: cb:inen:technical_savings:fuel_switch:all.
La variable se evalúa en Transformation Cost
---------Costs for: cb:inen:technical_cost:efficiency:X.
La variable se evalúa en Transformation Cost
---------Costs for: cb:trns:technical_cost:electrification:LDV.
La variable se evalúa en Transformation Cost
---------Costs for: cb:trns:technical_savings:electrification:LDV.
La variable se evalúa en Transformation Cost
---------Costs for: cb:trns:technical_cost:electrification:hdv_vehicles.
La variable se evalúa en Transformation Cost
---------Costs for: cb:trns:technical_savings:electrification:hdv_vehicles.
La variable se evalúa en Transformation Cost
---------Costs for: cb:trns:technical_cost:electrification:hdv_charger.
La variable se evalúa en Transformation Cost
---------Costs for: cb:trns:technical_cost:efficiency:non_electric.
La variable se evalúa en Transformation Cost
---------Costs for: cb:trns:technical_cost:efficiency:all.
La variable se evalúa en Transformation Cost
---------Costs for: cb:scoe:technical_cost:fuel_switch:heat_pumps.
La variable se evalúa en Transformation Cost
---------Costs for: cb:scoe:technical_savings:fuel_switch:heat_pumps.
La variable se evalúa en Transformation Cost
---------Costs for: cb:scoe:technical_cost:efficiency:building_shell.
La variable se evalúa en Transformation Cost
---------Costs for: cb:entc:technical_cost:loss_reduction:electricity.
La variable se evalúa en Transformation Cost
---------Costs for: cb:ippu:technical_savings:clinker:X.
La variable se evalúa en Transformation Cost
---------Costs for: cb:ippu:technical_cost:abating_gases:hfcs.
La variable se evalúa en Transformation Cost

/Users/fabianfuentes/anaconda3/envs/ssp_uganda_env/lib/python3.11/site-packages/costs_benefits_ssp/cb_calculate.py:1067: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_output['variable_value_baseline'] = 0
/Users/fabianfuentes/anaconda3/envs/ssp_uganda_env/lib/python3.11/site-packages/costs_benefits_ssp/cb_calculate.py:1070: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_output['variable_value_pathway'] = data_merged["difference_value"]

---------Costs for: cb:waso:technical_cost:consumer_food_waste:X.
La variable se evalúa en Transformation Cost
---------Costs for: cb:waso:consumer_savings:consumer_food_waste:X.
La variable se evalúa en Transformation Cost
---------Costs for: cb:lvst:technical_cost:ent_ferm_mgmt:X.
La variable se evalúa en Transformation Cost
---------Costs for: cb:agrc:technical_cost:increase_productivity:X.
La variable se evalúa en Transformation Cost
---------Costs for: cb:lvst:technical_cost:increase_productivity:X.
La variable se evalúa en Transformation Cost
---------Costs for: cb:lndu:technical_cost:silvopasture:X.
La variable se evalúa en Transformation Cost
---------Costs for: cb:lndu:technical_cost:all_secondary_forests:X.
La variable se evalúa en Transformation Cost
---------Costs for: cb:agrc:consumer_savings:cons_ag_land_value:X.
La variable se evalúa en Transformation Cost
---------Costs for: cb:agrc:technical_savings:cons_ag:X.
La variable se evalúa en Transformation Cost

************************************
*Strategy : PFLO:NDC_2_2025_TUNED (1/65)
************************************

---------Costs for: cb:inen:technical_cost:fuel_switch:lo_heat.
La variable se evalúa en Transformation Cost
---------Costs for: cb:inen:technical_savings:fuel_switch:lo_heat.
La variable se evalúa en Transformation Cost
---------Costs for: cb:inen:technical_cost:fuel_switch:hi_heat.
La variable se evalúa en Transformation Cost
---------Costs for: cb:inen:technical_savings:fuel_switch:hi_heat.
La variable se evalúa en Transformation Cost
---------Costs for: cb:inen:technical_cost:fuel_switch:all.
La variable se evalúa en Transformation Cost
---------Costs for: cb:inen:technical_savings:fuel_switch:all.
La variable se evalúa en Transformation Cost
---------Costs for: cb:inen:technical_cost:efficiency:X.
La variable se evalúa en Transformation Cost
---------Costs for: cb:trns:technical_cost:electrification:LDV.
La variable se evalúa en Transformation Cost
---------Costs for: cb:trns:technical_savings:electrification:LDV.
La variable se evalúa en Transformation Cost
---------Costs for: cb:trns:technical_cost:electrification:hdv_vehicles.
La variable se evalúa en Transformation Cost
---------Costs for: cb:trns:technical_savings:electrification:hdv_vehicles.
La variable se evalúa en Transformation Cost
---------Costs for: cb:trns:technical_cost:electrification:hdv_charger.
La variable se evalúa en Transformation Cost
---------Costs for: cb:trns:technical_cost:efficiency:non_electric.
La variable se evalúa en Transformation Cost
---------Costs for: cb:trns:technical_cost:efficiency:all.
La variable se evalúa en Transformation Cost
---------Costs for: cb:scoe:technical_cost:fuel_switch:heat_pumps.
La variable se evalúa en Transformation Cost
---------Costs for: cb:scoe:technical_savings:fuel_switch:heat_pumps.
La variable se evalúa en Transformation Cost
---------Costs for: cb:scoe:technical_cost:efficiency:building_shell.
La variable se evalúa en Transformation Cost
---------Costs for: cb:entc:technical_cost:loss_reduction:electricity.
La variable se evalúa en Transformation Cost
---------Costs for: cb:ippu:technical_savings:clinker:X.
La variable se evalúa en Transformation Cost
---------Costs for: cb:ippu:technical_cost:abating_gases:hfcs.
La variable se evalúa en Transformation Cost
---------Costs for: cb:waso:technical_cost:consumer_food_waste:X.
La variable se evalúa en Transformation Cost
---------Costs for: cb:waso:consumer_savings:consumer_food_waste:X.
La variable se evalúa en Transformation Cost

/Users/fabianfuentes/anaconda3/envs/ssp_uganda_env/lib/python3.11/site-packages/costs_benefits_ssp/cb_calculate.py:1067: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_output['variable_value_baseline'] = 0
/Users/fabianfuentes/anaconda3/envs/ssp_uganda_env/lib/python3.11/site-packages/costs_benefits_ssp/cb_calculate.py:1070: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_output['variable_value_pathway'] = data_merged["difference_value"]

---------Costs for: cb:lvst:technical_cost:ent_ferm_mgmt:X.
La variable se evalúa en Transformation Cost
---------Costs for: cb:agrc:technical_cost:increase_productivity:X.
La variable se evalúa en Transformation Cost
---------Costs for: cb:lvst:technical_cost:increase_productivity:X.
La variable se evalúa en Transformation Cost
---------Costs for: cb:lndu:technical_cost:silvopasture:X.
La variable se evalúa en Transformation Cost
---------Costs for: cb:lndu:technical_cost:all_secondary_forests:X.
La variable se evalúa en Transformation Cost
---------Costs for: cb:agrc:consumer_savings:cons_ag_land_value:X.
La variable se evalúa en Transformation Cost
---------Costs for: cb:agrc:technical_savings:cons_ag:X.
La variable se evalúa en Transformation Cost

************************************
*Strategy : AGRC:DEC_CH4_RICE (2/65)
************************************

---------Costs for: cb:agrc:technical_cost:rice_mgmt:X.
La variable se evalúa en Transformation Cost

************************************
*Strategy : AGRC:DEC_EXPORTS (3/65)
************************************

The Strategy AGRC:DEC_EXPORTS hasn't technical costs

************************************
*Strategy : AGRC:DEC_LOSSES_SUPPLY_CHAIN (4/65)
************************************

---------Costs for: cb:agrc:technical_cost:producer_food_waste:X.
La variable se evalúa en Transformation Cost
---------Costs for: cb:agrc:technical_savings:producer_food_waste:X.
La variable se evalúa en Transformation Cost

************************************
*Strategy : AGRC:INC_CONSERVATION_AGRICULTURE (5/65)
************************************

---------Costs for: cb:agrc:consumer_savings:cons_ag_land_value:X.
La variable se evalúa en Transformation Cost
---------Costs for: cb:agrc:technical_savings:cons_ag:X.
La variable se evalúa en Transformation Cost

************************************
*Strategy : AGRC:INC_PRODUCTIVITY (6/65)
************************************

---------Costs for: cb:agrc:technical_cost:increase_productivity:X.
La variable se evalúa en Transformation Cost

************************************
*Strategy : LNDU:DEC_DEFORESTATION (7/65)
************************************

The Strategy LNDU:DEC_DEFORESTATION hasn't technical costs

************************************
*Strategy : LNDU:DEC_SOC_LOSS_PASTURES (8/65)
************************************

The Strategy LNDU:DEC_SOC_LOSS_PASTURES hasn't technical costs

************************************
*Strategy : LNDU:INC_REFORESTATION (9/65)
************************************

---------Costs for: cb:lndu:technical_cost:all_secondary_forests:X.
La variable se evalúa en Transformation Cost

************************************
*Strategy : LNDU:INC_SILVOPASTURE (10/65)
************************************

---------Costs for: cb:lndu:technical_cost:silvopasture:X.
La variable se evalúa en Transformation Cost

************************************
*Strategy : LNDU:PLUR (11/65)
************************************

The Strategy LNDU:PLUR hasn't technical costs

************************************
*Strategy : LSMM:INC_CAPTURE_BIOGAS (12/65)
************************************

The Strategy LSMM:INC_CAPTURE_BIOGAS hasn't technical costs

************************************
*Strategy : LSMM:INC_MANAGEMENT_CATTLE_PIGS (13/65)
************************************

---------Costs for: cb:lsmm:technical_cost:manure_management.
La variable se evalúa en Transformation Cost

************************************
*Strategy : LSMM:INC_MANAGEMENT_OTHER (14/65)
************************************

The Strategy LSMM:INC_MANAGEMENT_OTHER hasn't technical costs

************************************
*Strategy : LSMM:INC_MANAGEMENT_POULTRY (15/65)
************************************

The Strategy LSMM:INC_MANAGEMENT_POULTRY hasn't technical costs

************************************
*Strategy : LVST:DEC_ENTERIC_FERMENTATION (16/65)
************************************

---------Costs for: cb:lvst:technical_cost:ent_ferm_mgmt:X.
La variable se evalúa en Transformation Cost

************************************
*Strategy : LVST:DEC_EXPORTS (17/65)
************************************

The Strategy LVST:DEC_EXPORTS hasn't technical costs

************************************
*Strategy : LVST:INC_PRODUCTIVITY (18/65)
************************************

---------Costs for: cb:lvst:technical_cost:increase_productivity:X.
La variable se evalúa en Transformation Cost

************************************
*Strategy : SOIL:DEC_LIME_APPLIED (19/65)
************************************

The Strategy SOIL:DEC_LIME_APPLIED hasn't technical costs

************************************
*Strategy : SOIL:DEC_N_APPLIED (20/65)
************************************

The Strategy SOIL:DEC_N_APPLIED hasn't technical costs

************************************
*Strategy : TRWW:INC_CAPTURE_BIOGAS (21/65)
************************************

The Strategy TRWW:INC_CAPTURE_BIOGAS hasn't technical costs

************************************
*Strategy : TRWW:INC_COMPLIANCE_SEPTIC (22/65)
************************************

The Strategy TRWW:INC_COMPLIANCE_SEPTIC hasn't technical costs

************************************
*Strategy : WALI:INC_TREATMENT_INDUSTRIAL (23/65)
************************************

The Strategy WALI:INC_TREATMENT_INDUSTRIAL hasn't technical costs

************************************
*Strategy : WALI:INC_TREATMENT_RURAL (24/65)
************************************

The Strategy WALI:INC_TREATMENT_RURAL hasn't technical costs

************************************
*Strategy : WALI:INC_TREATMENT_URBAN (25/65)
************************************

The Strategy WALI:INC_TREATMENT_URBAN hasn't technical costs

************************************
*Strategy : WASO:DEC_CONSUMER_FOOD_WASTE (26/65)
************************************

---------Costs for: cb:waso:technical_cost:consumer_food_waste:X.
La variable se evalúa en Transformation Cost
---------Costs for: cb:waso:consumer_savings:consumer_food_waste:X.
La variable se evalúa en Transformation Cost

************************************
*Strategy : WASO:INC_ANAEROBIC_AND_COMPOST (27/65)
************************************

The Strategy WASO:INC_ANAEROBIC_AND_COMPOST hasn't technical costs

************************************
*Strategy : WASO:INC_CAPTURE_BIOGAS (28/65)
************************************

The Strategy WASO:INC_CAPTURE_BIOGAS hasn't technical costs

************************************
*Strategy : WASO:INC_ENERGY_FROM_BIOGAS (29/65)
************************************

The Strategy WASO:INC_ENERGY_FROM_BIOGAS hasn't technical costs

************************************
*Strategy : WASO:INC_ENERGY_FROM_INCINERATION (30/65)
************************************

The Strategy WASO:INC_ENERGY_FROM_INCINERATION hasn't technical costs

************************************
*Strategy : WASO:INC_LANDFILLING (31/65)
************************************

The Strategy WASO:INC_LANDFILLING hasn't technical costs

************************************
*Strategy : WASO:INC_RECYCLING (32/65)
************************************

The Strategy WASO:INC_RECYCLING hasn't technical costs

************************************
*Strategy : CCSQ:INC_CAPTURE (33/65)
************************************

---------Costs for: cb:ccsq:technical_cost:direct_air_capture:X.
La variable se evalúa en Transformation Cost

************************************
*Strategy : ENTC:DEC_LOSSES (34/65)
************************************

---------Costs for: cb:entc:technical_cost:loss_reduction:electricity.
La variable se evalúa en Transformation Cost

************************************
*Strategy : ENTC:LEAST_COST_SOLUTION (35/65)
************************************

The Strategy ENTC:LEAST_COST_SOLUTION hasn't technical costs

************************************
*Strategy : ENTC:TARGET_CLEAN_HYDROGEN (36/65)
************************************

The Strategy ENTC:TARGET_CLEAN_HYDROGEN hasn't technical costs

************************************
*Strategy : ENTC:TARGET_RENEWABLE_ELEC (37/65)
************************************

The Strategy ENTC:TARGET_RENEWABLE_ELEC hasn't technical costs

************************************
*Strategy : FGTV:DEC_LEAKS (38/65)
************************************

---------Costs for: cb:fgtv:technical_cost:leaks:X.
La variable se evalúa en Transformation Cost

************************************
*Strategy : FGTV:INC_FLARE (39/65)
************************************

---------Costs for: cb:fgtv:technical_cost:flaring:X.
La variable se evalúa en Transformation Cost

************************************
*Strategy : INEN:INC_EFFICIENCY_ENERGY (40/65)
************************************

---------Costs for: cb:inen:technical_cost:efficiency:X.
La variable se evalúa en Transformation Cost

************************************
*Strategy : INEN:INC_EFFICIENCY_PRODUCTION (41/65)
************************************

The Strategy INEN:INC_EFFICIENCY_PRODUCTION hasn't technical costs

************************************
*Strategy : INEN:SHIFT_FUEL_HEAT (42/65)
************************************

---------Costs for: cb:inen:technical_cost:fuel_switch:lo_heat.
La variable se evalúa en Transformation Cost
---------Costs for: cb:inen:technical_savings:fuel_switch:lo_heat.
La variable se evalúa en Transformation Cost
---------Costs for: cb:inen:technical_cost:fuel_switch:hi_heat.
La variable se evalúa en Transformation Cost
---------Costs for: cb:inen:technical_savings:fuel_switch:hi_heat.
La variable se evalúa en Transformation Cost
---------Costs for: cb:inen:technical_cost:fuel_switch:all.
La variable se evalúa en Transformation Cost
---------Costs for: cb:inen:technical_savings:fuel_switch:all.
La variable se evalúa en Transformation Cost

************************************
*Strategy : SCOE:DEC_DEMAND_HEAT (43/65)
************************************

---------Costs for: cb:scoe:technical_cost:efficiency:building_shell.
La variable se evalúa en Transformation Cost

************************************
*Strategy : SCOE:INC_EFFICIENCY_APPLIANCE (44/65)
************************************

---------Costs for: cb:scoe:technical_cost:efficiency:appliance.
La variable se evalúa en Transformation Cost

************************************
*Strategy : SCOE:SHIFT_FUEL_HEAT (45/65)
************************************

---------Costs for: cb:scoe:technical_cost:fuel_switch:heat_pumps.
La variable se evalúa en Transformation Cost
---------Costs for: cb:scoe:technical_savings:fuel_switch:heat_pumps.
La variable se evalúa en Transformation Cost

************************************
*Strategy : TRDE:DEC_DEMAND (46/65)
************************************

The Strategy TRDE:DEC_DEMAND hasn't technical costs

************************************
*Strategy : TRNS:INC_EFFICIENCY_ELECTRIC (47/65)
************************************

---------Costs for: cb:trns:technical_cost:efficiency:electric.
La variable se evalúa en Transformation Cost

************************************
*Strategy : TRNS:INC_EFFICIENCY_NON_ELECTRIC (48/65)
************************************

---------Costs for: cb:trns:technical_cost:efficiency:non_electric.
La variable se evalúa en Transformation Cost
---------Costs for: cb:trns:technical_cost:efficiency:all.
La variable se evalúa en Transformation Cost

************************************
*Strategy : TRNS:INC_OCCUPANCY_LIGHT_DUTY (49/65)
************************************

The Strategy TRNS:INC_OCCUPANCY_LIGHT_DUTY hasn't technical costs

************************************
*Strategy : TRNS:SHIFT_FUEL_LIGHT_DUTY (50/65)
************************************

---------Costs for: cb:trns:technical_cost:electrification:LDV.
La variable se evalúa en Transformation Cost
---------Costs for: cb:trns:technical_savings:electrification:LDV.
La variable se evalúa en Transformation Cost

************************************
*Strategy : TRNS:SHIFT_FUEL_MARITIME (51/65)
************************************

---------Costs for: cb:trns:technical_cost:fuel_switch:maritime.
La variable se evalúa en Transformation Cost

************************************
*Strategy : TRNS:SHIFT_FUEL_MEDIUM_DUTY (52/65)
************************************

---------Costs for: cb:trns:technical_cost:electrification:hdv_vehicles.
La variable se evalúa en Transformation Cost
---------Costs for: cb:trns:technical_savings:electrification:hdv_vehicles.
La variable se evalúa en Transformation Cost
---------Costs for: cb:trns:technical_cost:electrification:hdv_charger.
La variable se evalúa en Transformation Cost

/Users/fabianfuentes/anaconda3/envs/ssp_uganda_env/lib/python3.11/site-packages/costs_benefits_ssp/cb_calculate.py:856: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp["difference_variable"] = cb_orm.diff_var
/Users/fabianfuentes/anaconda3/envs/ssp_uganda_env/lib/python3.11/site-packages/costs_benefits_ssp/cb_calculate.py:857: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp["difference_value"] = data_merged["difference"]
/Users/fabianfuentes/anaconda3/envs/ssp_uganda_env/lib/python3.11/site-packages/costs_benefits_ssp/cb_calculate.py:858: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp["variable"] = cb_orm.output_variable_name
/Users/fabianfuentes/anaconda3/envs/ssp_uganda_env/lib/python3.11/site-packages/costs_benefits_ssp/cb_calculate.py:859: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp["value"] = data_merged["values"]
/Users/fabianfuentes/anaconda3/envs/ssp_uganda_env/lib/python3.11/site-packages/costs_benefits_ssp/cb_calculate.py:863: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp['variable_value_baseline'] = 0

************************************
*Strategy : TRNS:SHIFT_FUEL_RAIL (53/65)
************************************

---------Costs for: cb:trns:technical_cost:electrification:rail.
La variable se evalúa en Transformation Cost
---------Costs for: cb:trns:technical_savings:electrification:rail.
La variable se evalúa en Transformation Cost

************************************
*Strategy : TRNS:SHIFT_MODE_FREIGHT (54/65)
************************************

The Strategy TRNS:SHIFT_MODE_FREIGHT hasn't technical costs

************************************
*Strategy : TRNS:SHIFT_MODE_PASSENGER (55/65)
************************************

The Strategy TRNS:SHIFT_MODE_PASSENGER hasn't technical costs

************************************
*Strategy : TRNS:SHIFT_MODE_REGIONAL (56/65)
************************************

The Strategy TRNS:SHIFT_MODE_REGIONAL hasn't technical costs

************************************
*Strategy : IPPU:DEC_CLINKER (57/65)
************************************

---------Costs for: cb:ippu:technical_savings:clinker:X.
La variable se evalúa en Transformation Cost

************************************
*Strategy : IPPU:DEC_DEMAND (58/65)
************************************

The Strategy IPPU:DEC_DEMAND hasn't technical costs

************************************
*Strategy : IPPU:DEC_HFCS (59/65)
************************************

---------Costs for: cb:ippu:technical_cost:abating_gases:hfcs.
La variable se evalúa en Transformation Cost

/Users/fabianfuentes/anaconda3/envs/ssp_uganda_env/lib/python3.11/site-packages/costs_benefits_ssp/cb_calculate.py:1067: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_output['variable_value_baseline'] = 0
/Users/fabianfuentes/anaconda3/envs/ssp_uganda_env/lib/python3.11/site-packages/costs_benefits_ssp/cb_calculate.py:1070: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_output['variable_value_pathway'] = data_merged["difference_value"]

************************************
*Strategy : IPPU:DEC_N2O (60/65)
************************************

---------Costs for: cb:ippu:technical_cost:abating_gases:n2o.
La variable se evalúa en Transformation Cost

************************************
*Strategy : IPPU:DEC_OTHER_FCS (61/65)
************************************

---------Costs for: cb:ippu:technical_cost:abating_gases:other_fgases.
La variable se evalúa en Transformation Cost

************************************
*Strategy : IPPU:DEC_PFCS (62/65)
************************************

---------Costs for: cb:ippu:technical_cost:abating_gases:pfcs.
La variable se evalúa en Transformation Cost

************************************
*Strategy : PFLO:INC_HEALTHIER_DIETS (63/65)
************************************

---------Costs for: cb:pflo:human_health:better_diets:X.
La variable se evalúa en Transformation Cost
---------Costs for: cb:pflo:consumer_savings:better_diets:X.
La variable se evalúa en Transformation Cost

************************************
*Strategy : PFLO:INC_IND_CCS (64/65)
************************************

---------Costs for: cb:ippu:technical_cost:industrial_ccs:X.
La variable se evalúa en Transformation Cost

In [15]:
# Combine results
results_all = pd.concat([results_system, results_tx], ignore_index = True)

#-------------POST PROCESS SIMULATION RESULTS---------------
# Post process interactions among strategies that affect the same variables
results_all_pp = cb.cb_process_interactions(results_all)

# SHIFT any stray costs incurred from 2015 to 2025 to 2025 and 2035
results_all_pp_shifted = cb.cb_shift_costs(results_all_pp)

Resolving Interactions in SCOE : TX:SCOE:SHIFT_FUEL_HEAT, TX:SCOE:SHIFT_FUEL_HEAT, TX:SCOE:DEC_DEMAND_HEAT
Resolving Interactions in INEN : TX:INEN:SHIFT_FUEL_HEAT, TX:INEN:SHIFT_FUEL_HEAT, TX:INEN:SHIFT_FUEL_HEAT, TX:INEN:SHIFT_FUEL_HEAT, TX:INEN:SHIFT_FUEL_HEAT, TX:INEN:SHIFT_FUEL_HEAT, TX:INEN:INC_EFFICIENCY_ENERGY
Resolving Interactions in SCOE : TX:SCOE:SHIFT_FUEL_HEAT, TX:SCOE:SHIFT_FUEL_HEAT, TX:SCOE:DEC_DEMAND_HEAT
Resolving Interactions in INEN : TX:INEN:SHIFT_FUEL_HEAT, TX:INEN:SHIFT_FUEL_HEAT, TX:INEN:SHIFT_FUEL_HEAT, TX:INEN:SHIFT_FUEL_HEAT, TX:INEN:SHIFT_FUEL_HEAT, TX:INEN:SHIFT_FUEL_HEAT, TX:INEN:INC_EFFICIENCY_ENERGY
Resolving Interactions in SCOE :
No interactions, skipping... AGRC:DEC_CH4_RICE
Resolving Interactions in INEN :
No interactions, skipping... AGRC:DEC_CH4_RICE
Resolving Interactions in SCOE :
No interactions, skipping... AGRC:DEC_EXPORTS
Resolving Interactions in INEN :
No interactions, skipping... AGRC:DEC_EXPORTS
Resolving Interactions in SCOE :
No interactions, skipping... AGRC:DEC_LOSSES_SUPPLY_CHAIN
Resolving Interactions in INEN :
No interactions, skipping... AGRC:DEC_LOSSES_SUPPLY_CHAIN
Resolving Interactions in SCOE :
No interactions, skipping... AGRC:INC_CONSERVATION_AGRICULTURE
Resolving Interactions in INEN :
No interactions, skipping... AGRC:INC_CONSERVATION_AGRICULTURE
Resolving Interactions in SCOE :
No interactions, skipping... AGRC:INC_PRODUCTIVITY
Resolving Interactions in INEN :
No interactions, skipping... AGRC:INC_PRODUCTIVITY
Resolving Interactions in SCOE :
No interactions, skipping... LNDU:DEC_DEFORESTATION
Resolving Interactions in INEN :
No interactions, skipping... LNDU:DEC_DEFORESTATION
Resolving Interactions in SCOE :
No interactions, skipping... LNDU:DEC_SOC_LOSS_PASTURES
Resolving Interactions in INEN :
No interactions, skipping... LNDU:DEC_SOC_LOSS_PASTURES
Resolving Interactions in SCOE :
No interactions, skipping... LNDU:INC_REFORESTATION
Resolving Interactions in INEN :
No interactions, skipping... LNDU:INC_REFORESTATION
Resolving Interactions in SCOE :
No interactions, skipping... LNDU:INC_SILVOPASTURE
Resolving Interactions in INEN :
No interactions, skipping... LNDU:INC_SILVOPASTURE
Resolving Interactions in SCOE :
No interactions, skipping... LNDU:PLUR
Resolving Interactions in INEN :
No interactions, skipping... LNDU:PLUR
Resolving Interactions in SCOE :
No interactions, skipping... LSMM:INC_CAPTURE_BIOGAS
Resolving Interactions in INEN :
No interactions, skipping... LSMM:INC_CAPTURE_BIOGAS
Resolving Interactions in SCOE :
No interactions, skipping... LSMM:INC_MANAGEMENT_CATTLE_PIGS
Resolving Interactions in INEN :
No interactions, skipping... LSMM:INC_MANAGEMENT_CATTLE_PIGS
Resolving Interactions in SCOE :
No interactions, skipping... LSMM:INC_MANAGEMENT_OTHER
Resolving Interactions in INEN :
No interactions, skipping... LSMM:INC_MANAGEMENT_OTHER
Resolving Interactions in SCOE :
No interactions, skipping... LSMM:INC_MANAGEMENT_POULTRY
Resolving Interactions in INEN :
No interactions, skipping... LSMM:INC_MANAGEMENT_POULTRY
Resolving Interactions in SCOE :
No interactions, skipping... LVST:DEC_ENTERIC_FERMENTATION
Resolving Interactions in INEN :
No interactions, skipping... LVST:DEC_ENTERIC_FERMENTATION
Resolving Interactions in SCOE :
No interactions, skipping... LVST:DEC_EXPORTS
Resolving Interactions in INEN :
No interactions, skipping... LVST:DEC_EXPORTS
Resolving Interactions in SCOE :
No interactions, skipping... LVST:INC_PRODUCTIVITY
Resolving Interactions in INEN :
No interactions, skipping... LVST:INC_PRODUCTIVITY
Resolving Interactions in SCOE :
No interactions, skipping... SOIL:DEC_LIME_APPLIED
Resolving Interactions in INEN :
No interactions, skipping... SOIL:DEC_LIME_APPLIED
Resolving Interactions in SCOE :
No interactions, skipping... SOIL:DEC_N_APPLIED
Resolving Interactions in INEN :
No interactions, skipping... SOIL:DEC_N_APPLIED
Resolving Interactions in SCOE :
No interactions, skipping... TRWW:INC_CAPTURE_BIOGAS
Resolving Interactions in INEN :
No interactions, skipping... TRWW:INC_CAPTURE_BIOGAS
Resolving Interactions in SCOE :
No interactions, skipping... TRWW:INC_COMPLIANCE_SEPTIC
Resolving Interactions in INEN :
No interactions, skipping... TRWW:INC_COMPLIANCE_SEPTIC
Resolving Interactions in SCOE :
No interactions, skipping... WALI:INC_TREATMENT_INDUSTRIAL
Resolving Interactions in INEN :
No interactions, skipping... WALI:INC_TREATMENT_INDUSTRIAL
Resolving Interactions in SCOE :
No interactions, skipping... WALI:INC_TREATMENT_RURAL
Resolving Interactions in INEN :
No interactions, skipping... WALI:INC_TREATMENT_RURAL
Resolving Interactions in SCOE :
No interactions, skipping... WALI:INC_TREATMENT_URBAN
Resolving Interactions in INEN :
No interactions, skipping... WALI:INC_TREATMENT_URBAN
Resolving Interactions in SCOE :
No interactions, skipping... WASO:DEC_CONSUMER_FOOD_WASTE
Resolving Interactions in INEN :
No interactions, skipping... WASO:DEC_CONSUMER_FOOD_WASTE
Resolving Interactions in SCOE :
No interactions, skipping... WASO:INC_ANAEROBIC_AND_COMPOST
Resolving Interactions in INEN :
No interactions, skipping... WASO:INC_ANAEROBIC_AND_COMPOST
Resolving Interactions in SCOE :
No interactions, skipping... WASO:INC_CAPTURE_BIOGAS
Resolving Interactions in INEN :
No interactions, skipping... WASO:INC_CAPTURE_BIOGAS
Resolving Interactions in SCOE :
No interactions, skipping... WASO:INC_ENERGY_FROM_BIOGAS
Resolving Interactions in INEN :
No interactions, skipping... WASO:INC_ENERGY_FROM_BIOGAS
Resolving Interactions in SCOE :
No interactions, skipping... WASO:INC_ENERGY_FROM_INCINERATION
Resolving Interactions in INEN :
No interactions, skipping... WASO:INC_ENERGY_FROM_INCINERATION
Resolving Interactions in SCOE :
No interactions, skipping... WASO:INC_LANDFILLING
Resolving Interactions in INEN :
No interactions, skipping... WASO:INC_LANDFILLING
Resolving Interactions in SCOE :
No interactions, skipping... WASO:INC_RECYCLING
Resolving Interactions in INEN :
No interactions, skipping... WASO:INC_RECYCLING
Resolving Interactions in SCOE :
No interactions, skipping... CCSQ:INC_CAPTURE
Resolving Interactions in INEN :
No interactions, skipping... CCSQ:INC_CAPTURE
Resolving Interactions in SCOE :
No interactions, skipping... ENTC:DEC_LOSSES
Resolving Interactions in INEN :
No interactions, skipping... ENTC:DEC_LOSSES
Resolving Interactions in SCOE :
No interactions, skipping... ENTC:LEAST_COST_SOLUTION
Resolving Interactions in INEN :
No interactions, skipping... ENTC:LEAST_COST_SOLUTION
Resolving Interactions in SCOE :
No interactions, skipping... ENTC:TARGET_CLEAN_HYDROGEN
Resolving Interactions in INEN :
No interactions, skipping... ENTC:TARGET_CLEAN_HYDROGEN
Resolving Interactions in SCOE :
No interactions, skipping... ENTC:TARGET_RENEWABLE_ELEC
Resolving Interactions in INEN :
No interactions, skipping... ENTC:TARGET_RENEWABLE_ELEC
Resolving Interactions in SCOE :
No interactions, skipping... FGTV:DEC_LEAKS
Resolving Interactions in INEN :
No interactions, skipping... FGTV:DEC_LEAKS
Resolving Interactions in SCOE :
No interactions, skipping... FGTV:INC_FLARE
Resolving Interactions in INEN :
No interactions, skipping... FGTV:INC_FLARE
Resolving Interactions in SCOE :
No interactions, skipping... INEN:INC_EFFICIENCY_ENERGY
Resolving Interactions in INEN : TX:INEN:INC_EFFICIENCY_ENERGY
Resolving Interactions in SCOE :
No interactions, skipping... INEN:INC_EFFICIENCY_PRODUCTION
Resolving Interactions in INEN :
No interactions, skipping... INEN:INC_EFFICIENCY_PRODUCTION
Resolving Interactions in SCOE :
No interactions, skipping... INEN:SHIFT_FUEL_HEAT
Resolving Interactions in INEN : TX:INEN:SHIFT_FUEL_HEAT, TX:INEN:SHIFT_FUEL_HEAT, TX:INEN:SHIFT_FUEL_HEAT, TX:INEN:SHIFT_FUEL_HEAT, TX:INEN:SHIFT_FUEL_HEAT, TX:INEN:SHIFT_FUEL_HEAT
Resolving Interactions in SCOE : TX:SCOE:DEC_DEMAND_HEAT
Resolving Interactions in INEN :
No interactions, skipping... SCOE:DEC_DEMAND_HEAT
Resolving Interactions in SCOE : TX:SCOE:INC_EFFICIENCY_APPLIANCE
Resolving Interactions in INEN :
No interactions, skipping... SCOE:INC_EFFICIENCY_APPLIANCE
Resolving Interactions in SCOE : TX:SCOE:SHIFT_FUEL_HEAT, TX:SCOE:SHIFT_FUEL_HEAT
Resolving Interactions in INEN :
No interactions, skipping... SCOE:SHIFT_FUEL_HEAT
Resolving Interactions in SCOE :
No interactions, skipping... TRDE:DEC_DEMAND
Resolving Interactions in INEN :
No interactions, skipping... TRDE:DEC_DEMAND
Resolving Interactions in SCOE :
No interactions, skipping... TRNS:INC_EFFICIENCY_ELECTRIC
Resolving Interactions in INEN :
No interactions, skipping... TRNS:INC_EFFICIENCY_ELECTRIC
Resolving Interactions in SCOE :
No interactions, skipping... TRNS:INC_EFFICIENCY_NON_ELECTRIC
Resolving Interactions in INEN :
No interactions, skipping... TRNS:INC_EFFICIENCY_NON_ELECTRIC
Resolving Interactions in SCOE :
No interactions, skipping... TRNS:INC_OCCUPANCY_LIGHT_DUTY
Resolving Interactions in INEN :
No interactions, skipping... TRNS:INC_OCCUPANCY_LIGHT_DUTY
Resolving Interactions in SCOE :
No interactions, skipping... TRNS:SHIFT_FUEL_LIGHT_DUTY
Resolving Interactions in INEN :
No interactions, skipping... TRNS:SHIFT_FUEL_LIGHT_DUTY
Resolving Interactions in SCOE :
No interactions, skipping... TRNS:SHIFT_FUEL_MARITIME
Resolving Interactions in INEN :
No interactions, skipping... TRNS:SHIFT_FUEL_MARITIME
Resolving Interactions in SCOE :
No interactions, skipping... TRNS:SHIFT_FUEL_MEDIUM_DUTY
Resolving Interactions in INEN :
No interactions, skipping... TRNS:SHIFT_FUEL_MEDIUM_DUTY
Resolving Interactions in SCOE :
No interactions, skipping... TRNS:SHIFT_FUEL_RAIL
Resolving Interactions in INEN :
No interactions, skipping... TRNS:SHIFT_FUEL_RAIL
Resolving Interactions in SCOE :
No interactions, skipping... TRNS:SHIFT_MODE_FREIGHT
Resolving Interactions in INEN :
No interactions, skipping... TRNS:SHIFT_MODE_FREIGHT
Resolving Interactions in SCOE :
No interactions, skipping... TRNS:SHIFT_MODE_PASSENGER
Resolving Interactions in INEN :
No interactions, skipping... TRNS:SHIFT_MODE_PASSENGER
Resolving Interactions in SCOE :
No interactions, skipping... TRNS:SHIFT_MODE_REGIONAL
Resolving Interactions in INEN :
No interactions, skipping... TRNS:SHIFT_MODE_REGIONAL
Resolving Interactions in SCOE :
No interactions, skipping... IPPU:DEC_CLINKER
Resolving Interactions in INEN :
No interactions, skipping... IPPU:DEC_CLINKER
Resolving Interactions in SCOE :
No interactions, skipping... IPPU:DEC_DEMAND
Resolving Interactions in INEN :
No interactions, skipping... IPPU:DEC_DEMAND
Resolving Interactions in SCOE :
No interactions, skipping... IPPU:DEC_HFCS
Resolving Interactions in INEN :
No interactions, skipping... IPPU:DEC_HFCS
Resolving Interactions in SCOE :
No interactions, skipping... IPPU:DEC_N2O
Resolving Interactions in INEN :
No interactions, skipping... IPPU:DEC_N2O
Resolving Interactions in SCOE :
No interactions, skipping... IPPU:DEC_OTHER_FCS
Resolving Interactions in INEN :
No interactions, skipping... IPPU:DEC_OTHER_FCS
Resolving Interactions in SCOE :
No interactions, skipping... IPPU:DEC_PFCS
Resolving Interactions in INEN :
No interactions, skipping... IPPU:DEC_PFCS
Resolving Interactions in SCOE :
No interactions, skipping... PFLO:INC_HEALTHIER_DIETS
Resolving Interactions in INEN :
No interactions, skipping... PFLO:INC_HEALTHIER_DIETS
Resolving Interactions in SCOE :
No interactions, skipping... PFLO:INC_IND_CCS
Resolving Interactions in INEN :
No interactions, skipping... PFLO:INC_IND_CCS

/Users/fabianfuentes/anaconda3/envs/ssp_uganda_env/lib/python3.11/site-packages/costs_benefits_ssp/cb_calculate.py:660: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  res_pre2025["variable"] = res_pre2025["variable"] + "_shifted" + (res_pre2025["time_period"]+SSP_GLOBAL_TIME_PERIOD_0).astype(str)#create a new variable so they can be recognized as shifted costs
/Users/fabianfuentes/anaconda3/envs/ssp_uganda_env/lib/python3.11/site-packages/costs_benefits_ssp/cb_calculate.py:661: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  res_pre2025["time_period"] = res_pre2025["time_period"]+SSP_GLOBAL_TIME_PERIOD_TX_START #shift the time period

In [16]:
results_all_pp_shifted.head()

,strategy_code,future_id,region,time_period,difference_variable,variable_value_baseline,variable_value_pathway,difference_value,variable,value
0,PFLO:NDC_2_2020_TUNED,0,uganda,4,pop_unimproved_rural,1.932346e+07,1.932346e+07,0.000000e+00,cb:wali:technical_cost:sanitation:unimp_rural,0.0
1,PFLO:NDC_2_2020_TUNED,0,uganda,5,pop_unimproved_rural,1.951974e+07,1.951974e+07,0.000000e+00,cb:wali:technical_cost:sanitation:unimp_rural,0.0
2,PFLO:NDC_2_2020_TUNED,0,uganda,6,pop_unimproved_rural,1.896047e+07,1.858126e+07,-3.792094e+05,cb:wali:technical_cost:sanitation:unimp_rural,0.0
3,PFLO:NDC_2_2020_TUNED,0,uganda,7,pop_unimproved_rural,1.837001e+07,1.763521e+07,-7.348005e+05,cb:wali:technical_cost:sanitation:unimp_rural,0.0
4,PFLO:NDC_2_2020_TUNED,0,uganda,8,pop_unimproved_rural,1.774752e+07,1.668267e+07,-1.064851e+06,cb:wali:technical_cost:sanitation:unimp_rural,0.0

In [17]:
ssp_data.head()

,primary_id,region,time_period,area_agrc_crops_bevs_and_spices,area_agrc_crops_cereals,area_agrc_crops_fibers,area_agrc_crops_fruits,area_agrc_crops_herbs_and_other_perennial_crops,area_agrc_crops_nuts,area_agrc_crops_other_annual,...,emission_co2e_subsector_total_inen,emission_co2e_subsector_total_ippu,emission_co2e_subsector_total_lndu,emission_co2e_subsector_total_lsmm,emission_co2e_subsector_total_lvst,emission_co2e_subsector_total_scoe,emission_co2e_subsector_total_soil,emission_co2e_subsector_total_trns,emission_co2e_subsector_total_trww,emission_co2e_subsector_total_waso
0,0,uganda,4,634960.593061,2.025945e+06,156073.139455,1.131815e+06,505.429083,513832.892470,2.915383e+06,...,4.042769,0.369457,12.786390,2.851485,24.455996,5.111759,5.466143,3.120065,5.679647,7.834200
1,0,uganda,5,640126.452982,2.042427e+06,157342.906406,1.141024e+06,509.541112,518013.291655,2.939102e+06,...,4.144474,0.431364,14.592304,2.926134,24.430748,5.280986,5.901251,3.206151,5.860085,7.720287
2,0,uganda,6,642767.262368,2.050853e+06,157992.016628,1.145731e+06,511.643198,520150.329354,2.951227e+06,...,3.876473,0.487391,14.491826,2.885015,24.261499,5.471392,6.320646,3.287342,6.163252,7.649363
3,0,uganda,7,645322.479649,2.059006e+06,158620.088334,1.150285e+06,513.677153,522218.102852,2.962959e+06,...,3.796968,0.497802,14.390979,2.895205,24.286362,5.674534,6.677825,3.433169,6.497566,7.616672
4,0,uganda,8,647798.760608,2.066907e+06,159228.757514,1.154699e+06,515.648274,524221.998246,2.974329e+06,...,3.683509,0.505170,14.286685,2.907203,24.316574,5.906849,6.960800,3.613724,6.869311,7.618560

# Indoor air pollution benef

Health co-benefit from reduced household air pollution

To monetize the health benefits of reducing indoor air pollution from the use of traditional biomass stoves, we drew on estimates from the BAR-HAP model (The Benefits of Action to Reduce Household Air Pollution; WHO, 2021).
The study reports cost-effectiveness ratios ranging from 674 – 869 USD per DALY avoided for clean cooking interventions in Nepal, meaning that each avoided disability-adjusted life year (DALY) costs approximately 700 USD.

To adapt this metric to Uganda, we scaled the cost-effectiveness ratio by the relative difference in GDP per capita between Nepal (~1,450 USD) and Uganda (~1,070 USD), yielding an adjusted range of ≈ 500–640 USD per DALY avoided.
Assuming that the transition from solid fuels to clean cooking solutions avoids about 0.1 DALY per person per year, the implied annual health benefit equals 50–64 USD per person.

Given an average household size of five, this corresponds to an estimated 250–320 USD per household per year in health-related economic benefits.

This adjusted value was used in the cost–benefit analysis as the annual household health co-benefit of eliminating exposure to indoor air pollution from firewood and other solid fuels in Uganda.

In [18]:
import pandas as pd
import numpy as np

# parameters
benefit_per_person = 320   # USD/person/year. 
years = np.arange(4, 56)

# ['primary_id', 'time_period', 'population_gnrl_total']

# baseline
baseline = ssp_data[ssp_data['primary_id'] == 0][['time_period', 'population_gnrl_total', 'frac_scoe_heat_energy_residential_solid_biomass']]
baseline = baseline.rename(columns={'population_gnrl_total': 'population_baseline'})
baseline = baseline.rename(columns={'frac_scoe_heat_energy_residential_solid_biomass': 'frac_scoe_heat_energy_residential_solid_biomass_baseline'})

baseline.head()

,time_period,population_baseline,frac_scoe_heat_energy_residential_solid_biomass_baseline
0,4,39853824,0.960324
1,5,40996690,0.932779
2,6,42172327,0.901015
3,7,43381679,0.901015
4,8,44625710,0.901015

In [19]:
# baseline merge
merged = ssp_data[ssp_data['primary_id'] != 0][['primary_id', 'time_period', 'population_gnrl_total', 
                                                'frac_scoe_heat_energy_residential_solid_biomass']].merge(baseline, 
                                                                                                          on='time_period', how='left')
merged.tail(50)

,primary_id,time_period,population_gnrl_total,frac_scoe_heat_energy_residential_solid_biomass,population_baseline,frac_scoe_heat_energy_residential_solid_biomass_baseline
3330,75075,6,42172327,0.901015,42172327,0.901015
3331,75075,7,43381679,0.901015,43381679,0.901015
3332,75075,8,44625710,0.901015,44625710,0.901015
3333,75075,9,45905416,0.901015,45905416,0.901015
3334,75075,10,47221819,0.901015,47221819,0.901015
3335,75075,11,48562777,0.901015,48562777,0.901015
3336,75075,12,49928247,0.881160,49928247,0.892538
3337,75075,13,51318160,0.850218,51318160,0.879923
3338,75075,14,52732427,0.803123,52732427,0.861368
3339,75075,15,54170936,0.734175,54170936,0.834544
3340,75075,16,55633552,0.639178,55633552,0.796717
3341,75075,17,57118968,0.519451,57118968,0.745199
3342,75075,18,58626908,0.385762,58626908,0.678266
3343,75075,19,60157070,0.257217,60157070,0.596441
3344,75075,20,61709123,0.152539,61709123,0.503533
3345,75075,21,63282705,0.080378,63282705,0.406492
3346,75075,22,64877430,0.037714,64877430,0.313584
3347,75075,23,66492878,0.015671,66492878,0.231759
3348,75075,24,68128603,0.005564,68128603,0.164826
3349,75075,25,69784128,0.001444,69784128,0.113308
3350,75075,26,71458947,0.000000,71458947,0.075481
3351,75075,27,73013306,0.000000,73013306,0.048657
3352,75075,28,74582504,0.000000,74582504,0.030102
3353,75075,29,76162092,0.000000,76162092,0.017487
3354,75075,30,77745983,0.000000,77745983,0.009010
3355,75075,31,79337720,0.000000,79337720,0.009010
3356,75075,32,80943325,0.000000,80943325,0.009010
3357,75075,33,82560132,0.000000,82560132,0.009010
3358,75075,34,84179703,0.000000,84179703,0.009010
3359,75075,35,85801427,0.000000,85801427,0.009010
3360,75075,36,87428891,0.000000,87428891,0.009010
3361,75075,37,89064421,0.000000,89064421,0.009010
3362,75075,38,90709186,0.000000,90709186,0.009010
3363,75075,39,92356737,0.000000,92356737,0.009010
3364,75075,40,94002404,0.000000,94002404,0.009010
3365,75075,41,95647230,0.000000,95647230,0.009010
3366,75075,42,97294463,0.000000,97294463,0.009010
3367,75075,43,98943854,0.000000,98943854,0.009010
3368,75075,44,100590482,0.000000,100590482,0.009010
3369,75075,45,102228430,0.000000,102228430,0.009010
3370,75075,46,103867064,0.000000,103867064,0.009010
3371,75075,47,105508460,0.000000,105508460,0.009010
3372,75075,48,107140913,0.000000,107140913,0.009010
3373,75075,49,108767599,0.000000,108767599,0.009010
3374,75075,50,110385692,0.000000,110385692,0.009010
3375,75075,51,111995359,0.000000,111995359,0.009010
3376,75075,52,113599053,0.000000,113599053,0.009010
3377,75075,53,115193414,0.000000,115193414,0.009010
3378,75075,54,116777146,0.000000,116777146,0.009010
3379,75075,55,118356823,0.000000,118356823,0.009010

In [20]:
# frac_scoe_heat_energy_residential_solid_biomass 
merged['pop_diff'] = (merged['frac_scoe_heat_energy_residential_solid_biomass_baseline'] - merged['frac_scoe_heat_energy_residential_solid_biomass'] ) * merged['population_gnrl_total']

In [21]:
# difference calculation
merged['value'] =  merged['pop_diff'] * benefit_per_person

In [23]:
merged.head()

,primary_id,time_period,population_gnrl_total,frac_scoe_heat_energy_residential_solid_biomass,population_baseline,frac_scoe_heat_energy_residential_solid_biomass_baseline,pop_diff,value
0,1001,4,39853824,0.960324,39853824,0.960324,0.0,0.0
1,1001,5,40996690,0.932779,40996690,0.932779,0.0,0.0
2,1001,6,42172327,0.901015,42172327,0.901015,0.0,0.0
3,1001,7,43381679,0.901015,43381679,0.901015,0.0,0.0
4,1001,8,44625710,0.901015,44625710,0.901015,0.0,0.0

In [24]:
merged = merged.merge(att_primary[['primary_id', 'strategy_id', 'future_id']], on='primary_id', how='left')
merged = merged.merge(att_strategy[['strategy_id', 'strategy_code']], on='strategy_id', how='left')

In [25]:
merged.to_csv(os.path.join(CB_OUTPUT, "cba_indoor_air_pollution.csv"), index = False)

In [26]:
merged['region']='uganda'
merged['difference_variable'] ='frac_scoe_heat_energy_residential_solid_biomass'
merged['difference_value'] = 'pop_diff'
merged['variable'] ='cb:scoe:indoor_air_pollution'

In [27]:
merged = merged[['strategy_code', 'future_id', 'region', 'time_period', 'difference_variable', 'value','variable']]
merged.head()

,strategy_code,future_id,region,time_period,difference_variable,value,variable
0,AGRC:DEC_CH4_RICE,0,uganda,4,frac_scoe_heat_energy_residential_solid_biomass,0.0,cb:scoe:indoor_air_pollution
1,AGRC:DEC_CH4_RICE,0,uganda,5,frac_scoe_heat_energy_residential_solid_biomass,0.0,cb:scoe:indoor_air_pollution
2,AGRC:DEC_CH4_RICE,0,uganda,6,frac_scoe_heat_energy_residential_solid_biomass,0.0,cb:scoe:indoor_air_pollution
3,AGRC:DEC_CH4_RICE,0,uganda,7,frac_scoe_heat_energy_residential_solid_biomass,0.0,cb:scoe:indoor_air_pollution
4,AGRC:DEC_CH4_RICE,0,uganda,8,frac_scoe_heat_energy_residential_solid_biomass,0.0,cb:scoe:indoor_air_pollution

In [28]:
merged.to_csv(os.path.join(CB_OUTPUT, "cba_indoor_air_pollution.csv"), index = False)

In [29]:
results_all_pp_shifted= pd.concat([results_all_pp_shifted, merged], ignore_index = True)

In [30]:
results_all_pp_shifted.head()

,strategy_code,future_id,region,time_period,difference_variable,variable_value_baseline,variable_value_pathway,difference_value,variable,value
0,PFLO:NDC_2_2020_TUNED,0,uganda,4,pop_unimproved_rural,1.932346e+07,1.932346e+07,0.000000e+00,cb:wali:technical_cost:sanitation:unimp_rural,0.0
1,PFLO:NDC_2_2020_TUNED,0,uganda,5,pop_unimproved_rural,1.951974e+07,1.951974e+07,0.000000e+00,cb:wali:technical_cost:sanitation:unimp_rural,0.0
2,PFLO:NDC_2_2020_TUNED,0,uganda,6,pop_unimproved_rural,1.896047e+07,1.858126e+07,-3.792094e+05,cb:wali:technical_cost:sanitation:unimp_rural,0.0
3,PFLO:NDC_2_2020_TUNED,0,uganda,7,pop_unimproved_rural,1.837001e+07,1.763521e+07,-7.348005e+05,cb:wali:technical_cost:sanitation:unimp_rural,0.0
4,PFLO:NDC_2_2020_TUNED,0,uganda,8,pop_unimproved_rural,1.774752e+07,1.668267e+07,-1.064851e+06,cb:wali:technical_cost:sanitation:unimp_rural,0.0

In [31]:
results_all_pp_shifted.tail()

,strategy_code,future_id,region,time_period,difference_variable,variable_value_baseline,variable_value_pathway,difference_value,variable,value
641291,PFLO:NDC_2_2025_TUNED,0,uganda,51,frac_scoe_heat_energy_residential_solid_biomass,NaN,NaN,NaN,cb:scoe:indoor_air_pollution,3.229103e+08
641292,PFLO:NDC_2_2025_TUNED,0,uganda,52,frac_scoe_heat_energy_residential_solid_biomass,NaN,NaN,NaN,cb:scoe:indoor_air_pollution,3.275342e+08
641293,PFLO:NDC_2_2025_TUNED,0,uganda,53,frac_scoe_heat_energy_residential_solid_biomass,NaN,NaN,NaN,cb:scoe:indoor_air_pollution,3.321311e+08
641294,PFLO:NDC_2_2025_TUNED,0,uganda,54,frac_scoe_heat_energy_residential_solid_biomass,NaN,NaN,NaN,cb:scoe:indoor_air_pollution,3.366974e+08
641295,PFLO:NDC_2_2025_TUNED,0,uganda,55,frac_scoe_heat_energy_residential_solid_biomass,NaN,NaN,NaN,cb:scoe:indoor_air_pollution,3.412520e+08

In [33]:
# Save the results
results_all_pp_shifted.to_csv(os.path.join(CB_OUTPUT, "cba_results.csv"), index = False)