In [11]:
import pandas as pd
import os

In [12]:
# Set up paths
SCRIPT_DIR_PATH = os.getcwd()
PARENT_DIR_PATH = os.path.dirname(SCRIPT_DIR_PATH)
DATA_DIR_PATH = os.path.join(PARENT_DIR_PATH, "data")
SSP_DIR_PATH = os.path.join(DATA_DIR_PATH, "ssp")
run_id = "sisepuede_run_2025-11-12t22;19;28.194097"
RUN_DIR_PATH = os.path.join(SSP_DIR_PATH, run_id)

In [13]:
# cb_df = pd.read_csv(os.path.join(RUN_DIR_PATH, f"cba_la_{run_id}_tornado.csv"))
cb_df = pd.read_csv(os.path.join(RUN_DIR_PATH, f"combined_cb_results_{run_id}.csv"))
cb_df.head()

,strategy_code,future_id,region,time_period,difference_variable,variable_value_baseline,variable_value_pathway,difference_value,variable,value,primary_id
0,PFLO:NZ,613,uganda,4,mass_distance_traveled_trns_mt_km_water_borne,0.0,0.0,3465.860721,cb:trns:technical_cost:fuel_switch:maritime,0.0,374987
1,PFLO:NZ,613,uganda,5,mass_distance_traveled_trns_mt_km_water_borne,0.0,0.0,3568.072052,cb:trns:technical_cost:fuel_switch:maritime,0.0,374987
2,PFLO:NZ,613,uganda,6,mass_distance_traveled_trns_mt_km_water_borne,0.0,0.0,3694.312012,cb:trns:technical_cost:fuel_switch:maritime,0.0,374987
3,PFLO:NZ,613,uganda,7,mass_distance_traveled_trns_mt_km_water_borne,0.0,0.0,3863.588322,cb:trns:technical_cost:fuel_switch:maritime,0.0,374987
4,PFLO:NZ,613,uganda,8,mass_distance_traveled_trns_mt_km_water_borne,0.0,0.0,4069.944108,cb:trns:technical_cost:fuel_switch:maritime,0.0,374987

In [14]:
#print shape
cb_df.shape

(4437886, 11)

In [15]:
cb_df.primary_id.nunique()

1997

In [16]:
# evaluate each column null values
null_counts = cb_df.isnull().sum()
print("Null values in each column:")
print(null_counts)

Null values in each column:
strategy_code                   0
future_id                       0
region                          0
time_period                     0
difference_variable             0
variable_value_baseline         0
variable_value_pathway     897666
difference_value                0
variable                        0
value                           0
primary_id                      0
dtype: int64

In [17]:
null_baseline = cb_df[cb_df['variable_value_pathway'].isnull()]
null_baseline

,strategy_code,future_id,region,time_period,difference_variable,variable_value_baseline,variable_value_pathway,difference_value,variable,value,primary_id
208,PFLO:NZ,613,uganda,4,emission_co2e_hfcs_ippu_product_use_product_us...,0.0,NaN,0.0,cb:ippu:technical_cost:abating_gases:hfcs,0.0,374987
209,PFLO:NZ,613,uganda,5,emission_co2e_hfcs_ippu_product_use_product_us...,0.0,NaN,0.0,cb:ippu:technical_cost:abating_gases:hfcs,0.0,374987
210,PFLO:NZ,613,uganda,6,emission_co2e_hfcs_ippu_product_use_product_us...,0.0,NaN,0.0,cb:ippu:technical_cost:abating_gases:hfcs,0.0,374987
211,PFLO:NZ,613,uganda,7,emission_co2e_hfcs_ippu_product_use_product_us...,0.0,NaN,0.0,cb:ippu:technical_cost:abating_gases:hfcs,0.0,374987
212,PFLO:NZ,613,uganda,8,emission_co2e_hfcs_ippu_product_use_product_us...,0.0,NaN,0.0,cb:ippu:technical_cost:abating_gases:hfcs,0.0,374987
...,...,...,...,...,...,...,...,...,...,...,...
4437761,PFLO:NZ,372,uganda,15,emission_co2e_other_fcs_ippu_production_electr...,0.0,NaN,0.0,cb:ippu:technical_cost:abating_gases:other_fga...,0.0,374746
4437762,PFLO:NZ,372,uganda,16,emission_co2e_other_fcs_ippu_production_electr...,0.0,NaN,0.0,cb:ippu:technical_cost:abating_gases:other_fga...,0.0,374746
4437763,PFLO:NZ,372,uganda,17,emission_co2e_other_fcs_ippu_production_electr...,0.0,NaN,0.0,cb:ippu:technical_cost:abating_gases:other_fga...,0.0,374746
4437764,PFLO:NZ,372,uganda,18,emission_co2e_other_fcs_ippu_production_electr...,0.0,NaN,0.0,cb:ippu:technical_cost:abating_gases:other_fga...,0.0,374746
4437765,PFLO:NZ,372,uganda,19,emission_co2e_other_fcs_ippu_production_electr...,0.0,NaN,0.0,cb:ippu:technical_cost:abating_gases:other_fga...,0.0,374746

In [18]:
null_baseline.variable.unique()  # Check unique future_ids with null baseline values

array(['cb:ippu:technical_cost:abating_gases:hfcs',
       'cb:ippu:technical_cost:abating_gases:other_fgases',
       'cb:ippu:technical_cost:abating_gases:hfcs_shifted2019',
       'cb:ippu:technical_cost:abating_gases:hfcs_shifted2020',
       'cb:ippu:technical_cost:abating_gases:hfcs_shifted2021',
       'cb:ippu:technical_cost:abating_gases:hfcs_shifted2022',
       'cb:ippu:technical_cost:abating_gases:hfcs_shifted2023',
       'cb:ippu:technical_cost:abating_gases:hfcs_shifted2024',
       'cb:ippu:technical_cost:abating_gases:other_fgases_shifted2019',
       'cb:ippu:technical_cost:abating_gases:other_fgases_shifted2020',
       'cb:ippu:technical_cost:abating_gases:other_fgases_shifted2021',
       'cb:ippu:technical_cost:abating_gases:other_fgases_shifted2022',
       'cb:ippu:technical_cost:abating_gases:other_fgases_shifted2023',
       'cb:ippu:technical_cost:abating_gases:other_fgases_shifted2024'],
      dtype=object)

In [19]:
# Check for -inf values in numeric columns
negative_inf_counts = (cb_df == -float('inf')).sum()
print("Negative infinity counts in each column:")
print(negative_inf_counts)

Negative infinity counts in each column:
strategy_code              0
future_id                  0
region                     0
time_period                0
difference_variable        0
variable_value_baseline    0
variable_value_pathway     0
difference_value           0
variable                   0
value                      0
primary_id                 0
dtype: int64

In [20]:
# check the rows with -inf values in 'value' column
negative_inf_rows = cb_df[cb_df['value'] == -float('inf')]
print("Rows with -inf in 'value' column:")
negative_inf_rows

Rows with -inf in 'value' column:

Empty DataFrame
Columns: [strategy_code, future_id, region, time_period, difference_variable, variable_value_baseline, variable_value_pathway, difference_value, variable, value, primary_id]
Index: []

In [21]:
# # replace -inf with 0 in 'value' column
# cb_df['value'] = cb_df['value'].replace(-float('inf'), 0)
# cb_df['difference_value'] = cb_df['difference_value'].replace(-float('inf'), 0)

In [22]:
# Check for -inf values in numeric columns
negative_inf_counts = (cb_df == -float('inf')).sum()
print("Negative infinity counts in each column:")
print(negative_inf_counts)

Negative infinity counts in each column:
strategy_code              0
future_id                  0
region                     0
time_period                0
difference_variable        0
variable_value_baseline    0
variable_value_pathway     0
difference_value           0
variable                   0
value                      0
primary_id                 0
dtype: int64

In [23]:
# replace all nans with 0
cb_df.fillna(0, inplace=True)
# Check if there are still any null values
null_counts_after_fill = cb_df.isnull().sum()
print("Null values after fillna:")
print(null_counts_after_fill)

Null values after fillna:
strategy_code              0
future_id                  0
region                     0
time_period                0
difference_variable        0
variable_value_baseline    0
variable_value_pathway     0
difference_value           0
variable                   0
value                      0
primary_id                 0
dtype: int64

In [24]:
cb_df.primary_id.nunique()

1997

In [25]:
# Save updated DataFrame
cb_df.to_csv(os.path.join(RUN_DIR_PATH, f"combined_cb_results_{run_id}_cleaned.csv"), index=False)
print(f"Updated DataFrame saved to combined_cb_results_updated_{run_id}.csv")

Updated DataFrame saved to combined_cb_results_updated_sisepuede_run_2025-11-12t22;19;28.194097.csv

### Quick Validation

In [26]:
saved_df = pd.read_csv(os.path.join(RUN_DIR_PATH, f"combined_cb_results_{run_id}_cleaned.csv"))
saved_df.head()

,strategy_code,future_id,region,time_period,difference_variable,variable_value_baseline,variable_value_pathway,difference_value,variable,value,primary_id
0,PFLO:NZ,613,uganda,4,mass_distance_traveled_trns_mt_km_water_borne,0.0,0.0,3465.860721,cb:trns:technical_cost:fuel_switch:maritime,0.0,374987
1,PFLO:NZ,613,uganda,5,mass_distance_traveled_trns_mt_km_water_borne,0.0,0.0,3568.072052,cb:trns:technical_cost:fuel_switch:maritime,0.0,374987
2,PFLO:NZ,613,uganda,6,mass_distance_traveled_trns_mt_km_water_borne,0.0,0.0,3694.312012,cb:trns:technical_cost:fuel_switch:maritime,0.0,374987
3,PFLO:NZ,613,uganda,7,mass_distance_traveled_trns_mt_km_water_borne,0.0,0.0,3863.588322,cb:trns:technical_cost:fuel_switch:maritime,0.0,374987
4,PFLO:NZ,613,uganda,8,mass_distance_traveled_trns_mt_km_water_borne,0.0,0.0,4069.944108,cb:trns:technical_cost:fuel_switch:maritime,0.0,374987

In [27]:
print(cb_df.shape)
print(saved_df.shape)

(4437886, 11)
(4437886, 11)

In [28]:
saved_df.future_id.nunique()

999

In [29]:
saved_df.primary_id.nunique()

1997

## Check wide file

In [30]:
wide_cb_df = pd.read_csv(os.path.join(RUN_DIR_PATH, f"wide_cb_data_lhc_{run_id}.csv"))
wide_cb_df.head()

,primary_id,future_id,strategy_code,Year,air_pollution,congestion,consumer_savings,crop_value,ecosystem_services,env_pollution,...,human_health,ippu_value,land_pollution,lvst_value,road_safety,sector_specific,system_cost,technical_cost,technical_savings,water_pollution
0,1001,0,AGRC:DEC_CH4_RICE,2019,0.0,0.0,NaN,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0
1,1001,0,AGRC:DEC_CH4_RICE,2020,0.0,0.0,NaN,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0
2,1001,0,AGRC:DEC_CH4_RICE,2021,0.0,0.0,NaN,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0
3,1001,0,AGRC:DEC_CH4_RICE,2022,0.0,0.0,NaN,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0
4,1001,0,AGRC:DEC_CH4_RICE,2023,0.0,0.0,NaN,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0

In [31]:
# check for null values in wide file
wide_null_counts = wide_cb_df.isnull().sum()
print("Null values in wide DataFrame:")
print(wide_null_counts)

Null values in wide DataFrame:
primary_id                 0
future_id                  0
strategy_code              0
Year                       0
air_pollution         100516
congestion            100516
consumer_savings        3120
crop_value            100516
ecosystem_services    100516
env_pollution         100516
fuel_cost             100516
human_health               0
ippu_value            100516
land_pollution        100516
lvst_value            100516
road_safety           100516
sector_specific       100516
system_cost           100516
technical_cost             0
technical_savings     103376
water_pollution       100516
dtype: int64

In [32]:
# check for inf and -inf values in wide file
wide_negative_inf_counts = (wide_cb_df == -float('inf')).sum()
print("Negative infinity counts in wide DataFrame:")
print(wide_negative_inf_counts)

Negative infinity counts in wide DataFrame:
primary_id            0
future_id             0
strategy_code         0
Year                  0
air_pollution         0
congestion            0
consumer_savings      0
crop_value            0
ecosystem_services    0
env_pollution         0
fuel_cost             0
human_health          0
ippu_value            0
land_pollution        0
lvst_value            0
road_safety           0
sector_specific       0
system_cost           0
technical_cost        0
technical_savings     0
water_pollution       0
dtype: int64

In [33]:
wide_cb_df.future_id.nunique()

999

In [34]:
wide_cb_df.primary_id.nunique()

1997

In [35]:
wide_cb_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103844 entries, 0 to 103843
Data columns (total 21 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   primary_id          103844 non-null  int64
 1   future_id           103844 non-null  int64
 2   strategy_code       103844 non-null  object
 3   Year                103844 non-null  int64
 4   air_pollution       3328 non-null    float64
 5   congestion          3328 non-null    float64
 6   consumer_savings    100724 non-null  float64
 7   crop_value          3328 non-null    float64
 8   ecosystem_services  3328 non-null    float64
 9   env_pollution       3328 non-null    float64
 10  fuel_cost           3328 non-null    float64
 11  human_health        103844 non-null  float64
 12  ippu_value          3328 non-null    float64
 13  land_pollution      3328 non-null    float64
 14  lvst_value          3328 non-null    float64
 15  road_safety         3328 non-null    float64
 16  sector_specific     3328 non-null    float64
 17  system_cost         3328 non-null    float64
 18  technical_cost      103844 non-null  float64
 19  technical_savings   468 non-null     float64
 20  water_pollution     3328 non-null    float64
dtypes: float64(17), int64(3), object(1)
memory usage: 16.6+ MB

In [36]:
wide_cb_df

,primary_id,future_id,strategy_code,Year,air_pollution,congestion,consumer_savings,crop_value,ecosystem_services,env_pollution,...,human_health,ippu_value,land_pollution,lvst_value,road_safety,sector_specific,system_cost,technical_cost,technical_savings,water_pollution
0,1001,0,AGRC:DEC_CH4_RICE,2019,0.0,0.0,NaN,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,NaN,0.0
1,1001,0,AGRC:DEC_CH4_RICE,2020,0.0,0.0,NaN,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,NaN,0.0
2,1001,0,AGRC:DEC_CH4_RICE,2021,0.0,0.0,NaN,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,NaN,0.0
3,1001,0,AGRC:DEC_CH4_RICE,2022,0.0,0.0,NaN,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,NaN,0.0
4,1001,0,AGRC:DEC_CH4_RICE,2023,0.0,0.0,NaN,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,NaN,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103839,375374,1000,PFLO:NZ,2066,NaN,NaN,29.128911,NaN,NaN,NaN,...,17.906486,NaN,NaN,NaN,NaN,NaN,NaN,-1.756948,NaN,NaN
103840,375374,1000,PFLO:NZ,2067,NaN,NaN,30.275406,NaN,NaN,NaN,...,18.583429,NaN,NaN,NaN,NaN,NaN,NaN,-1.828242,NaN,NaN
103841,375374,1000,PFLO:NZ,2068,NaN,NaN,31.443209,NaN,NaN,NaN,...,19.270369,NaN,NaN,NaN,NaN,NaN,NaN,-1.901486,NaN,NaN
103842,375374,1000,PFLO:NZ,2069,NaN,NaN,32.632247,NaN,NaN,NaN,...,19.966958,NaN,NaN,NaN,NaN,NaN,NaN,-1.976759,NaN,NaN
103843,375374,1000,PFLO:NZ,2070,NaN,NaN,33.844775,NaN,NaN,NaN,...,20.674288,NaN,NaN,NaN,NaN,NaN,NaN,-2.054242,NaN,NaN

In [37]:
saved_df

,strategy_code,future_id,region,time_period,difference_variable,variable_value_baseline,variable_value_pathway,difference_value,variable,value,primary_id
0,PFLO:NZ,613,uganda,4,mass_distance_traveled_trns_mt_km_water_borne,0.0,0.0,3465.860721,cb:trns:technical_cost:fuel_switch:maritime,0.0,374987
1,PFLO:NZ,613,uganda,5,mass_distance_traveled_trns_mt_km_water_borne,0.0,0.0,3568.072052,cb:trns:technical_cost:fuel_switch:maritime,0.0,374987
2,PFLO:NZ,613,uganda,6,mass_distance_traveled_trns_mt_km_water_borne,0.0,0.0,3694.312012,cb:trns:technical_cost:fuel_switch:maritime,0.0,374987
3,PFLO:NZ,613,uganda,7,mass_distance_traveled_trns_mt_km_water_borne,0.0,0.0,3863.588322,cb:trns:technical_cost:fuel_switch:maritime,0.0,374987
4,PFLO:NZ,613,uganda,8,mass_distance_traveled_trns_mt_km_water_borne,0.0,0.0,4069.944108,cb:trns:technical_cost:fuel_switch:maritime,0.0,374987
...,...,...,...,...,...,...,...,...,...,...,...
4437881,PFLO:NZ,372,uganda,15,lvst_total_tlu,0.0,0.0,0.000000,cb:lsmm:technical_cost:manure_management_shift...,0.0,374746
4437882,PFLO:NZ,372,uganda,16,lvst_total_tlu,0.0,0.0,0.000000,cb:lsmm:technical_cost:manure_management_shift...,0.0,374746
4437883,PFLO:NZ,372,uganda,17,lvst_total_tlu,0.0,0.0,0.000000,cb:lsmm:technical_cost:manure_management_shift...,0.0,374746
4437884,PFLO:NZ,372,uganda,18,lvst_total_tlu,0.0,0.0,0.000000,cb:lsmm:technical_cost:manure_management_shift...,0.0,374746
4437885,PFLO:NZ,372,uganda,19,lvst_total_tlu,0.0,0.0,0.000000,cb:lsmm:technical_cost:manure_management_shift...,0.0,374746

In [38]:
saved_df.strategy_code.value_counts()

strategy_code
PFLO:NZ                        3811876
PFLO:NDC_2_2025_TUNED            11906
TRNS:SHIFT_FUEL_MEDIUM_DUTY      10208
INEN:SHIFT_FUEL_HEAT             10034
IPPU:DEC_HFCS                     9976
                                ...
ENTC:DEC_LOSSES                   9686
WALI:INC_TREATMENT_URBAN          9686
LSMM:INC_MANAGEMENT_OTHER         9686
LNDU:DEC_SOC_LOSS_PASTURES        9686
AGRC:INC_PRODUCTIVITY             9686
Name: count, Length: 65, dtype: int64