In [1]:
# Load packages
from costs_benefits_ssp.cb_calculate import CostBenefits
import pandas as pd
import os
import pathlib
import numpy as np

In [2]:
# Define paths
SSP_PATH = pathlib.Path(os.getcwd()).parent.parent.as_posix()
SSP_RUN  = os.path.join(SSP_PATH, "ssp_run_output/sisepuede_summary_results_run_sisepuede_run_2026-04-01T14;29;26.355576/nwr")


CB_DEFAULT_DEFINITION_PATH = os.path.join(SSP_PATH,"cost-benefits/cb_cost_factors")
CB_DEFAULT_DEFINITION_FILE_PATH = os.path.join(CB_DEFAULT_DEFINITION_PATH, "cb_config_params.xlsx")

CB_OUTPUT = os.path.join(SSP_PATH, "Tableau/data")

In [3]:
CB_OUTPUT

'/Users/alexa/Projects/ssp_uganda_data/ssp_modeling/Tableau/data'

In [4]:
CB_DEFAULT_DEFINITION_PATH

'/Users/alexa/Projects/ssp_uganda_data/ssp_modeling/cost-benefits/cb_cost_factors'

In [5]:
# Load data
ssp_data = pd.read_csv(os.path.join(SSP_RUN, "uganda.csv"))
att_primary = pd.read_csv(os.path.join(SSP_RUN,"ATTRIBUTE_PRIMARY.csv"))
att_strategy = pd.read_csv(os.path.join(SSP_RUN,"ATTRIBUTE_STRATEGY.csv"))
strategy_code_base = "BASE"

In [6]:
att_primary

   primary_id  design_id  strategy_id  future_id
0           0          0            0          0
1      700070          0         6004          0
2      760076          0         6010          0
3      770077          0         6011          0
4      780078          0         6012          0

In [7]:
# Instantiate CostBenefits object
cb = CostBenefits(ssp_data, att_primary, att_strategy, strategy_code_base)

# The export_db_to_excel method saves the initial configuration of the cost tables to an excel file.
# Each sheet represents a table in the cost and benefit program database.
# If the Excel file name is not given, the file will be saved with the default name cb_config_params.xlsx on the current python session.

#cb.export_db_to_excel(CB_DEFAULT_DEFINITION_FILE_PATH)

# Once that the excel file has been updated, we can reload it in order to update the cost factors database
cb.load_cb_parameters(CB_DEFAULT_DEFINITION_FILE_PATH)

The TX TX:FRST:INCREASE_SEQUESTRATION_NZ is missing on AttTransformationCode
The TX TX:LNDU:DEC_WETLAND_LOSS_NZ is missing on AttTransformationCode
The TX TX:LNDU:SET_WETLANDS_MINIMUM_NZ is missing on AttTransformationCode
The TX TX:SCOE:INC_EFFICIENCY_HEAT_NZ is missing on AttTransformationCode
The TX TX:FRST:INCREASE_SEQUESTRATION_NDC_25 is missing on AttTransformationCode
The TX TX:LNDU:DEC_WETLAND_LOSS_NDC_25 is missing on AttTransformationCode
The TX TX:LNDU:SET_WETLANDS_MINIMUM_NDC_25 is missing on AttTransformationCode
The TX TX:SCOE:INC_EFFICIENCY_HEAT_NDC_25 is missing on AttTransformationCode
The TX TX:SCOE:INC_EFFICIENCY_HEAT_NDC_25 is missing on AttTransformationCode
The TX TX:LNDU:DEC_WETLAND_LOSS_NDC_25 is missing on AttTransformationCode
The TX TX:LNDU:SET_WETLANDS_MINIMUM_NDC_25 is missing on AttTransformationCode
The TX TX:SCOE:INC_EFFICIENCY_HEAT_NDC_25 is missing on AttTransformationCode
Cargamos configuración de archivo excel
Se actualizó la base de datos

In [8]:
# Compute System Costs
results_system = cb.compute_system_cost_for_all_strategies()

************************************
*Strategy : PFLO:HBLE (0/4)
************************************

---------Costs for: cb:wali:technical_cost:sanitation:unimp_rural.
La variable se evalúa en System Cost
---------Costs for: cb:wali:technical_cost:sanitation:imp_rural.
La variable se evalúa en System Cost
---------Costs for: cb:wali:technical_cost:sanitation:safeman_rural.
La variable se evalúa en System Cost
---------Costs for: cb:wali:technical_cost:sanitation:unimp_urban.
La variable se evalúa en System Cost
---------Costs for: cb:wali:technical_cost:sanitation:imp_urban.
La variable se evalúa en System Cost
---------Costs for: cb:wali:technical_cost:sanitation:safeman_urban.
La variable se evalúa en System Cost
---------Costs for: cb:wali:technical_cost:sanitation:omit_rural.
La variable se evalúa en System Cost
---------Costs for: cb:entc:technical_cost:electricity:capex.
La variable se evalúa en System Cost
---------Costs for: cb:entc:technical_cost:electricity:transmission.
La variable se evalúa en System Cost
---------Costs for: change_in_emissions.
La variable se evalúa en System Cost
---------Costs for: cb:trns:air_pollution:X:diesel.
La variable se evalúa en System Cost
---------Costs for: cb:trns:air_pollution:X:gasoline.
La variable se evalúa en System Cost
---------Costs for: cb:trns:air_pollution:X:biofuels.
La variable se evalúa en System Cost
---------Costs for: cb:lndu:ecosystem_services:forests:primary.
La variable se evalúa en System Cost
---------Costs for: cb:lndu:ecosystem_services:forests:secondary.
La variable se evalúa en System Cost
---------Costs for: cb:trns:system_cost:freight_transport:aviation.
La variable se evalúa en System Cost
---------Costs for: cb:trns:system_cost:freight_transport:rail.
La variable se evalúa en System Cost
---------Costs for: cb:trns:system_cost:freight_transport:road_heavy.
La variable se evalúa en System Cost
---------Costs for: cb:trns:system_cost:freight_transport:water_borne.
La variable se evalúa en System Cost
---------Costs for: cb:waso:technical_cost:waste_management:biogas.
La variable se evalúa en System Cost
---------Costs for: cb:waso:technical_cost:waste_management:compost.
La variable se evalúa en System Cost
---------Costs for: cb:waso:technical_cost:waste_management:incinerated.
La variable se evalúa en System Cost
---------Costs for: cb:waso:technical_cost:waste_management:landfilled.
La variable se evalúa en System Cost
---------Costs for: cb:waso:technical_cost:waste_management:open_dump.
La variable se evalúa en System Cost
---------Costs for: cb:waso:technical_cost:waste_management:recycled.
La variable se evalúa en System Cost
---------Costs for: cb:trww:technical_cost:wastewater_treatment:tertiary_aerobic.
La variable se evalúa en System Cost
---------Costs for: cb:trww:technical_cost:wastewater_treatment:tertiary_anaerobic.
La variable se evalúa en System Cost
---------Costs for: cb:trww:technical_cost:wastewater_treatment:primary.
La variable se evalúa en System Cost
---------Costs for: cb:trww:technical_cost:wastewater_treatment:secondary_aerobic.
La variable se evalúa en System Cost
---------Costs for: cb:trww:technical_cost:wastewater_treatment:secondary_anaerobic.
La variable se evalúa en System Cost
---------Costs for: cb:trww:technical_cost:wastewater_treatment:untreated_with_sewerage.
La variable se evalúa en System Cost
---------Costs for: cb:wali:human_health:safe_sanitation:X.
La variable se evalúa en System Cost
---------Costs for: cb:lvst:lvst_value:livestock_produced:buffalo.
La variable se evalúa en System Cost
---------Costs for: cb:lvst:lvst_value:livestock_produced:cattle_dairy.
La variable se evalúa en System Cost
---------Costs for: cb:lvst:lvst_value:livestock_produced:cattle_nondairy.
La variable se evalúa en System Cost
---------Costs for: cb:lvst:lvst_value:livestock_produced:chickens.
La variable se evalúa en System Cost
---------Costs for: cb:lvst:lvst_value:livestock_produced:goats.
La variable se evalúa en System Cost
---------Costs for: cb:lvst:lvst_value:livestock_produced:horses.
La variable se evalúa en System Cost
---------Costs for: cb:lvst:lvst_value:livestock_produced:mules.
La variable se evalúa en System Cost
---------Costs for: cb:lvst:lvst_value:livestock_produced:pigs.
La variable se evalúa en System Cost
---------Costs for: cb:lvst:lvst_value:livestock_produced:sheep.
La variable se evalúa en System Cost
---------Costs for: cb:agrc:crop_value:crops_produced:bevs_and_spices.
La variable se evalúa en System Cost
---------Costs for: cb:agrc:crop_value:crops_produced:cereals.
La variable se evalúa en System Cost
---------Costs for: cb:agrc:crop_value:crops_produced:fibers.
La variable se evalúa en System Cost
---------Costs for: cb:agrc:crop_value:crops_produced:fruits.
La variable se evalúa en System Cost
---------Costs for: cb:agrc:crop_value:crops_produced:herbs.
La variable se evalúa en System Cost
---------Costs for: cb:agrc:crop_value:crops_produced:nuts.
La variable se evalúa en System Cost
---------Costs for: cb:agrc:crop_value:crops_produced:other_annual.
La variable se evalúa en System Cost
---------Costs for: cb:agrc:crop_value:crops_produced:other_woody_perennial.
La variable se evalúa en System Cost
---------Costs for: cb:agrc:crop_value:crops_produced:pulses.
La variable se evalúa en System Cost
---------Costs for: cb:agrc:crop_value:crops_produced:rice.
La variable se evalúa en System Cost
---------Costs for: cb:agrc:crop_value:crops_produced:sugar_cane.
La variable se evalúa en System Cost
---------Costs for: cb:agrc:crop_value:crops_produced:tubers.
La variable se evalúa en System Cost
---------Costs for: cb:agrc:crop_value:crops_produced:vegetables.
La variable se evalúa en System Cost
---------Costs for: cb:trww:technical_cost:waste_to_energy:X.
La variable se evalúa en System Cost
---------Costs for: cb:trww:fuel_cost:waste_to_energy_value:X.
La variable se evalúa en System Cost
---------Costs for: cb:ccsq:sector_specific:fuel_cost:X.
La variable se evalúa en System Cost
---------Costs for: cb:inen:sector_specific:fuel_cost:X.
La variable se evalúa en System Cost
---------Costs for: cb:scoe:sector_specific:fuel_cost:X.
La variable se evalúa en System Cost
---------Costs for: cb:entc:sector_specific:fuel_cost:X.
La variable se evalúa en System Cost
---------Costs for: cb:trns:sector_specific:fuel_cost:X.
La variable se evalúa en System Cost
---------Costs for: cb:ippu:air_pollution:X:cement.
La variable se evalúa en System Cost
---------Costs for: cb:trns:system_cost:passenger_transport:aviation.
La variable se evalúa en System Cost
---------Costs for: cb:trns:system_cost:passenger_transport:powered_bikes.
La variable se evalúa en System Cost
---------Costs for: cb:trns:system_cost:passenger_transport:public.
La variable se evalúa en System Cost
---------Costs for: cb:trns:system_cost:passenger_transport:rail_passenger.
La variable se evalúa en System Cost
---------Costs for: cb:trns:system_cost:passenger_transport:road_heavy_regional.
La variable se evalúa en System Cost
---------Costs for: cb:trns:system_cost:passenger_transport:road_light.
La variable se evalúa en System Cost
---------Costs for: cb:waso:env_pollution:open_dumping:X.
La variable se evalúa en System Cost
---------Costs for: cb:ippu:ippu_value:industrial_products:cement.
La variable se evalúa en System Cost
---------Costs for: cb:ippu:ippu_value:industrial_products:steel.
La variable se evalúa en System Cost
---------Costs for: cb:ccsq:sector_specific:electricity_cost:X.
La variable se evalúa en System Cost
---------Costs for: cb:inen:sector_specific:electricity_cost:X.
La variable se evalúa en System Cost
---------Costs for: cb:scoe:sector_specific:electricity_cost:X.
La variable se evalúa en System Cost
---------Costs for: cb:trns:sector_specific:electricity_cost:X.
La variable se evalúa en System Cost
---------Costs for: cb:waso:technical_cost:waste_to_energy:incineration.
La variable se evalúa en System Cost
---------Costs for: cb:waso:technical_cost:waste_to_energy:anaerobic.
La variable se evalúa en System Cost
---------Costs for: cb:waso:technical_cost:waste_to_energy:landfill.
La variable se evalúa en System Cost
---------Costs for: cb:waso:fuel_cost:waste_to_energy_value:anaerobic.
La variable se evalúa en System Cost
---------Costs for: cb:waso:fuel_cost:waste_to_energy_value:landfill.
La variable se evalúa en System Cost
---------Costs for: cb:entc:air_pollution:X:diesel.
La variable se evalúa en System Cost
---------Costs for: cb:entc:air_pollution:X:gasoline.
La variable se evalúa en System Cost
---------Costs for: cb:entc:air_pollution:X:biofuels.
La variable se evalúa en System Cost
---------Costs for: cb:trns:congestion:X:diesel.
La variable se evalúa en System Cost
---------Costs for: cb:trns:congestion:X:gasoline.
La variable se evalúa en System Cost
---------Costs for: cb:trns:congestion:X:biofuels.
La variable se evalúa en System Cost
---------Costs for: cb:trns:congestion:X:electricity.
La variable se evalúa en System Cost
---------Costs for: cb:waso:technical_cost:waste_collection:biogas.
La variable se evalúa en System Cost
---------Costs for: cb:waso:technical_cost:waste_collection:compost.
La variable se evalúa en System Cost
---------Costs for: cb:waso:technical_cost:waste_collection:incinerated.
La variable se evalúa en System Cost
---------Costs for: cb:waso:technical_cost:waste_collection:landfilled.
La variable se evalúa en System Cost
---------Costs for: cb:waso:technical_cost:waste_collection:open_dump.
La variable se evalúa en System Cost
---------Costs for: cb:waso:technical_cost:waste_collection:recycled.
La variable se evalúa en System Cost
---------Costs for: cb:soil:technical_cost:agriculture_inputs:fertilizer.
La variable se evalúa en System Cost
---------Costs for: cb:soil:land_pollution:N_leaching:fertilizer.
La variable se evalúa en System Cost
---------Costs for: cb:inen:air_pollution:X:diesel.
La variable se evalúa en System Cost
---------Costs for: cb:inen:air_pollution:X:gasoline.
La variable se evalúa en System Cost
---------Costs for: cb:inen:air_pollution:X:biomass.
La variable se evalúa en System Cost
---------Costs for: cb:inen:air_pollution:X:coal.
La variable se evalúa en System Cost
---------Costs for: cb:inen:air_pollution:X:coke.
La variable se evalúa en System Cost
---------Costs for: cb:inen:air_pollution:X:natural_gas.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:X:X.
La variable se evalúa en System Cost
---------Costs for: cb:trns:road_safety:X:diesel.
La variable se evalúa en System Cost
---------Costs for: cb:trns:road_safety:X:gasoline.
La variable se evalúa en System Cost
---------Costs for: cb:trns:road_safety:X:biofuels.
La variable se evalúa en System Cost
---------Costs for: cb:trns:road_safety:X:electricity.
La variable se evalúa en System Cost
---------Costs for: cb:trww:water_pollution:wastewater_treatment:P.
La variable se evalúa en System Cost
---------Costs for: cb:trww:water_pollution:wastewater_treatment:N.
La variable se evalúa en System Cost
---------Costs for: cb:trww:water_pollution:wastewater_treatment:COD.
La variable se evalúa en System Cost
---------Costs for: cb:trww:water_pollution:wastewater_treatment:BOD.
La variable se evalúa en System Cost
---------Costs for: cb:lsmm:fuel_cost:waste_to_energy_value:X.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:ccsq:electricity.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:ccsq:hydrogen.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:ccsq:natural_gas.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:entc:biofuels.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:entc:biogas.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:entc:biomass.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:entc:coal.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:entc:coke.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:entc:diesel.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:entc:electricity.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:entc:gasoline.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:entc:hydrocarbon_gas_liquids.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:entc:hydrogen.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:entc:kerosene.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:entc:natural_gas.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:entc:nuclear.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:entc:oil.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:entc:other.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:entc:waste.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:inen:biomass.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:inen:coal.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:inen:coke.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:inen:diesel.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:inen:electricity.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:inen:gasoline.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:inen:hydrocarbon_gas_liquids.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:inen:hydrogen.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:inen:kerosene.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:inen:natural_gas.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:inen:oil.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:scoe:biomass.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:scoe:coal.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:scoe:diesel.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:scoe:electricity.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:scoe:gasoline.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:scoe:hydrocarbon_gas_liquids.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:scoe:hydrogen.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:scoe:kerosene.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:scoe:natural_gas.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:trns:biofuels.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:trns:diesel.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:trns:electricity.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:trns:gasoline.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:trns:hydrocarbon_gas_liquids.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:trns:hydrogen.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:trns:kerosene.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:trns:natural_gas.
La variable se evalúa en System Cost

************************************
*Strategy : PFLO:NDC_25_SCOE_ELEC (1/4)
************************************

---------Costs for: cb:wali:technical_cost:sanitation:unimp_rural.
La variable se evalúa en System Cost
---------Costs for: cb:wali:technical_cost:sanitation:imp_rural.
La variable se evalúa en System Cost
---------Costs for: cb:wali:technical_cost:sanitation:safeman_rural.
La variable se evalúa en System Cost
---------Costs for: cb:wali:technical_cost:sanitation:unimp_urban.
La variable se evalúa en System Cost
---------Costs for: cb:wali:technical_cost:sanitation:imp_urban.
La variable se evalúa en System Cost
---------Costs for: cb:wali:technical_cost:sanitation:safeman_urban.
La variable se evalúa en System Cost
---------Costs for: cb:wali:technical_cost:sanitation:omit_rural.
La variable se evalúa en System Cost
---------Costs for: cb:entc:technical_cost:electricity:capex.
La variable se evalúa en System Cost
---------Costs for: cb:entc:technical_cost:electricity:transmission.
La variable se evalúa en System Cost
---------Costs for: change_in_emissions.
La variable se evalúa en System Cost
---------Costs for: cb:trns:air_pollution:X:diesel.
La variable se evalúa en System Cost
---------Costs for: cb:trns:air_pollution:X:gasoline.
La variable se evalúa en System Cost
---------Costs for: cb:trns:air_pollution:X:biofuels.
La variable se evalúa en System Cost
---------Costs for: cb:lndu:ecosystem_services:forests:primary.
La variable se evalúa en System Cost
---------Costs for: cb:lndu:ecosystem_services:forests:secondary.
La variable se evalúa en System Cost
---------Costs for: cb:trns:system_cost:freight_transport:aviation.
La variable se evalúa en System Cost
---------Costs for: cb:trns:system_cost:freight_transport:rail.
La variable se evalúa en System Cost
---------Costs for: cb:trns:system_cost:freight_transport:road_heavy.
La variable se evalúa en System Cost
---------Costs for: cb:trns:system_cost:freight_transport:water_borne.
La variable se evalúa en System Cost
---------Costs for: cb:waso:technical_cost:waste_management:biogas.
La variable se evalúa en System Cost
---------Costs for: cb:waso:technical_cost:waste_management:compost.
La variable se evalúa en System Cost
---------Costs for: cb:waso:technical_cost:waste_management:incinerated.
La variable se evalúa en System Cost
---------Costs for: cb:waso:technical_cost:waste_management:landfilled.
La variable se evalúa en System Cost
---------Costs for: cb:waso:technical_cost:waste_management:open_dump.
La variable se evalúa en System Cost
---------Costs for: cb:waso:technical_cost:waste_management:recycled.
La variable se evalúa en System Cost
---------Costs for: cb:trww:technical_cost:wastewater_treatment:tertiary_aerobic.
La variable se evalúa en System Cost
---------Costs for: cb:trww:technical_cost:wastewater_treatment:tertiary_anaerobic.
La variable se evalúa en System Cost
---------Costs for: cb:trww:technical_cost:wastewater_treatment:primary.
La variable se evalúa en System Cost
---------Costs for: cb:trww:technical_cost:wastewater_treatment:secondary_aerobic.
La variable se evalúa en System Cost
---------Costs for: cb:trww:technical_cost:wastewater_treatment:secondary_anaerobic.
La variable se evalúa en System Cost
---------Costs for: cb:trww:technical_cost:wastewater_treatment:untreated_with_sewerage.
La variable se evalúa en System Cost
---------Costs for: cb:wali:human_health:safe_sanitation:X.
La variable se evalúa en System Cost
---------Costs for: cb:lvst:lvst_value:livestock_produced:buffalo.
La variable se evalúa en System Cost
---------Costs for: cb:lvst:lvst_value:livestock_produced:cattle_dairy.
La variable se evalúa en System Cost
---------Costs for: cb:lvst:lvst_value:livestock_produced:cattle_nondairy.
La variable se evalúa en System Cost
---------Costs for: cb:lvst:lvst_value:livestock_produced:chickens.
La variable se evalúa en System Cost
---------Costs for: cb:lvst:lvst_value:livestock_produced:goats.
La variable se evalúa en System Cost
---------Costs for: cb:lvst:lvst_value:livestock_produced:horses.
La variable se evalúa en System Cost
---------Costs for: cb:lvst:lvst_value:livestock_produced:mules.
La variable se evalúa en System Cost
---------Costs for: cb:lvst:lvst_value:livestock_produced:pigs.
La variable se evalúa en System Cost

In [9]:
# Compute Technical Costs
results_tx = cb.compute_technical_cost_for_all_strategies()

************************************
*Strategy : PFLO:HBLE (0/4)
************************************

---------Costs for: cb:inen:technical_cost:fuel_switch:lo_heat.
La variable se evalúa en Transformation Cost
---------Costs for: cb:inen:technical_savings:fuel_switch:lo_heat.
La variable se evalúa en Transformation Cost
---------Costs for: cb:inen:technical_cost:fuel_switch:hi_heat.
La variable se evalúa en Transformation Cost
---------Costs for: cb:inen:technical_savings:fuel_switch:hi_heat.
La variable se evalúa en Transformation Cost
---------Costs for: cb:inen:technical_cost:fuel_switch:all.
La variable se evalúa en Transformation Cost
---------Costs for: cb:inen:technical_savings:fuel_switch:all.
La variable se evalúa en Transformation Cost
---------Costs for: cb:inen:technical_cost:efficiency:X.
La variable se evalúa en Transformation Cost
---------Costs for: cb:trns:technical_cost:electrification:LDV.
La variable se evalúa en Transformation Cost
---------Costs for: cb:trns:technical_savings:electrification:LDV.
La variable se evalúa en Transformation Cost
---------Costs for: cb:trns:technical_cost:electrification:rail.
La variable se evalúa en Transformation Cost
---------Costs for: cb:trns:technical_savings:electrification:rail.
La variable se evalúa en Transformation Cost
---------Costs for: cb:trns:technical_cost:fuel_switch:maritime.
La variable se evalúa en Transformation Cost
---------Costs for: cb:trns:technical_cost:electrification:hdv_vehicles.
La variable se evalúa en Transformation Cost
---------Costs for: cb:trns:technical_savings:electrification:hdv_vehicles.
La variable se evalúa en Transformation Cost
---------Costs for: cb:trns:technical_cost:electrification:hdv_charger.
La variable se evalúa en Transformation Cost
---------Costs for: cb:trns:technical_cost:efficiency:electric.
La variable se evalúa en Transformation Cost
---------Costs for: cb:trns:technical_cost:efficiency:non_electric.
La variable se evalúa en Transformation Cost
---------Costs for: cb:trns:technical_cost:efficiency:all.
La variable se evalúa en Transformation Cost
---------Costs for: cb:scoe:technical_cost:efficiency:appliance.
La variable se evalúa en Transformation Cost
---------Costs for: cb:scoe:technical_cost:fuel_switch:heat_pumps.
La variable se evalúa en Transformation Cost

/opt/anaconda3/envs/ssp_uganda_env/lib/python3.11/site-packages/costs_benefits_ssp/cb_calculate.py:856: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp["difference_variable"] = cb_orm.diff_var
/opt/anaconda3/envs/ssp_uganda_env/lib/python3.11/site-packages/costs_benefits_ssp/cb_calculate.py:857: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp["difference_value"] = data_merged["difference"]
/opt/anaconda3/envs/ssp_uganda_env/lib/python3.11/site-packages/costs_benefits_ssp/cb_calculate.py:858: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp["variable"] = cb_orm.output_variable_name
/opt/anaconda3/envs/ssp_uganda_env/lib/python3.11/site-packages/costs_benefits_ssp/cb_calculate.py:859: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp["value"] = data_merged["values"]
/opt/anaconda3/envs/ssp_uganda_env/lib/python3.11/site-packages/costs_benefits_ssp/cb_calculate.py:863: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp['variable_value_baseline'] = 0
/opt/anaconda3/envs/ssp_uganda_env/lib/python3.11/site-packages/costs_benefits_ssp/cb_calculate.py:1067: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_output['variable_value_baseline'] = 0
/opt/anaconda3/envs/ssp_uganda_env/lib/python3.11/site-packages/costs_benefits_ssp/cb_calculate.py:1070: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_output['variable_value_pathway'] = data_merged["difference_value"]

---------Costs for: cb:scoe:technical_savings:fuel_switch:heat_pumps.
La variable se evalúa en Transformation Cost
---------Costs for: cb:scoe:technical_cost:efficiency:building_shell.
La variable se evalúa en Transformation Cost
---------Costs for: cb:entc:technical_cost:loss_reduction:electricity.
La variable se evalúa en Transformation Cost
---------Costs for: cb:ippu:technical_cost:clinker:X.
La variable se evalúa en Transformation Cost
---------Costs for: cb:ippu:technical_cost:abating_gases:n2o.
La variable se evalúa en Transformation Cost
---------Costs for: cb:ippu:technical_cost:abating_gases:pfcs.
La variable se evalúa en Transformation Cost
---------Costs for: cb:ippu:technical_cost:abating_gases:other_fgases.
La variable se evalúa en Transformation Cost
---------Costs for: cb:fgtv:technical_cost:flaring:X.
La variable se evalúa en Transformation Cost
---------Costs for: cb:fgtv:technical_cost:leaks:X.
La variable se evalúa en Transformation Cost
---------Costs for: cb:waso:technical_cost:consumer_food_waste:X.
La variable se evalúa en Transformation Cost
---------Costs for: cb:waso:consumer_savings:consumer_food_waste:X.
La variable se evalúa en Transformation Cost
---------Costs for: cb:lvst:technical_cost:ent_ferm_mgmt:X.
La variable se evalúa en Transformation Cost
---------Costs for: cb:agrc:technical_cost:rice_mgmt:X.
La variable se evalúa en Transformation Cost
---------Costs for: cb:agrc:technical_cost:producer_food_waste:X.
La variable se evalúa en Transformation Cost
---------Costs for: cb:agrc:technical_savings:producer_food_waste:X.
La variable se evalúa en Transformation Cost
---------Costs for: cb:agrc:technical_cost:increase_productivity:X.
La variable se evalúa en Transformation Cost
---------Costs for: cb:lvst:technical_cost:increase_productivity:X.
La variable se evalúa en Transformation Cost
---------Costs for: cb:pflo:human_health:better_diets:X.
La variable se evalúa en Transformation Cost
---------Costs for: cb:pflo:consumer_savings:better_diets:X.
La variable se evalúa en Transformation Cost
---------Costs for: cb:lndu:technical_cost:silvopasture:X.
La variable se evalúa en Transformation Cost
---------Costs for: cb:lndu:technical_cost:all_secondary_forests:X.
La variable se evalúa en Transformation Cost
---------Costs for: cb:ippu:technical_cost:industrial_ccs:X.
La variable se evalúa en Transformation Cost
---------Costs for: cb:agrc:consumer_savings:cons_ag_land_value:X.
La variable se evalúa en Transformation Cost
---------Costs for: cb:agrc:technical_savings:cons_ag:X.
La variable se evalúa en Transformation Cost
---------Costs for: cb:lsmm:technical_cost:manure_management_cattle_pigs.
La variable se evalúa en Transformation Cost
---------Costs for: cb:lsmm:technical_cost:manure_management_poultry.
La variable se evalúa en Transformation Cost
---------Costs for: cb:lsmm:technical_cost:manure_management_other.
La variable se evalúa en Transformation Cost
---------Costs for: cb:lsmm:technical_cost:biogas_capture.
La variable se evalúa en Transformation Cost
---------Costs for: cb:waso:technical_cost:biogas_capture.
La variable se evalúa en Transformation Cost
---------Costs for: cb:entc:technical_savings:electricity:opex.
La variable se evalúa en Transformation Cost

************************************
*Strategy : PFLO:NDC_25_SCOE_ELEC (1/4)
************************************

---------Costs for: cb:inen:technical_cost:fuel_switch:lo_heat.
La variable se evalúa en Transformation Cost
---------Costs for: cb:inen:technical_savings:fuel_switch:lo_heat.
La variable se evalúa en Transformation Cost
---------Costs for: cb:inen:technical_cost:fuel_switch:hi_heat.
La variable se evalúa en Transformation Cost
---------Costs for: cb:inen:technical_savings:fuel_switch:hi_heat.
La variable se evalúa en Transformation Cost
---------Costs for: cb:inen:technical_cost:fuel_switch:all.
La variable se evalúa en Transformation Cost
---------Costs for: cb:inen:technical_savings:fuel_switch:all.
La variable se evalúa en Transformation Cost
---------Costs for: cb:inen:technical_cost:efficiency:X.
La variable se evalúa en Transformation Cost
---------Costs for: cb:trns:technical_cost:electrification:LDV.
La variable se evalúa en Transformation Cost
---------Costs for: cb:trns:technical_savings:electrification:LDV.
La variable se evalúa en Transformation Cost
---------Costs for: cb:trns:technical_cost:electrification:hdv_vehicles.
La variable se evalúa en Transformation Cost
---------Costs for: cb:trns:technical_savings:electrification:hdv_vehicles.
La variable se evalúa en Transformation Cost
---------Costs for: cb:trns:technical_cost:electrification:hdv_charger.
La variable se evalúa en Transformation Cost
---------Costs for: cb:trns:technical_cost:efficiency:non_electric.
La variable se evalúa en Transformation Cost
---------Costs for: cb:trns:technical_cost:efficiency:all.
La variable se evalúa en Transformation Cost
---------Costs for: cb:scoe:technical_cost:fuel_switch:heat_pumps.
La variable se evalúa en Transformation Cost
---------Costs for: cb:scoe:technical_savings:fuel_switch:heat_pumps.
La variable se evalúa en Transformation Cost
---------Costs for: cb:scoe:technical_cost:efficiency:building_shell.
La variable se evalúa en Transformation Cost
---------Costs for: cb:entc:technical_cost:loss_reduction:electricity.
La variable se evalúa en Transformation Cost
---------Costs for: cb:ippu:technical_cost:clinker:X.
La variable se evalúa en Transformation Cost
---------Costs for: cb:waso:technical_cost:consumer_food_waste:X.
La variable se evalúa en Transformation Cost
---------Costs for: cb:waso:consumer_savings:consumer_food_waste:X.
La variable se evalúa en Transformation Cost
---------Costs for: cb:lvst:technical_cost:ent_ferm_mgmt:X.
La variable se evalúa en Transformation Cost
---------Costs for: cb:agrc:technical_cost:increase_productivity:X.
La variable se evalúa en Transformation Cost
---------Costs for: cb:lvst:technical_cost:increase_productivity:X.
La variable se evalúa en Transformation Cost
---------Costs for: cb:lndu:technical_cost:silvopasture:X.
La variable se evalúa en Transformation Cost
---------Costs for: cb:lndu:technical_cost:all_secondary_forests:X.
La variable se evalúa en Transformation Cost
---------Costs for: cb:agrc:consumer_savings:cons_ag_land_value:X.
La variable se evalúa en Transformation Cost
---------Costs for: cb:agrc:technical_savings:cons_ag:X.
La variable se evalúa en Transformation Cost
---------Costs for: cb:waso:technical_cost:biogas_capture.
La variable se evalúa en Transformation Cost
---------Costs for: cb:entc:technical_savings:electricity:opex.
La variable se evalúa en Transformation Cost

/opt/anaconda3/envs/ssp_uganda_env/lib/python3.11/site-packages/costs_benefits_ssp/cb_calculate.py:1067: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_output['variable_value_baseline'] = 0
/opt/anaconda3/envs/ssp_uganda_env/lib/python3.11/site-packages/costs_benefits_ssp/cb_calculate.py:1070: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_output['variable_value_pathway'] = data_merged["difference_value"]

************************************
*Strategy : PFLO:NDC_25_UNCONDITIONAL (2/4)
************************************

---------Costs for: cb:scoe:technical_cost:fuel_switch:heat_pumps.
La variable se evalúa en Transformation Cost
---------Costs for: cb:scoe:technical_savings:fuel_switch:heat_pumps.
La variable se evalúa en Transformation Cost
---------Costs for: cb:scoe:technical_cost:efficiency:building_shell.
La variable se evalúa en Transformation Cost
---------Costs for: cb:waso:technical_cost:biogas_capture.
La variable se evalúa en Transformation Cost

************************************
*Strategy : PFLO:NDC_25_UNCONDITIONAL_CE (3/4)
************************************

---------Costs for: cb:scoe:technical_cost:fuel_switch:heat_pumps.
La variable se evalúa en Transformation Cost
---------Costs for: cb:scoe:technical_savings:fuel_switch:heat_pumps.
La variable se evalúa en Transformation Cost
---------Costs for: cb:scoe:technical_cost:efficiency:building_shell.
La variable se evalúa en Transformation Cost
---------Costs for: cb:ippu:technical_cost:clinker:X.
La variable se evalúa en Transformation Cost
---------Costs for: cb:agrc:technical_cost:increase_productivity:X.
La variable se evalúa en Transformation Cost
---------Costs for: cb:waso:technical_cost:biogas_capture.
La variable se evalúa en Transformation Cost

/opt/anaconda3/envs/ssp_uganda_env/lib/python3.11/site-packages/costs_benefits_ssp/cb_calculate.py:1067: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_output['variable_value_baseline'] = 0
/opt/anaconda3/envs/ssp_uganda_env/lib/python3.11/site-packages/costs_benefits_ssp/cb_calculate.py:1070: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_output['variable_value_pathway'] = data_merged["difference_value"]

In [10]:
# Combine results
results_all = pd.concat([results_system, results_tx], ignore_index = True)

#-------------POST PROCESS SIMULATION RESULTS---------------
# Post process interactions among strategies that affect the same variables
results_all_pp = cb.cb_process_interactions(results_all)

# SHIFT any stray costs incurred from 2015 to 2025 to 2025 and 2035
results_all_pp_shifted = cb.cb_shift_costs(results_all_pp)

Resolving Interactions in SCOE : TX:SCOE:INC_EFFICIENCY_APPLIANCE, TX:SCOE:SHIFT_FUEL_HEAT, TX:SCOE:SHIFT_FUEL_HEAT, TX:SCOE:DEC_DEMAND_HEAT
Resolving Interactions in INEN : TX:INEN:SHIFT_FUEL_HEAT, TX:INEN:SHIFT_FUEL_HEAT, TX:INEN:SHIFT_FUEL_HEAT, TX:INEN:SHIFT_FUEL_HEAT, TX:INEN:SHIFT_FUEL_HEAT, TX:INEN:SHIFT_FUEL_HEAT, TX:INEN:INC_EFFICIENCY_ENERGY
Resolving Interactions in SCOE : TX:SCOE:SHIFT_FUEL_HEAT, TX:SCOE:SHIFT_FUEL_HEAT, TX:SCOE:DEC_DEMAND_HEAT
Resolving Interactions in INEN : TX:INEN:SHIFT_FUEL_HEAT, TX:INEN:SHIFT_FUEL_HEAT, TX:INEN:SHIFT_FUEL_HEAT, TX:INEN:SHIFT_FUEL_HEAT, TX:INEN:SHIFT_FUEL_HEAT, TX:INEN:SHIFT_FUEL_HEAT, TX:INEN:INC_EFFICIENCY_ENERGY
Resolving Interactions in SCOE : TX:SCOE:SHIFT_FUEL_HEAT, TX:SCOE:SHIFT_FUEL_HEAT, TX:SCOE:DEC_DEMAND_HEAT
Resolving Interactions in INEN :
No interactions, skipping... PFLO:NDC_25_UNCONDITIONAL
Resolving Interactions in SCOE : TX:SCOE:SHIFT_FUEL_HEAT, TX:SCOE:SHIFT_FUEL_HEAT, TX:SCOE:DEC_DEMAND_HEAT
Resolving Interactions in INEN :
No interactions, skipping... PFLO:NDC_25_UNCONDITIONAL_CE

/opt/anaconda3/envs/ssp_uganda_env/lib/python3.11/site-packages/costs_benefits_ssp/cb_calculate.py:660: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  res_pre2025["variable"] = res_pre2025["variable"] + "_shifted" + (res_pre2025["time_period"]+SSP_GLOBAL_TIME_PERIOD_0).astype(str)#create a new variable so they can be recognized as shifted costs
/opt/anaconda3/envs/ssp_uganda_env/lib/python3.11/site-packages/costs_benefits_ssp/cb_calculate.py:661: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  res_pre2025["time_period"] = res_pre2025["time_period"]+SSP_GLOBAL_TIME_PERIOD_TX_START #shift the time period

In [11]:
results_all_pp_shifted.head()

,strategy_code,future_id,region,time_period,difference_variable,variable_value_baseline,variable_value_pathway,difference_value,variable,value
0,PFLO:HBLE,0,uganda,4,pop_unimproved_rural,1.932346e+07,1.932346e+07,0.0,cb:wali:technical_cost:sanitation:unimp_rural,0.0
1,PFLO:HBLE,0,uganda,5,pop_unimproved_rural,1.951974e+07,1.951974e+07,0.0,cb:wali:technical_cost:sanitation:unimp_rural,0.0
2,PFLO:HBLE,0,uganda,6,pop_unimproved_rural,1.896047e+07,1.896047e+07,0.0,cb:wali:technical_cost:sanitation:unimp_rural,0.0
3,PFLO:HBLE,0,uganda,7,pop_unimproved_rural,1.837001e+07,1.837001e+07,0.0,cb:wali:technical_cost:sanitation:unimp_rural,0.0
4,PFLO:HBLE,0,uganda,8,pop_unimproved_rural,1.774752e+07,1.774752e+07,0.0,cb:wali:technical_cost:sanitation:unimp_rural,0.0

In [12]:
ssp_data.head()

,primary_id,region,time_period,area_agrc_crops_bevs_and_spices,area_agrc_crops_cereals,area_agrc_crops_fibers,area_agrc_crops_fruits,area_agrc_crops_herbs_and_other_perennial_crops,area_agrc_crops_nuts,area_agrc_crops_other_annual,...,yf_agrc_herbs_and_other_perennial_crops_tonne_ha,yf_agrc_nuts_tonne_ha,yf_agrc_other_annual_tonne_ha,yf_agrc_other_woody_perennial_tonne_ha,yf_agrc_pulses_tonne_ha,yf_agrc_rice_tonne_ha,yf_agrc_sugar_cane_tonne_ha,yf_agrc_tubers_tonne_ha,yf_agrc_vegetables_and_vines_tonne_ha,yf_lndu_supremum_pastures_tonne_per_ha
0,0,uganda,4,634960.593061,2.025945e+06,156073.139455,1.131815e+06,505.429083,513832.892470,2.915383e+06,...,2.172065,0.458120,1.528325,0.3674,0.799814,2.970174,77.726965,4.805888,4.035314,92.81
1,0,uganda,5,640126.452982,2.042427e+06,157342.906406,1.141024e+06,509.541112,518013.291655,2.939102e+06,...,2.196794,0.611231,1.681739,0.3674,0.805568,3.032345,78.023706,4.440105,4.013004,92.81
2,0,uganda,6,642767.262368,2.050853e+06,157992.016628,1.145731e+06,511.643198,520150.329354,2.951227e+06,...,2.210866,0.841393,2.293907,0.3674,0.807398,3.080626,61.430414,4.911305,4.023409,92.81
3,0,uganda,7,645322.479649,2.059006e+06,158620.088334,1.150285e+06,513.677153,522218.102852,2.962959e+06,...,2.225270,0.400800,2.699337,0.3674,0.810044,3.094956,77.255948,4.924276,4.030111,92.81
4,0,uganda,8,647798.760608,2.066907e+06,159228.757514,1.154699e+06,515.648274,524221.998246,2.974329e+06,...,2.225270,0.400800,2.699337,0.3674,0.810044,3.094956,77.255948,4.924276,4.030111,92.81

# Indoor air pollution benef

Health co-benefit from reduced household air pollution

To monetize the health benefits of reducing indoor air pollution from the use of traditional biomass stoves, we drew on estimates from the BAR-HAP model (The Benefits of Action to Reduce Household Air Pollution; WHO, 2021).
The study reports cost-effectiveness ratios ranging from 674 – 869 USD per DALY avoided for clean cooking interventions in Nepal, meaning that each avoided disability-adjusted life year (DALY) costs approximately 700 USD.

To adapt this metric to Uganda, we scaled the cost-effectiveness ratio by the relative difference in GDP per capita between Nepal (~1,450 USD) and Uganda (~1,070 USD), yielding an adjusted range of ≈ 500–640 USD per DALY avoided.
Assuming that the transition from solid fuels to clean cooking solutions avoids about 0.1 DALY per person per year, the implied annual health benefit equals 50–64 USD per person.

Given an average household size of five, this corresponds to an estimated 250–320 USD per household per year in health-related economic benefits.

This adjusted value was used in the cost–benefit analysis as the annual household health co-benefit of eliminating exposure to indoor air pollution from firewood and other solid fuels in Uganda.

In [13]:
import pandas as pd
import numpy as np

# parameters
benefit_per_person = 320   # USD/person/year. 
years = np.arange(4, 56)

# ['primary_id', 'time_period', 'population_gnrl_total']

# baseline
baseline = ssp_data[ssp_data['primary_id'] == 0][['time_period', 'population_gnrl_total', 'frac_scoe_heat_energy_residential_solid_biomass']]
baseline = baseline.rename(columns={'population_gnrl_total': 'population_baseline'})
baseline = baseline.rename(columns={'frac_scoe_heat_energy_residential_solid_biomass': 'frac_scoe_heat_energy_residential_solid_biomass_baseline'})

baseline.head()

,time_period,population_baseline,frac_scoe_heat_energy_residential_solid_biomass_baseline
0,4,39853824,0.960324
1,5,40996690,0.932779
2,6,42172327,0.901015
3,7,43381679,0.901015
4,8,44625710,0.901015

In [14]:
# baseline merge
merged = ssp_data[ssp_data['primary_id'] != 0][['primary_id', 'time_period', 'population_gnrl_total', 
                                                'frac_scoe_heat_energy_residential_solid_biomass']].merge(baseline, 
                                                                                                          on='time_period', how='left')
merged.tail(50)

,primary_id,time_period,population_gnrl_total,frac_scoe_heat_energy_residential_solid_biomass,population_baseline,frac_scoe_heat_energy_residential_solid_biomass_baseline
158,780078,6,42172327,0.901015,42172327,0.901015
159,780078,7,43381679,0.901015,43381679,0.901015
160,780078,8,44625710,0.901015,44625710,0.901015
161,780078,9,45905416,0.901015,45905416,0.901015
162,780078,10,47221819,0.901015,47221819,0.901015
163,780078,11,48562777,0.901015,48562777,0.901015
164,780078,12,49928247,0.891400,49928247,0.892538
165,780078,13,51318160,0.876952,51318160,0.879923
166,780078,14,52732427,0.855544,52732427,0.861368
167,780078,15,54170936,0.824507,54170936,0.834544
168,780078,16,55633552,0.780963,55633552,0.796717
169,780078,17,57118968,0.722624,57118968,0.745199
170,780078,18,58626908,0.649016,58626908,0.678266
171,780078,19,60157070,0.562518,60157070,0.596441
172,780078,20,61709123,0.468433,61709123,0.503533
173,780078,21,63282705,0.373881,63282705,0.406492
174,780078,22,64877430,0.285997,64877430,0.313584
175,780078,23,66492878,0.210150,66492878,0.231759
176,780078,24,68128603,0.148900,68128603,0.164826
177,780078,25,69784128,0.102122,69784128,0.113308
178,780078,26,71458947,0.067933,71458947,0.075481
179,780078,27,73013306,0.043791,73013306,0.048657
180,780078,28,74582504,0.027092,74582504,0.030102
181,780078,29,76162092,0.015738,76162092,0.017487
182,780078,30,77745983,0.008109,77745983,0.009010
183,780078,31,79337720,0.008109,79337720,0.009010
184,780078,32,80943325,0.008109,80943325,0.009010
185,780078,33,82560132,0.008109,82560132,0.009010
186,780078,34,84179703,0.008109,84179703,0.009010
187,780078,35,85801427,0.008109,85801427,0.009010
188,780078,36,87428891,0.008109,87428891,0.009010
189,780078,37,89064421,0.008109,89064421,0.009010
190,780078,38,90709186,0.008109,90709186,0.009010
191,780078,39,92356737,0.008109,92356737,0.009010
192,780078,40,94002404,0.008109,94002404,0.009010
193,780078,41,95647230,0.008109,95647230,0.009010
194,780078,42,97294463,0.008109,97294463,0.009010
195,780078,43,98943854,0.008109,98943854,0.009010
196,780078,44,100590482,0.008109,100590482,0.009010
197,780078,45,102228430,0.008109,102228430,0.009010
198,780078,46,103867064,0.008109,103867064,0.009010
199,780078,47,105508460,0.008109,105508460,0.009010
200,780078,48,107140913,0.008109,107140913,0.009010
201,780078,49,108767599,0.008109,108767599,0.009010
202,780078,50,110385692,0.008109,110385692,0.009010
203,780078,51,111995359,0.008109,111995359,0.009010
204,780078,52,113599053,0.008109,113599053,0.009010
205,780078,53,115193414,0.008109,115193414,0.009010
206,780078,54,116777146,0.008109,116777146,0.009010
207,780078,55,118356823,0.008109,118356823,0.009010

In [15]:
# frac_scoe_heat_energy_residential_solid_biomass 
merged['pop_diff'] = (merged['frac_scoe_heat_energy_residential_solid_biomass_baseline'] - merged['frac_scoe_heat_energy_residential_solid_biomass'] ) * merged['population_gnrl_total']

In [16]:
# difference calculation
merged['value'] =  merged['pop_diff'] * benefit_per_person

In [17]:
merged.head(30)

,primary_id,time_period,population_gnrl_total,frac_scoe_heat_energy_residential_solid_biomass,population_baseline,frac_scoe_heat_energy_residential_solid_biomass_baseline,pop_diff,value
0,700070,4,39853824,0.960324,39853824,0.960324,0.000000e+00,0.000000e+00
1,700070,5,40996690,0.932779,40996690,0.932779,0.000000e+00,0.000000e+00
2,700070,6,42172327,0.901015,42172327,0.901015,0.000000e+00,0.000000e+00
3,700070,7,43381679,0.901015,43381679,0.901015,0.000000e+00,0.000000e+00
4,700070,8,44625710,0.901015,44625710,0.901015,0.000000e+00,0.000000e+00
5,700070,9,45905416,0.901015,45905416,0.901015,0.000000e+00,0.000000e+00
6,700070,10,47221819,0.901015,47221819,0.901015,0.000000e+00,0.000000e+00
7,700070,11,48562777,0.901015,48562777,0.901015,0.000000e+00,0.000000e+00
8,700070,12,49928247,0.878908,49928247,0.892538,6.805106e+05,2.177634e+08
9,700070,13,51318160,0.851210,51318160,0.879923,1.473473e+06,4.715115e+08
10,700070,14,52732427,0.816296,52732427,0.861368,2.376758e+06,7.605627e+08
11,700070,15,54170936,0.772296,54170936,0.834544,3.372029e+06,1.079049e+09
12,700070,16,55633552,0.717349,55633552,0.796717,4.415525e+06,1.412968e+09
13,700070,17,57118968,0.650143,57118968,0.745199,5.429512e+06,1.737444e+09
14,700070,18,58626908,0.570783,58626908,0.678266,6.301437e+06,2.016460e+09
15,700070,19,60157070,0.481743,60157070,0.596441,6.899847e+06,2.207951e+09
16,700070,20,61709123,0.388281,61709123,0.503533,7.112074e+06,2.275864e+09
17,700070,21,63282705,0.297593,63282705,0.406492,6.891410e+06,2.205251e+09
18,700070,22,64877430,0.216725,64877430,0.313584,6.284018e+06,2.010886e+09
19,700070,23,66492878,0.150356,66492878,0.231759,5.412687e+06,1.732060e+09
20,700070,24,68128603,0.099837,68128603,0.164826,4.427618e+06,1.416838e+09
21,700070,25,69784128,0.063759,69784128,0.113308,3.457739e+06,1.106476e+09
22,700070,26,71458947,0.039286,71458947,0.075481,2.586452e+06,8.276646e+08
23,700070,27,73013306,0.023340,73013306,0.048657,1.848429e+06,5.914973e+08
24,700070,28,74582504,0.013274,74582504,0.030102,1.255128e+06,4.016410e+08
25,700070,29,76162092,0.007077,76162092,0.017487,7.928823e+05,2.537223e+08
26,700070,30,77745983,0.003344,77745983,0.009010,4.404920e+05,1.409574e+08
27,700070,31,79337720,0.003069,79337720,0.009010,4.713566e+05,1.508341e+08
28,700070,32,80943325,0.002820,80943325,0.009010,5.010189e+05,1.603261e+08
29,700070,33,82560132,0.002598,82560132,0.009010,5.293970e+05,1.694070e+08

In [18]:
merged = merged.merge(att_primary[['primary_id', 'strategy_id', 'future_id']], on='primary_id', how='left')
merged = merged.merge(att_strategy[['strategy_id', 'strategy_code']], on='strategy_id', how='left')

In [19]:
#merged.to_csv(os.path.join(CB_OUTPUT, "cba_indoor_air_pollution.csv"), index = False)

In [20]:
merged['region']='uganda'
merged['difference_variable'] ='frac_scoe_heat_energy_residential_solid_biomass'
merged['difference_value'] = 'pop_diff'
merged['variable'] ='cb:scoe:indoor_air_pollution'

In [21]:
merged = merged[['strategy_code', 'future_id', 'region', 'time_period', 'difference_variable', 'value','variable']]
merged.head()

,strategy_code,future_id,region,time_period,difference_variable,value,variable
0,PFLO:HBLE,0,uganda,4,frac_scoe_heat_energy_residential_solid_biomass,0.0,cb:scoe:indoor_air_pollution
1,PFLO:HBLE,0,uganda,5,frac_scoe_heat_energy_residential_solid_biomass,0.0,cb:scoe:indoor_air_pollution
2,PFLO:HBLE,0,uganda,6,frac_scoe_heat_energy_residential_solid_biomass,0.0,cb:scoe:indoor_air_pollution
3,PFLO:HBLE,0,uganda,7,frac_scoe_heat_energy_residential_solid_biomass,0.0,cb:scoe:indoor_air_pollution
4,PFLO:HBLE,0,uganda,8,frac_scoe_heat_energy_residential_solid_biomass,0.0,cb:scoe:indoor_air_pollution

In [22]:
#merged.to_csv(os.path.join(CB_OUTPUT, "cba_indoor_air_pollution.csv"), index = False)

In [23]:
results_all_pp_shifted= pd.concat([results_all_pp_shifted, merged], ignore_index = True)

In [24]:
results_all_pp_shifted.head()

,strategy_code,future_id,region,time_period,difference_variable,variable_value_baseline,variable_value_pathway,difference_value,variable,value
0,PFLO:HBLE,0,uganda,4,pop_unimproved_rural,1.932346e+07,1.932346e+07,0.0,cb:wali:technical_cost:sanitation:unimp_rural,0.0
1,PFLO:HBLE,0,uganda,5,pop_unimproved_rural,1.951974e+07,1.951974e+07,0.0,cb:wali:technical_cost:sanitation:unimp_rural,0.0
2,PFLO:HBLE,0,uganda,6,pop_unimproved_rural,1.896047e+07,1.896047e+07,0.0,cb:wali:technical_cost:sanitation:unimp_rural,0.0
3,PFLO:HBLE,0,uganda,7,pop_unimproved_rural,1.837001e+07,1.837001e+07,0.0,cb:wali:technical_cost:sanitation:unimp_rural,0.0
4,PFLO:HBLE,0,uganda,8,pop_unimproved_rural,1.774752e+07,1.774752e+07,0.0,cb:wali:technical_cost:sanitation:unimp_rural,0.0

In [25]:
results_all_pp_shifted.tail()

,strategy_code,future_id,region,time_period,difference_variable,variable_value_baseline,variable_value_pathway,difference_value,variable,value
50029,PFLO:NDC_25_UNCONDITIONAL_CE,0,uganda,51,frac_scoe_heat_energy_residential_solid_biomass,NaN,NaN,NaN,cb:scoe:indoor_air_pollution,3.229103e+07
50030,PFLO:NDC_25_UNCONDITIONAL_CE,0,uganda,52,frac_scoe_heat_energy_residential_solid_biomass,NaN,NaN,NaN,cb:scoe:indoor_air_pollution,3.275342e+07
50031,PFLO:NDC_25_UNCONDITIONAL_CE,0,uganda,53,frac_scoe_heat_energy_residential_solid_biomass,NaN,NaN,NaN,cb:scoe:indoor_air_pollution,3.321311e+07
50032,PFLO:NDC_25_UNCONDITIONAL_CE,0,uganda,54,frac_scoe_heat_energy_residential_solid_biomass,NaN,NaN,NaN,cb:scoe:indoor_air_pollution,3.366974e+07
50033,PFLO:NDC_25_UNCONDITIONAL_CE,0,uganda,55,frac_scoe_heat_energy_residential_solid_biomass,NaN,NaN,NaN,cb:scoe:indoor_air_pollution,3.412520e+07

## Reshape to load into tableau

In [26]:
# --- Read cost-benefit data ---
cb_data = results_all_pp_shifted.copy()

# Split 'variable' into components: name, sector, cb_type, item_1, item_2
# (Assumes exactly 5 colon-separated parts; if there are more colons inside the last field,
# they will be kept in item_2 thanks to n=4)
cb_chars = cb_data["variable"].astype(str).str.split(":", n=4, expand=True)
cb_chars.columns = ["name", "sector", "cb_type", "item_1", "item_2"]
cb_data = pd.concat([cb_data, cb_chars], axis=1)

In [27]:
cb_data.head()

,strategy_code,future_id,region,time_period,difference_variable,variable_value_baseline,variable_value_pathway,difference_value,variable,value,name,sector,cb_type,item_1,item_2
0,PFLO:HBLE,0,uganda,4,pop_unimproved_rural,1.932346e+07,1.932346e+07,0.0,cb:wali:technical_cost:sanitation:unimp_rural,0.0,cb,wali,technical_cost,sanitation,unimp_rural
1,PFLO:HBLE,0,uganda,5,pop_unimproved_rural,1.951974e+07,1.951974e+07,0.0,cb:wali:technical_cost:sanitation:unimp_rural,0.0,cb,wali,technical_cost,sanitation,unimp_rural
2,PFLO:HBLE,0,uganda,6,pop_unimproved_rural,1.896047e+07,1.896047e+07,0.0,cb:wali:technical_cost:sanitation:unimp_rural,0.0,cb,wali,technical_cost,sanitation,unimp_rural
3,PFLO:HBLE,0,uganda,7,pop_unimproved_rural,1.837001e+07,1.837001e+07,0.0,cb:wali:technical_cost:sanitation:unimp_rural,0.0,cb,wali,technical_cost,sanitation,unimp_rural
4,PFLO:HBLE,0,uganda,8,pop_unimproved_rural,1.774752e+07,1.774752e+07,0.0,cb:wali:technical_cost:sanitation:unimp_rural,0.0,cb,wali,technical_cost,sanitation,unimp_rural

In [28]:
cb_data['strategy_code'].unique()

array(['PFLO:HBLE', 'PFLO:NDC_25_SCOE_ELEC', 'PFLO:NDC_25_UNCONDITIONAL',
       'PFLO:NDC_25_UNCONDITIONAL_CE'], dtype=object)

In [29]:
# Scale value from USD to billions (divide by 1e9)
if "value" in cb_data.columns:
    cb_data["value"] = cb_data["value"] / 1e9

# --- Remove "shifted" entries ---
# Remove rows where item_2 contains "shifted"
cb_data = cb_data[~cb_data["item_2"].astype(str).str.contains("shifted", na=False)]

# Remove any remaining rows where variable contains "shifted2"
cb_data = cb_data[~cb_data["variable"].astype(str).str.contains("shifted2", na=False)]

# --- Add Year column (Year = time_period + 2015) ---
cb_data["Year"] = cb_data["time_period"] + 2015

**This Section Needs Manual Tunnning**

In [30]:
cb_data.strategy_code.unique()

array(['PFLO:HBLE', 'PFLO:NDC_25_SCOE_ELEC', 'PFLO:NDC_25_UNCONDITIONAL',
       'PFLO:NDC_25_UNCONDITIONAL_CE'], dtype=object)

In [31]:
# Harmonize strategy name changes with a single mapping (no duplicate replacements)
strategy_name_map = {
    "PFLO:HBLE": "PFLO:HBLE",
    "PFLO:NDC_25_SCOE_ELEC": "PFLO:NDC_25_SCOE_ELEC",
    "PFLO:NDC_25_UNCONDITIONAL": "NDC_25_UNCONDITIONAL",
    "PFLO:NDC_25_UNCONDITIONAL_CE": "PFLO:NDC_25_UNCONDITIONAL_CE"
}

cb_data["strategy"] = (
    cb_data["strategy_code"].astype(str).map(strategy_name_map).fillna(cb_data["strategy_code"])
)
print(cb_data["strategy"].unique())

['PFLO:HBLE' 'PFLO:NDC_25_SCOE_ELEC' 'NDC_25_UNCONDITIONAL'
 'PFLO:NDC_25_UNCONDITIONAL_CE']

In [32]:
# --- Strategy ID mapping based on strategy_code ---
def map_strategy_id(code: str):
    if code == "BASE":
        return 0
    if code == "PFLO:HBLE":
        return 6004
    if code == "PFLO:NDC_25_SCOE_ELEC":
        return 6010
    if code == "PFLO:NDC_25_UNCONDITIONAL":
        return 6011
    if code == "PFLO:NDC_25_UNCONDITIONAL_CE":
        return 6012
    return code  # keep original if not matched

cb_data["strategy_id"] = cb_data["strategy_code"].astype(str).map(map_strategy_id)

In [33]:
ssp_data.primary_id.unique()

array([     0, 700070, 760076, 770077, 780078])

In [34]:
def map_primary_id(code: str):
    if code == "BASE":
        return 0
    if code == "PFLO:HBLE":
        return 700070
    if code == "PFLO:NDC_25_SCOE_ELEC":
        return 760076
    if code == "PFLO:NDC_25_UNCONDITIONAL":
        return 770077
    if code == "PFLO:NDC_25_UNCONDITIONAL_CE":
        return 780078
    return code  # keep original if not matched

cb_data["primary_id"] = cb_data["strategy_code"].astype(str).map(map_primary_id)

**Manual Tunning Ends Here**

In [35]:
# --- Create ids (variable:strategy_id) ---
cb_data["ids"] = cb_data["variable"].astype(str) + ":" + cb_data["strategy_id"].astype(str)

In [36]:
cb_data.head()

,strategy_code,future_id,region,time_period,difference_variable,variable_value_baseline,variable_value_pathway,difference_value,variable,value,name,sector,cb_type,item_1,item_2,Year,strategy,strategy_id,primary_id,ids
0,PFLO:HBLE,0,uganda,4,pop_unimproved_rural,1.932346e+07,1.932346e+07,0.0,cb:wali:technical_cost:sanitation:unimp_rural,0.0,cb,wali,technical_cost,sanitation,unimp_rural,2019,PFLO:HBLE,6004,700070,cb:wali:technical_cost:sanitation:unimp_rural:...
1,PFLO:HBLE,0,uganda,5,pop_unimproved_rural,1.951974e+07,1.951974e+07,0.0,cb:wali:technical_cost:sanitation:unimp_rural,0.0,cb,wali,technical_cost,sanitation,unimp_rural,2020,PFLO:HBLE,6004,700070,cb:wali:technical_cost:sanitation:unimp_rural:...
2,PFLO:HBLE,0,uganda,6,pop_unimproved_rural,1.896047e+07,1.896047e+07,0.0,cb:wali:technical_cost:sanitation:unimp_rural,0.0,cb,wali,technical_cost,sanitation,unimp_rural,2021,PFLO:HBLE,6004,700070,cb:wali:technical_cost:sanitation:unimp_rural:...
3,PFLO:HBLE,0,uganda,7,pop_unimproved_rural,1.837001e+07,1.837001e+07,0.0,cb:wali:technical_cost:sanitation:unimp_rural,0.0,cb,wali,technical_cost,sanitation,unimp_rural,2022,PFLO:HBLE,6004,700070,cb:wali:technical_cost:sanitation:unimp_rural:...
4,PFLO:HBLE,0,uganda,8,pop_unimproved_rural,1.774752e+07,1.774752e+07,0.0,cb:wali:technical_cost:sanitation:unimp_rural,0.0,cb,wali,technical_cost,sanitation,unimp_rural,2023,PFLO:HBLE,6004,700070,cb:wali:technical_cost:sanitation:unimp_rural:...

In [37]:
cb_data.strategy.unique()

array(['PFLO:HBLE', 'PFLO:NDC_25_SCOE_ELEC', 'NDC_25_UNCONDITIONAL',
       'PFLO:NDC_25_UNCONDITIONAL_CE'], dtype=object)

In [38]:
cb_data.strategy_code.unique()

array(['PFLO:HBLE', 'PFLO:NDC_25_SCOE_ELEC', 'PFLO:NDC_25_UNCONDITIONAL',
       'PFLO:NDC_25_UNCONDITIONAL_CE'], dtype=object)

In [39]:
# --- Read GDP and merge ---
# Keep only needed columns
gdp = ssp_data.loc[:, ["primary_id", "time_period", "gdp_mmm_usd"]]
gdp.head(100)

    primary_id  time_period  gdp_mmm_usd
0            0            4    96.640000
1            0            5    99.490000
2            0            6   103.010000
3            0            7   107.730000
4            0            8   113.483902
..         ...          ...          ...
95      700070           47   885.672553
96      700070           48   903.386004
97      700070           49   921.453724
98      700070           50   939.882799
99      700070           51   958.680455

[100 rows x 3 columns]

In [40]:
gdp[gdp['primary_id']== 760076]

     primary_id  time_period  gdp_mmm_usd
104      760076            4    96.640000
105      760076            5    99.490000
106      760076            6   103.010000
107      760076            7   107.730000
108      760076            8   113.483902
109      760076            9   120.406420
110      760076           10   128.353244
111      760076           11   137.787207
112      760076           12   150.256950
113      760076           13   165.012182
114      760076           14   182.090943
115      760076           15   200.536755
116      760076           16   217.217552
117      760076           17   235.175966
118      760076           18   254.500096
119      760076           19   275.283299
120      760076           20   297.630005
121      760076           21   321.646185
122      760076           22   347.444033
123      760076           23   375.142250
124      760076           24   404.866352
125      760076           25   434.618551
126      760076           26   464.059057
127      760076           27   492.826532
128      760076           28   520.544691
129      760076           29   546.829850
130      760076           30   571.299252
131      760076           31   593.579923
132      760076           32   615.601738
133      760076           33   637.270920
134      760076           34   658.492041
135      760076           35   679.168691
136      760076           36   699.204168
137      760076           37   718.502203
138      760076           38   736.967709
139      760076           39   754.507541
140      760076           40   771.031256
141      760076           41   786.451881
142      760076           42   802.180919
143      760076           43   818.224537
144      760076           44   834.589028
145      760076           45   851.280808
146      760076           46   868.306425
147      760076           47   885.672553
148      760076           48   903.386004
149      760076           49   921.453724
150      760076           50   939.882799
151      760076           51   958.680455
152      760076           52   977.854064
153      760076           53   997.411145
154      760076           54  1017.359368
155      760076           55  1037.706555

In [41]:
# Merge cb_data with gdp on primary_id and time_period
cb_data = cb_data.merge(gdp, on=["primary_id", "time_period"], how="left")
cb_data

,strategy_code,future_id,region,time_period,difference_variable,variable_value_baseline,variable_value_pathway,difference_value,variable,value,...,sector,cb_type,item_1,item_2,Year,strategy,strategy_id,primary_id,ids,gdp_mmm_usd
0,PFLO:HBLE,0,uganda,4,pop_unimproved_rural,1.932346e+07,1.932346e+07,0.0,cb:wali:technical_cost:sanitation:unimp_rural,0.000000,...,wali,technical_cost,sanitation,unimp_rural,2019,PFLO:HBLE,6004,700070,cb:wali:technical_cost:sanitation:unimp_rural:...,96.640000
1,PFLO:HBLE,0,uganda,5,pop_unimproved_rural,1.951974e+07,1.951974e+07,0.0,cb:wali:technical_cost:sanitation:unimp_rural,0.000000,...,wali,technical_cost,sanitation,unimp_rural,2020,PFLO:HBLE,6004,700070,cb:wali:technical_cost:sanitation:unimp_rural:...,99.490000
2,PFLO:HBLE,0,uganda,6,pop_unimproved_rural,1.896047e+07,1.896047e+07,0.0,cb:wali:technical_cost:sanitation:unimp_rural,0.000000,...,wali,technical_cost,sanitation,unimp_rural,2021,PFLO:HBLE,6004,700070,cb:wali:technical_cost:sanitation:unimp_rural:...,103.010000
3,PFLO:HBLE,0,uganda,7,pop_unimproved_rural,1.837001e+07,1.837001e+07,0.0,cb:wali:technical_cost:sanitation:unimp_rural,0.000000,...,wali,technical_cost,sanitation,unimp_rural,2022,PFLO:HBLE,6004,700070,cb:wali:technical_cost:sanitation:unimp_rural:...,107.730000
4,PFLO:HBLE,0,uganda,8,pop_unimproved_rural,1.774752e+07,1.774752e+07,0.0,cb:wali:technical_cost:sanitation:unimp_rural,0.000000,...,wali,technical_cost,sanitation,unimp_rural,2023,PFLO:HBLE,6004,700070,cb:wali:technical_cost:sanitation:unimp_rural:...,113.483902
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44839,PFLO:NDC_25_UNCONDITIONAL_CE,0,uganda,51,frac_scoe_heat_energy_residential_solid_biomass,NaN,NaN,NaN,cb:scoe:indoor_air_pollution,0.032291,...,scoe,indoor_air_pollution,None,None,2066,PFLO:NDC_25_UNCONDITIONAL_CE,6012,780078,cb:scoe:indoor_air_pollution:6012,958.680455
44840,PFLO:NDC_25_UNCONDITIONAL_CE,0,uganda,52,frac_scoe_heat_energy_residential_solid_biomass,NaN,NaN,NaN,cb:scoe:indoor_air_pollution,0.032753,...,scoe,indoor_air_pollution,None,None,2067,PFLO:NDC_25_UNCONDITIONAL_CE,6012,780078,cb:scoe:indoor_air_pollution:6012,977.854064
44841,PFLO:NDC_25_UNCONDITIONAL_CE,0,uganda,53,frac_scoe_heat_energy_residential_solid_biomass,NaN,NaN,NaN,cb:scoe:indoor_air_pollution,0.033213,...,scoe,indoor_air_pollution,None,None,2068,PFLO:NDC_25_UNCONDITIONAL_CE,6012,780078,cb:scoe:indoor_air_pollution:6012,997.411145
44842,PFLO:NDC_25_UNCONDITIONAL_CE,0,uganda,54,frac_scoe_heat_energy_residential_solid_biomass,NaN,NaN,NaN,cb:scoe:indoor_air_pollution,0.033670,...,scoe,indoor_air_pollution,None,None,2069,PFLO:NDC_25_UNCONDITIONAL_CE,6012,780078,cb:scoe:indoor_air_pollution:6012,1017.359368
44843,PFLO:NDC_25_UNCONDITIONAL_CE,0,uganda,55,frac_scoe_heat_energy_residential_solid_biomass,NaN,NaN,NaN,cb:scoe:indoor_air_pollution,0.034125,...,scoe,indoor_air_pollution,None,None,2070,PFLO:NDC_25_UNCONDITIONAL_CE,6012,780078,cb:scoe:indoor_air_pollution:6012,1037.706555

In [42]:
96.640000/35.35

2.7338048090523337

In [43]:
cb_data[['time_period','gdp_mmm_usd']]

# 2019: 96.640000 #PPP
# 2019: 35.35 #USD
# 2.7
# https://data.worldbank.org/indicator/NY.GDP.MKTP.CD?locations=UG

       time_period  gdp_mmm_usd
0                4    96.640000
1                5    99.490000
2                6   103.010000
3                7   107.730000
4                8   113.483902
...            ...          ...
44839           51   958.680455
44840           52   977.854064
44841           53   997.411145
44842           54  1017.359368
44843           55  1037.706555

[44844 rows x 2 columns]

In [44]:
cb_data.isna().sum()

strategy_code                 0
future_id                     0
region                        0
time_period                   0
difference_variable           0
variable_value_baseline     208
variable_value_pathway      364
difference_value            208
variable                      0
value                         0
name                          0
sector                        0
cb_type                       0
item_1                      208
item_2                     3340
Year                          0
strategy                      0
strategy_id                   0
primary_id                    0
ids                           0
gdp_mmm_usd                   0
dtype: int64

In [45]:
# Save the results
cb_data.to_csv(os.path.join(CB_OUTPUT, "cba_data_air_pollution.csv"), index = False)