In [1]:
# Load packages
from costs_benefits_ssp.cb_calculate import CostBenefits
import pandas as pd
import os
import pathlib
import numpy as np

In [2]:
# Define paths
SSP_PATH = pathlib.Path(os.getcwd()).parent.parent.as_posix()
SSP_RUN  = os.path.join(SSP_PATH, "ssp_run_output/sisepuede_run_2026-03-10t13;27;53.264959/nwr")


CB_DEFAULT_DEFINITION_PATH = os.path.join(SSP_PATH,"cost-benefits/cb_cost_factors")
CB_DEFAULT_DEFINITION_FILE_PATH = os.path.join(CB_DEFAULT_DEFINITION_PATH, "cb_config_params.xlsx")

CB_OUTPUT = os.path.join(SSP_PATH, "Tableau/data")

In [3]:
CB_OUTPUT

'/Users/fabianfuentes/git/ssp_uganda_data/ssp_modeling/Tableau/data'

In [4]:
CB_DEFAULT_DEFINITION_PATH

'/Users/fabianfuentes/git/ssp_uganda_data/ssp_modeling/cost-benefits/cb_cost_factors'

In [5]:
# Load data
ssp_data = pd.read_csv(os.path.join(SSP_RUN, "uganda.csv"))
att_primary = pd.read_csv(os.path.join(SSP_RUN,"ATTRIBUTE_PRIMARY.csv"))
att_strategy = pd.read_csv(os.path.join(SSP_RUN,"ATTRIBUTE_STRATEGY.csv"))
strategy_code_base = "BASE"

In [6]:
att_primary

   primary_id  design_id  strategy_id  future_id
0           0          0            0          0
1      700070          0         6004          0
2      740074          0         6008          0
3      750075          0         6009          0

In [7]:
# Instantiate CostBenefits object
cb = CostBenefits(ssp_data, att_primary, att_strategy, strategy_code_base)

# The export_db_to_excel method saves the initial configuration of the cost tables to an excel file.
# Each sheet represents a table in the cost and benefit program database.
# If the Excel file name is not given, the file will be saved with the default name cb_config_params.xlsx on the current python session.

#cb.export_db_to_excel(CB_DEFAULT_DEFINITION_FILE_PATH)

# Once that the excel file has been updated, we can reload it in order to update the cost factors database
cb.load_cb_parameters(CB_DEFAULT_DEFINITION_FILE_PATH)

The TX TX:FRST:INCREASE_SEQUESTRATION_NZ is missing on AttTransformationCode
The TX TX:LNDU:DEC_WETLAND_LOSS_NZ is missing on AttTransformationCode
The TX TX:LNDU:SET_WETLANDS_MINIMUM_NZ is missing on AttTransformationCode
The TX TX:SCOE:INC_EFFICIENCY_HEAT_NZ is missing on AttTransformationCode
The TX TX:FRST:INCREASE_SEQUESTRATION_NDC_2 is missing on AttTransformationCode
The TX TX:LNDU:DEC_WETLAND_LOSS_NDC_2 is missing on AttTransformationCode
The TX TX:LNDU:SET_WETLANDS_MINIMUM_NDC_2 is missing on AttTransformationCode
The TX TX:SCOE:INC_EFFICIENCY_HEAT_NDC_2 is missing on AttTransformationCode
The TX TX:FRST:INCREASE_SEQUESTRATION_NDC_25 is missing on AttTransformationCode
The TX TX:LNDU:DEC_WETLAND_LOSS_NDC_25 is missing on AttTransformationCode
The TX TX:LNDU:SET_WETLANDS_MINIMUM_NDC_25 is missing on AttTransformationCode
The TX TX:SCOE:INC_EFFICIENCY_HEAT_NDC_25 is missing on AttTransformationCode
Cargamos configuración de archivo excel
Se actualizó la base de datos

In [8]:
# Compute System Costs
results_system = cb.compute_system_cost_for_all_strategies()

************************************
*Strategy : PFLO:HBLE (0/3)
************************************

---------Costs for: cb:wali:technical_cost:sanitation:unimp_rural.
La variable se evalúa en System Cost
---------Costs for: cb:wali:technical_cost:sanitation:imp_rural.
La variable se evalúa en System Cost
---------Costs for: cb:wali:technical_cost:sanitation:safeman_rural.
La variable se evalúa en System Cost
---------Costs for: cb:wali:technical_cost:sanitation:unimp_urban.
La variable se evalúa en System Cost
---------Costs for: cb:wali:technical_cost:sanitation:imp_urban.
La variable se evalúa en System Cost
---------Costs for: cb:wali:technical_cost:sanitation:safeman_urban.
La variable se evalúa en System Cost
---------Costs for: cb:wali:technical_cost:sanitation:omit_rural.
La variable se evalúa en System Cost
---------Costs for: cb:entc:technical_cost:electricity:capex.
La variable se evalúa en System Cost
---------Costs for: cb:entc:technical_cost:electricity:transmission.
La variable se evalúa en System Cost
---------Costs for: change_in_emissions.
La variable se evalúa en System Cost
---------Costs for: cb:trns:air_pollution:X:diesel.
La variable se evalúa en System Cost
---------Costs for: cb:trns:air_pollution:X:gasoline.
La variable se evalúa en System Cost
---------Costs for: cb:trns:air_pollution:X:biofuels.
La variable se evalúa en System Cost
---------Costs for: cb:lndu:ecosystem_services:forests:primary.
La variable se evalúa en System Cost
---------Costs for: cb:lndu:ecosystem_services:forests:secondary.
La variable se evalúa en System Cost
---------Costs for: cb:trns:system_cost:freight_transport:aviation.
La variable se evalúa en System Cost
---------Costs for: cb:trns:system_cost:freight_transport:rail.
La variable se evalúa en System Cost
---------Costs for: cb:trns:system_cost:freight_transport:road_heavy.
La variable se evalúa en System Cost
---------Costs for: cb:trns:system_cost:freight_transport:water_borne.
La variable se evalúa en System Cost
---------Costs for: cb:waso:technical_cost:waste_management:biogas.
La variable se evalúa en System Cost
---------Costs for: cb:waso:technical_cost:waste_management:compost.
La variable se evalúa en System Cost
---------Costs for: cb:waso:technical_cost:waste_management:incinerated.
La variable se evalúa en System Cost
---------Costs for: cb:waso:technical_cost:waste_management:landfilled.
La variable se evalúa en System Cost
---------Costs for: cb:waso:technical_cost:waste_management:open_dump.
La variable se evalúa en System Cost
---------Costs for: cb:waso:technical_cost:waste_management:recycled.
La variable se evalúa en System Cost
---------Costs for: cb:trww:technical_cost:wastewater_treatment:tertiary_aerobic.
La variable se evalúa en System Cost
---------Costs for: cb:trww:technical_cost:wastewater_treatment:tertiary_anaerobic.
La variable se evalúa en System Cost
---------Costs for: cb:trww:technical_cost:wastewater_treatment:primary.
La variable se evalúa en System Cost
---------Costs for: cb:trww:technical_cost:wastewater_treatment:secondary_aerobic.
La variable se evalúa en System Cost
---------Costs for: cb:trww:technical_cost:wastewater_treatment:secondary_anaerobic.
La variable se evalúa en System Cost
---------Costs for: cb:trww:technical_cost:wastewater_treatment:untreated_with_sewerage.
La variable se evalúa en System Cost
---------Costs for: cb:wali:human_health:safe_sanitation:X.
La variable se evalúa en System Cost
---------Costs for: cb:lvst:lvst_value:livestock_produced:buffalo.
La variable se evalúa en System Cost
---------Costs for: cb:lvst:lvst_value:livestock_produced:cattle_dairy.
La variable se evalúa en System Cost
---------Costs for: cb:lvst:lvst_value:livestock_produced:cattle_nondairy.
La variable se evalúa en System Cost
---------Costs for: cb:lvst:lvst_value:livestock_produced:chickens.
La variable se evalúa en System Cost
---------Costs for: cb:lvst:lvst_value:livestock_produced:goats.
La variable se evalúa en System Cost
---------Costs for: cb:lvst:lvst_value:livestock_produced:horses.
La variable se evalúa en System Cost
---------Costs for: cb:lvst:lvst_value:livestock_produced:mules.
La variable se evalúa en System Cost
---------Costs for: cb:lvst:lvst_value:livestock_produced:pigs.
La variable se evalúa en System Cost
---------Costs for: cb:lvst:lvst_value:livestock_produced:sheep.
La variable se evalúa en System Cost
---------Costs for: cb:agrc:crop_value:crops_produced:bevs_and_spices.
La variable se evalúa en System Cost
---------Costs for: cb:agrc:crop_value:crops_produced:cereals.
La variable se evalúa en System Cost
---------Costs for: cb:agrc:crop_value:crops_produced:fibers.
La variable se evalúa en System Cost
---------Costs for: cb:agrc:crop_value:crops_produced:fruits.
La variable se evalúa en System Cost
---------Costs for: cb:agrc:crop_value:crops_produced:herbs.
La variable se evalúa en System Cost
---------Costs for: cb:agrc:crop_value:crops_produced:nuts.
La variable se evalúa en System Cost
---------Costs for: cb:agrc:crop_value:crops_produced:other_annual.
La variable se evalúa en System Cost
---------Costs for: cb:agrc:crop_value:crops_produced:other_woody_perennial.
La variable se evalúa en System Cost
---------Costs for: cb:agrc:crop_value:crops_produced:pulses.
La variable se evalúa en System Cost
---------Costs for: cb:agrc:crop_value:crops_produced:rice.
La variable se evalúa en System Cost
---------Costs for: cb:agrc:crop_value:crops_produced:sugar_cane.
La variable se evalúa en System Cost
---------Costs for: cb:agrc:crop_value:crops_produced:tubers.
La variable se evalúa en System Cost
---------Costs for: cb:agrc:crop_value:crops_produced:vegetables.
La variable se evalúa en System Cost
---------Costs for: cb:trww:technical_cost:waste_to_energy:X.
La variable se evalúa en System Cost
---------Costs for: cb:trww:fuel_cost:waste_to_energy_value:X.
La variable se evalúa en System Cost
---------Costs for: cb:ccsq:sector_specific:fuel_cost:X.
La variable se evalúa en System Cost
---------Costs for: cb:inen:sector_specific:fuel_cost:X.
La variable se evalúa en System Cost
---------Costs for: cb:scoe:sector_specific:fuel_cost:X.
La variable se evalúa en System Cost
---------Costs for: cb:entc:sector_specific:fuel_cost:X.
La variable se evalúa en System Cost
---------Costs for: cb:trns:sector_specific:fuel_cost:X.
La variable se evalúa en System Cost
---------Costs for: cb:ippu:air_pollution:X:cement.
La variable se evalúa en System Cost
---------Costs for: cb:trns:system_cost:passenger_transport:aviation.
La variable se evalúa en System Cost
---------Costs for: cb:trns:system_cost:passenger_transport:powered_bikes.
La variable se evalúa en System Cost
---------Costs for: cb:trns:system_cost:passenger_transport:public.
La variable se evalúa en System Cost
---------Costs for: cb:trns:system_cost:passenger_transport:rail_passenger.
La variable se evalúa en System Cost
---------Costs for: cb:trns:system_cost:passenger_transport:road_heavy_regional.
La variable se evalúa en System Cost
---------Costs for: cb:trns:system_cost:passenger_transport:road_light.
La variable se evalúa en System Cost
---------Costs for: cb:waso:env_pollution:open_dumping:X.
La variable se evalúa en System Cost
---------Costs for: cb:ippu:ippu_value:industrial_products:cement.
La variable se evalúa en System Cost
---------Costs for: cb:ippu:ippu_value:industrial_products:steel.
La variable se evalúa en System Cost
---------Costs for: cb:ccsq:sector_specific:electricity_cost:X.
La variable se evalúa en System Cost
---------Costs for: cb:inen:sector_specific:electricity_cost:X.
La variable se evalúa en System Cost
---------Costs for: cb:scoe:sector_specific:electricity_cost:X.
La variable se evalúa en System Cost
---------Costs for: cb:trns:sector_specific:electricity_cost:X.
La variable se evalúa en System Cost
---------Costs for: cb:waso:technical_cost:waste_to_energy:incineration.
La variable se evalúa en System Cost
---------Costs for: cb:waso:technical_cost:waste_to_energy:anaerobic.
La variable se evalúa en System Cost
---------Costs for: cb:waso:technical_cost:waste_to_energy:landfill.
La variable se evalúa en System Cost
---------Costs for: cb:waso:fuel_cost:waste_to_energy_value:anaerobic.
La variable se evalúa en System Cost
---------Costs for: cb:waso:fuel_cost:waste_to_energy_value:landfill.
La variable se evalúa en System Cost
---------Costs for: cb:entc:air_pollution:X:diesel.
La variable se evalúa en System Cost
---------Costs for: cb:entc:air_pollution:X:gasoline.
La variable se evalúa en System Cost
---------Costs for: cb:entc:air_pollution:X:biofuels.
La variable se evalúa en System Cost
---------Costs for: cb:trns:congestion:X:diesel.
La variable se evalúa en System Cost
---------Costs for: cb:trns:congestion:X:gasoline.
La variable se evalúa en System Cost
---------Costs for: cb:trns:congestion:X:biofuels.
La variable se evalúa en System Cost
---------Costs for: cb:trns:congestion:X:electricity.
La variable se evalúa en System Cost
---------Costs for: cb:waso:technical_cost:waste_collection:biogas.
La variable se evalúa en System Cost
---------Costs for: cb:waso:technical_cost:waste_collection:compost.
La variable se evalúa en System Cost
---------Costs for: cb:waso:technical_cost:waste_collection:incinerated.
La variable se evalúa en System Cost
---------Costs for: cb:waso:technical_cost:waste_collection:landfilled.
La variable se evalúa en System Cost
---------Costs for: cb:waso:technical_cost:waste_collection:open_dump.
La variable se evalúa en System Cost
---------Costs for: cb:waso:technical_cost:waste_collection:recycled.
La variable se evalúa en System Cost
---------Costs for: cb:soil:technical_cost:agriculture_inputs:fertilizer.
La variable se evalúa en System Cost
---------Costs for: cb:soil:land_pollution:N_leaching:fertilizer.
La variable se evalúa en System Cost
---------Costs for: cb:inen:air_pollution:X:diesel.
La variable se evalúa en System Cost
---------Costs for: cb:inen:air_pollution:X:gasoline.
La variable se evalúa en System Cost
---------Costs for: cb:inen:air_pollution:X:biomass.
La variable se evalúa en System Cost
---------Costs for: cb:inen:air_pollution:X:coal.
La variable se evalúa en System Cost
---------Costs for: cb:inen:air_pollution:X:coke.
La variable se evalúa en System Cost
---------Costs for: cb:inen:air_pollution:X:natural_gas.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:X:X.
La variable se evalúa en System Cost
---------Costs for: cb:trns:road_safety:X:diesel.
La variable se evalúa en System Cost
---------Costs for: cb:trns:road_safety:X:gasoline.
La variable se evalúa en System Cost
---------Costs for: cb:trns:road_safety:X:biofuels.
La variable se evalúa en System Cost
---------Costs for: cb:trns:road_safety:X:electricity.
La variable se evalúa en System Cost
---------Costs for: cb:trww:water_pollution:wastewater_treatment:P.
La variable se evalúa en System Cost
---------Costs for: cb:trww:water_pollution:wastewater_treatment:N.
La variable se evalúa en System Cost
---------Costs for: cb:trww:water_pollution:wastewater_treatment:COD.
La variable se evalúa en System Cost
---------Costs for: cb:trww:water_pollution:wastewater_treatment:BOD.
La variable se evalúa en System Cost
---------Costs for: cb:lsmm:fuel_cost:waste_to_energy_value:X.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:ccsq:electricity.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:ccsq:hydrogen.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:ccsq:natural_gas.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:entc:biofuels.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:entc:biogas.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:entc:biomass.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:entc:coal.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:entc:coke.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:entc:diesel.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:entc:electricity.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:entc:gasoline.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:entc:hydrocarbon_gas_liquids.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:entc:hydrogen.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:entc:kerosene.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:entc:natural_gas.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:entc:nuclear.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:entc:oil.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:entc:other.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:entc:waste.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:inen:biomass.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:inen:coal.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:inen:coke.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:inen:diesel.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:inen:electricity.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:inen:gasoline.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:inen:hydrocarbon_gas_liquids.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:inen:hydrogen.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:inen:kerosene.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:inen:natural_gas.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:inen:oil.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:scoe:biomass.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:scoe:coal.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:scoe:diesel.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:scoe:electricity.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:scoe:gasoline.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:scoe:hydrocarbon_gas_liquids.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:scoe:hydrogen.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:scoe:kerosene.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:scoe:natural_gas.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:trns:biofuels.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:trns:diesel.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:trns:electricity.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:trns:gasoline.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:trns:hydrocarbon_gas_liquids.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:trns:hydrogen.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:trns:kerosene.
La variable se evalúa en System Cost
---------Costs for: cb:enfu:fuel_cost:trns:natural_gas.
La variable se evalúa en System Cost

************************************
*Strategy : PFLO:NDC_2_2020_TUNED (1/3)
************************************

---------Costs for: cb:wali:technical_cost:sanitation:unimp_rural.
La variable se evalúa en System Cost
---------Costs for: cb:wali:technical_cost:sanitation:imp_rural.
La variable se evalúa en System Cost
---------Costs for: cb:wali:technical_cost:sanitation:safeman_rural.
La variable se evalúa en System Cost
---------Costs for: cb:wali:technical_cost:sanitation:unimp_urban.
La variable se evalúa en System Cost
---------Costs for: cb:wali:technical_cost:sanitation:imp_urban.
La variable se evalúa en System Cost
---------Costs for: cb:wali:technical_cost:sanitation:safeman_urban.
La variable se evalúa en System Cost
---------Costs for: cb:wali:technical_cost:sanitation:omit_rural.
La variable se evalúa en System Cost
---------Costs for: cb:entc:technical_cost:electricity:capex.
La variable se evalúa en System Cost
---------Costs for: cb:entc:technical_cost:electricity:transmission.
La variable se evalúa en System Cost
---------Costs for: change_in_emissions.
La variable se evalúa en System Cost
---------Costs for: cb:trns:air_pollution:X:diesel.
La variable se evalúa en System Cost
---------Costs for: cb:trns:air_pollution:X:gasoline.
La variable se evalúa en System Cost
---------Costs for: cb:trns:air_pollution:X:biofuels.
La variable se evalúa en System Cost
---------Costs for: cb:lndu:ecosystem_services:forests:primary.
La variable se evalúa en System Cost
---------Costs for: cb:lndu:ecosystem_services:forests:secondary.
La variable se evalúa en System Cost
---------Costs for: cb:trns:system_cost:freight_transport:aviation.
La variable se evalúa en System Cost
---------Costs for: cb:trns:system_cost:freight_transport:rail.
La variable se evalúa en System Cost
---------Costs for: cb:trns:system_cost:freight_transport:road_heavy.
La variable se evalúa en System Cost
---------Costs for: cb:trns:system_cost:freight_transport:water_borne.
La variable se evalúa en System Cost
---------Costs for: cb:waso:technical_cost:waste_management:biogas.
La variable se evalúa en System Cost
---------Costs for: cb:waso:technical_cost:waste_management:compost.
La variable se evalúa en System Cost
---------Costs for: cb:waso:technical_cost:waste_management:incinerated.
La variable se evalúa en System Cost
---------Costs for: cb:waso:technical_cost:waste_management:landfilled.
La variable se evalúa en System Cost
---------Costs for: cb:waso:technical_cost:waste_management:open_dump.
La variable se evalúa en System Cost
---------Costs for: cb:waso:technical_cost:waste_management:recycled.
La variable se evalúa en System Cost
---------Costs for: cb:trww:technical_cost:wastewater_treatment:tertiary_aerobic.
La variable se evalúa en System Cost
---------Costs for: cb:trww:technical_cost:wastewater_treatment:tertiary_anaerobic.
La variable se evalúa en System Cost
---------Costs for: cb:trww:technical_cost:wastewater_treatment:primary.
La variable se evalúa en System Cost
---------Costs for: cb:trww:technical_cost:wastewater_treatment:secondary_aerobic.
La variable se evalúa en System Cost
---------Costs for: cb:trww:technical_cost:wastewater_treatment:secondary_anaerobic.
La variable se evalúa en System Cost
---------Costs for: cb:trww:technical_cost:wastewater_treatment:untreated_with_sewerage.
La variable se evalúa en System Cost
---------Costs for: cb:wali:human_health:safe_sanitation:X.
La variable se evalúa en System Cost
---------Costs for: cb:lvst:lvst_value:livestock_produced:buffalo.
La variable se evalúa en System Cost
---------Costs for: cb:lvst:lvst_value:livestock_produced:cattle_dairy.
La variable se evalúa en System Cost
---------Costs for: cb:lvst:lvst_value:livestock_produced:cattle_nondairy.
La variable se evalúa en System Cost
---------Costs for: cb:lvst:lvst_value:livestock_produced:chickens.
La variable se evalúa en System Cost
---------Costs for: cb:lvst:lvst_value:livestock_produced:goats.
La variable se evalúa en System Cost
---------Costs for: cb:lvst:lvst_value:livestock_produced:horses.
La variable se evalúa en System Cost
---------Costs for: cb:lvst:lvst_value:livestock_produced:mules.
La variable se evalúa en System Cost
---------Costs for: cb:lvst:lvst_value:livestock_produced:pigs.
La variable se evalúa en System Cost

In [9]:
# Compute Technical Costs
results_tx = cb.compute_technical_cost_for_all_strategies()

************************************
*Strategy : PFLO:HBLE (0/3)
************************************

---------Costs for: cb:inen:technical_cost:fuel_switch:lo_heat.
La variable se evalúa en Transformation Cost
---------Costs for: cb:inen:technical_savings:fuel_switch:lo_heat.
La variable se evalúa en Transformation Cost
---------Costs for: cb:inen:technical_cost:fuel_switch:hi_heat.
La variable se evalúa en Transformation Cost
---------Costs for: cb:inen:technical_savings:fuel_switch:hi_heat.
La variable se evalúa en Transformation Cost
---------Costs for: cb:inen:technical_cost:fuel_switch:all.
La variable se evalúa en Transformation Cost
---------Costs for: cb:inen:technical_savings:fuel_switch:all.
La variable se evalúa en Transformation Cost
---------Costs for: cb:inen:technical_cost:efficiency:X.
La variable se evalúa en Transformation Cost
---------Costs for: cb:trns:technical_cost:electrification:LDV.
La variable se evalúa en Transformation Cost
---------Costs for: cb:trns:technical_savings:electrification:LDV.
La variable se evalúa en Transformation Cost
---------Costs for: cb:trns:technical_cost:electrification:rail.
La variable se evalúa en Transformation Cost
---------Costs for: cb:trns:technical_savings:electrification:rail.
La variable se evalúa en Transformation Cost
---------Costs for: cb:trns:technical_cost:fuel_switch:maritime.
La variable se evalúa en Transformation Cost
---------Costs for: cb:trns:technical_cost:electrification:hdv_vehicles.
La variable se evalúa en Transformation Cost
---------Costs for: cb:trns:technical_savings:electrification:hdv_vehicles.
La variable se evalúa en Transformation Cost
---------Costs for: cb:trns:technical_cost:electrification:hdv_charger.
La variable se evalúa en Transformation Cost
---------Costs for: cb:trns:technical_cost:efficiency:electric.
La variable se evalúa en Transformation Cost
---------Costs for: cb:trns:technical_cost:efficiency:non_electric.
La variable se evalúa en Transformation Cost
---------Costs for: cb:trns:technical_cost:efficiency:all.
La variable se evalúa en Transformation Cost
---------Costs for: cb:scoe:technical_cost:efficiency:appliance.
La variable se evalúa en Transformation Cost
---------Costs for: cb:scoe:technical_cost:fuel_switch:heat_pumps.
La variable se evalúa en Transformation Cost
---------Costs for: cb:scoe:technical_savings:fuel_switch:heat_pumps.
La variable se evalúa en Transformation Cost
---------Costs for: cb:scoe:technical_cost:efficiency:building_shell.
La variable se evalúa en Transformation Cost
---------Costs for: cb:entc:technical_cost:loss_reduction:electricity.
La variable se evalúa en Transformation Cost
---------Costs for: cb:ippu:technical_cost:clinker:X.
La variable se evalúa en Transformation Cost
---------Costs for: cb:ippu:technical_cost:abating_gases:n2o.
La variable se evalúa en Transformation Cost
---------Costs for: cb:ippu:technical_cost:abating_gases:pfcs.
La variable se evalúa en Transformation Cost

/Users/fabianfuentes/anaconda3/envs/ssp_uganda_env/lib/python3.11/site-packages/costs_benefits_ssp/cb_calculate.py:856: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp["difference_variable"] = cb_orm.diff_var
/Users/fabianfuentes/anaconda3/envs/ssp_uganda_env/lib/python3.11/site-packages/costs_benefits_ssp/cb_calculate.py:857: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp["difference_value"] = data_merged["difference"]
/Users/fabianfuentes/anaconda3/envs/ssp_uganda_env/lib/python3.11/site-packages/costs_benefits_ssp/cb_calculate.py:858: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp["variable"] = cb_orm.output_variable_name
/Users/fabianfuentes/anaconda3/envs/ssp_uganda_env/lib/python3.11/site-packages/costs_benefits_ssp/cb_calculate.py:859: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp["value"] = data_merged["values"]
/Users/fabianfuentes/anaconda3/envs/ssp_uganda_env/lib/python3.11/site-packages/costs_benefits_ssp/cb_calculate.py:863: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp['variable_value_baseline'] = 0
/Users/fabianfuentes/anaconda3/envs/ssp_uganda_env/lib/python3.11/site-packages/costs_benefits_ssp/cb_calculate.py:1067: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_output['variable_value_baseline'] = 0
/Users/fabianfuentes/anaconda3/envs/ssp_uganda_env/lib/python3.11/site-packages/costs_benefits_ssp/cb_calculate.py:1070: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_output['variable_value_pathway'] = data_merged["difference_value"]

---------Costs for: cb:ippu:technical_cost:abating_gases:other_fgases.
La variable se evalúa en Transformation Cost
---------Costs for: cb:fgtv:technical_cost:flaring:X.
La variable se evalúa en Transformation Cost
---------Costs for: cb:fgtv:technical_cost:leaks:X.
La variable se evalúa en Transformation Cost
---------Costs for: cb:waso:technical_cost:consumer_food_waste:X.
La variable se evalúa en Transformation Cost
---------Costs for: cb:waso:consumer_savings:consumer_food_waste:X.
La variable se evalúa en Transformation Cost
---------Costs for: cb:lvst:technical_cost:ent_ferm_mgmt:X.
La variable se evalúa en Transformation Cost
---------Costs for: cb:agrc:technical_cost:rice_mgmt:X.
La variable se evalúa en Transformation Cost
---------Costs for: cb:agrc:technical_cost:producer_food_waste:X.
La variable se evalúa en Transformation Cost
---------Costs for: cb:agrc:technical_savings:producer_food_waste:X.
La variable se evalúa en Transformation Cost
---------Costs for: cb:agrc:technical_cost:increase_productivity:X.
La variable se evalúa en Transformation Cost
---------Costs for: cb:lvst:technical_cost:increase_productivity:X.
La variable se evalúa en Transformation Cost
---------Costs for: cb:pflo:human_health:better_diets:X.
La variable se evalúa en Transformation Cost
---------Costs for: cb:pflo:consumer_savings:better_diets:X.
La variable se evalúa en Transformation Cost
---------Costs for: cb:lndu:technical_cost:silvopasture:X.
La variable se evalúa en Transformation Cost
---------Costs for: cb:lndu:technical_cost:all_secondary_forests:X.
La variable se evalúa en Transformation Cost
---------Costs for: cb:ippu:technical_cost:industrial_ccs:X.
La variable se evalúa en Transformation Cost
---------Costs for: cb:agrc:consumer_savings:cons_ag_land_value:X.
La variable se evalúa en Transformation Cost
---------Costs for: cb:agrc:technical_savings:cons_ag:X.
La variable se evalúa en Transformation Cost
---------Costs for: cb:lsmm:technical_cost:manure_management_cattle_pigs.
La variable se evalúa en Transformation Cost
---------Costs for: cb:lsmm:technical_cost:manure_management_poultry.
La variable se evalúa en Transformation Cost
---------Costs for: cb:lsmm:technical_cost:manure_management_other.
La variable se evalúa en Transformation Cost
---------Costs for: cb:lsmm:technical_cost:biogas_capture.
La variable se evalúa en Transformation Cost
---------Costs for: cb:waso:technical_cost:biogas_capture.
La variable se evalúa en Transformation Cost
---------Costs for: cb:entc:technical_savings:electricity:opex.
La variable se evalúa en Transformation Cost

************************************
*Strategy : PFLO:NDC_2_2020_TUNED (1/3)
************************************

---------Costs for: cb:inen:technical_cost:fuel_switch:lo_heat.
La variable se evalúa en Transformation Cost
---------Costs for: cb:inen:technical_savings:fuel_switch:lo_heat.
La variable se evalúa en Transformation Cost
---------Costs for: cb:inen:technical_cost:fuel_switch:hi_heat.
La variable se evalúa en Transformation Cost
---------Costs for: cb:inen:technical_savings:fuel_switch:hi_heat.
La variable se evalúa en Transformation Cost
---------Costs for: cb:inen:technical_cost:fuel_switch:all.
La variable se evalúa en Transformation Cost
---------Costs for: cb:inen:technical_savings:fuel_switch:all.
La variable se evalúa en Transformation Cost
---------Costs for: cb:inen:technical_cost:efficiency:X.
La variable se evalúa en Transformation Cost
---------Costs for: cb:trns:technical_cost:electrification:LDV.
La variable se evalúa en Transformation Cost
---------Costs for: cb:trns:technical_savings:electrification:LDV.
La variable se evalúa en Transformation Cost
---------Costs for: cb:trns:technical_cost:electrification:hdv_vehicles.
La variable se evalúa en Transformation Cost
---------Costs for: cb:trns:technical_savings:electrification:hdv_vehicles.
La variable se evalúa en Transformation Cost
---------Costs for: cb:trns:technical_cost:electrification:hdv_charger.
La variable se evalúa en Transformation Cost
---------Costs for: cb:trns:technical_cost:efficiency:non_electric.
La variable se evalúa en Transformation Cost
---------Costs for: cb:trns:technical_cost:efficiency:all.
La variable se evalúa en Transformation Cost
---------Costs for: cb:scoe:technical_cost:fuel_switch:heat_pumps.
La variable se evalúa en Transformation Cost
---------Costs for: cb:scoe:technical_savings:fuel_switch:heat_pumps.
La variable se evalúa en Transformation Cost
---------Costs for: cb:scoe:technical_cost:efficiency:building_shell.
La variable se evalúa en Transformation Cost
---------Costs for: cb:entc:technical_cost:loss_reduction:electricity.
La variable se evalúa en Transformation Cost
---------Costs for: cb:ippu:technical_cost:clinker:X.
La variable se evalúa en Transformation Cost
---------Costs for: cb:waso:technical_cost:consumer_food_waste:X.
La variable se evalúa en Transformation Cost
---------Costs for: cb:waso:consumer_savings:consumer_food_waste:X.
La variable se evalúa en Transformation Cost
---------Costs for: cb:lvst:technical_cost:ent_ferm_mgmt:X.
La variable se evalúa en Transformation Cost
---------Costs for: cb:agrc:technical_cost:increase_productivity:X.
La variable se evalúa en Transformation Cost
---------Costs for: cb:lvst:technical_cost:increase_productivity:X.
La variable se evalúa en Transformation Cost
---------Costs for: cb:lndu:technical_cost:silvopasture:X.
La variable se evalúa en Transformation Cost
---------Costs for: cb:lndu:technical_cost:all_secondary_forests:X.
La variable se evalúa en Transformation Cost
---------Costs for: cb:agrc:consumer_savings:cons_ag_land_value:X.
La variable se evalúa en Transformation Cost
---------Costs for: cb:agrc:technical_savings:cons_ag:X.
La variable se evalúa en Transformation Cost
---------Costs for: cb:waso:technical_cost:biogas_capture.
La variable se evalúa en Transformation Cost
---------Costs for: cb:entc:technical_savings:electricity:opex.
La variable se evalúa en Transformation Cost

************************************
*Strategy : PFLO:NDC_2_2025_TUNED (2/3)
************************************

---------Costs for: cb:inen:technical_cost:fuel_switch:lo_heat.
La variable se evalúa en Transformation Cost
---------Costs for: cb:inen:technical_savings:fuel_switch:lo_heat.
La variable se evalúa en Transformation Cost
---------Costs for: cb:inen:technical_cost:fuel_switch:hi_heat.
La variable se evalúa en Transformation Cost
---------Costs for: cb:inen:technical_savings:fuel_switch:hi_heat.
La variable se evalúa en Transformation Cost
---------Costs for: cb:inen:technical_cost:fuel_switch:all.
La variable se evalúa en Transformation Cost
---------Costs for: cb:inen:technical_savings:fuel_switch:all.
La variable se evalúa en Transformation Cost
---------Costs for: cb:inen:technical_cost:efficiency:X.
La variable se evalúa en Transformation Cost

/Users/fabianfuentes/anaconda3/envs/ssp_uganda_env/lib/python3.11/site-packages/costs_benefits_ssp/cb_calculate.py:1067: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_output['variable_value_baseline'] = 0
/Users/fabianfuentes/anaconda3/envs/ssp_uganda_env/lib/python3.11/site-packages/costs_benefits_ssp/cb_calculate.py:1070: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_output['variable_value_pathway'] = data_merged["difference_value"]

---------Costs for: cb:trns:technical_cost:electrification:LDV.
La variable se evalúa en Transformation Cost
---------Costs for: cb:trns:technical_savings:electrification:LDV.
La variable se evalúa en Transformation Cost
---------Costs for: cb:trns:technical_cost:electrification:hdv_vehicles.
La variable se evalúa en Transformation Cost
---------Costs for: cb:trns:technical_savings:electrification:hdv_vehicles.
La variable se evalúa en Transformation Cost
---------Costs for: cb:trns:technical_cost:electrification:hdv_charger.
La variable se evalúa en Transformation Cost
---------Costs for: cb:trns:technical_cost:efficiency:non_electric.
La variable se evalúa en Transformation Cost
---------Costs for: cb:trns:technical_cost:efficiency:all.
La variable se evalúa en Transformation Cost
---------Costs for: cb:scoe:technical_cost:fuel_switch:heat_pumps.
La variable se evalúa en Transformation Cost
---------Costs for: cb:scoe:technical_savings:fuel_switch:heat_pumps.
La variable se evalúa en Transformation Cost
---------Costs for: cb:scoe:technical_cost:efficiency:building_shell.
La variable se evalúa en Transformation Cost
---------Costs for: cb:entc:technical_cost:loss_reduction:electricity.
La variable se evalúa en Transformation Cost
---------Costs for: cb:ippu:technical_cost:clinker:X.
La variable se evalúa en Transformation Cost
---------Costs for: cb:waso:technical_cost:consumer_food_waste:X.
La variable se evalúa en Transformation Cost
---------Costs for: cb:waso:consumer_savings:consumer_food_waste:X.
La variable se evalúa en Transformation Cost
---------Costs for: cb:lvst:technical_cost:ent_ferm_mgmt:X.
La variable se evalúa en Transformation Cost
---------Costs for: cb:agrc:technical_cost:increase_productivity:X.
La variable se evalúa en Transformation Cost
---------Costs for: cb:lvst:technical_cost:increase_productivity:X.
La variable se evalúa en Transformation Cost
---------Costs for: cb:lndu:technical_cost:silvopasture:X.
La variable se evalúa en Transformation Cost
---------Costs for: cb:lndu:technical_cost:all_secondary_forests:X.
La variable se evalúa en Transformation Cost
---------Costs for: cb:agrc:consumer_savings:cons_ag_land_value:X.
La variable se evalúa en Transformation Cost
---------Costs for: cb:agrc:technical_savings:cons_ag:X.
La variable se evalúa en Transformation Cost
---------Costs for: cb:waso:technical_cost:biogas_capture.
La variable se evalúa en Transformation Cost
---------Costs for: cb:entc:technical_savings:electricity:opex.
La variable se evalúa en Transformation Cost

/Users/fabianfuentes/anaconda3/envs/ssp_uganda_env/lib/python3.11/site-packages/costs_benefits_ssp/cb_calculate.py:1067: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_output['variable_value_baseline'] = 0
/Users/fabianfuentes/anaconda3/envs/ssp_uganda_env/lib/python3.11/site-packages/costs_benefits_ssp/cb_calculate.py:1070: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_output['variable_value_pathway'] = data_merged["difference_value"]

In [10]:
# Combine results
results_all = pd.concat([results_system, results_tx], ignore_index = True)

#-------------POST PROCESS SIMULATION RESULTS---------------
# Post process interactions among strategies that affect the same variables
results_all_pp = cb.cb_process_interactions(results_all)

# SHIFT any stray costs incurred from 2015 to 2025 to 2025 and 2035
results_all_pp_shifted = cb.cb_shift_costs(results_all_pp)

Resolving Interactions in SCOE : TX:SCOE:INC_EFFICIENCY_APPLIANCE, TX:SCOE:SHIFT_FUEL_HEAT, TX:SCOE:SHIFT_FUEL_HEAT, TX:SCOE:DEC_DEMAND_HEAT
Resolving Interactions in INEN : TX:INEN:SHIFT_FUEL_HEAT, TX:INEN:SHIFT_FUEL_HEAT, TX:INEN:SHIFT_FUEL_HEAT, TX:INEN:SHIFT_FUEL_HEAT, TX:INEN:SHIFT_FUEL_HEAT, TX:INEN:SHIFT_FUEL_HEAT, TX:INEN:INC_EFFICIENCY_ENERGY
Resolving Interactions in SCOE : TX:SCOE:SHIFT_FUEL_HEAT, TX:SCOE:SHIFT_FUEL_HEAT, TX:SCOE:DEC_DEMAND_HEAT
Resolving Interactions in INEN : TX:INEN:SHIFT_FUEL_HEAT, TX:INEN:SHIFT_FUEL_HEAT, TX:INEN:SHIFT_FUEL_HEAT, TX:INEN:SHIFT_FUEL_HEAT, TX:INEN:SHIFT_FUEL_HEAT, TX:INEN:SHIFT_FUEL_HEAT, TX:INEN:INC_EFFICIENCY_ENERGY
Resolving Interactions in SCOE : TX:SCOE:SHIFT_FUEL_HEAT, TX:SCOE:SHIFT_FUEL_HEAT, TX:SCOE:DEC_DEMAND_HEAT
Resolving Interactions in INEN : TX:INEN:SHIFT_FUEL_HEAT, TX:INEN:SHIFT_FUEL_HEAT, TX:INEN:SHIFT_FUEL_HEAT, TX:INEN:SHIFT_FUEL_HEAT, TX:INEN:SHIFT_FUEL_HEAT, TX:INEN:SHIFT_FUEL_HEAT, TX:INEN:INC_EFFICIENCY_ENERGY

/Users/fabianfuentes/anaconda3/envs/ssp_uganda_env/lib/python3.11/site-packages/costs_benefits_ssp/cb_calculate.py:660: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  res_pre2025["variable"] = res_pre2025["variable"] + "_shifted" + (res_pre2025["time_period"]+SSP_GLOBAL_TIME_PERIOD_0).astype(str)#create a new variable so they can be recognized as shifted costs
/Users/fabianfuentes/anaconda3/envs/ssp_uganda_env/lib/python3.11/site-packages/costs_benefits_ssp/cb_calculate.py:661: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  res_pre2025["time_period"] = res_pre2025["time_period"]+SSP_GLOBAL_TIME_PERIOD_TX_START #shift the time period

In [11]:
results_all_pp_shifted.head()

,strategy_code,future_id,region,time_period,difference_variable,variable_value_baseline,variable_value_pathway,difference_value,variable,value
0,PFLO:HBLE,0,uganda,4,pop_unimproved_rural,1.932346e+07,1.932346e+07,0.0,cb:wali:technical_cost:sanitation:unimp_rural,0.0
1,PFLO:HBLE,0,uganda,5,pop_unimproved_rural,1.951974e+07,1.951974e+07,0.0,cb:wali:technical_cost:sanitation:unimp_rural,0.0
2,PFLO:HBLE,0,uganda,6,pop_unimproved_rural,1.896047e+07,1.896047e+07,0.0,cb:wali:technical_cost:sanitation:unimp_rural,0.0
3,PFLO:HBLE,0,uganda,7,pop_unimproved_rural,1.837001e+07,1.837001e+07,0.0,cb:wali:technical_cost:sanitation:unimp_rural,0.0
4,PFLO:HBLE,0,uganda,8,pop_unimproved_rural,1.774752e+07,1.774752e+07,0.0,cb:wali:technical_cost:sanitation:unimp_rural,0.0

In [12]:
ssp_data.head()

,primary_id,region,time_period,area_agrc_crops_bevs_and_spices,area_agrc_crops_cereals,area_agrc_crops_fibers,area_agrc_crops_fruits,area_agrc_crops_herbs_and_other_perennial_crops,area_agrc_crops_nuts,area_agrc_crops_other_annual,...,emission_co2e_subsector_total_inen,emission_co2e_subsector_total_ippu,emission_co2e_subsector_total_lndu,emission_co2e_subsector_total_lsmm,emission_co2e_subsector_total_lvst,emission_co2e_subsector_total_scoe,emission_co2e_subsector_total_soil,emission_co2e_subsector_total_trns,emission_co2e_subsector_total_trww,emission_co2e_subsector_total_waso
0,0,uganda,4,634960.593061,2.025945e+06,156073.139455,1.131815e+06,505.429083,513832.892470,2.915383e+06,...,4.042769,0.465881,12.786390,2.851485,24.455996,5.111759,3.902635,3.120065,5.679647,7.834200
1,0,uganda,5,640126.452982,2.042427e+06,157342.906406,1.141024e+06,509.541112,518013.291655,2.939102e+06,...,3.768837,0.425196,14.074887,2.866579,24.388514,5.280258,4.346543,3.186059,5.805355,7.989162
2,0,uganda,6,642767.262368,2.050853e+06,157992.016628,1.145731e+06,511.643198,520150.329354,2.951227e+06,...,3.743437,0.480422,13.989612,2.828685,24.228654,5.464224,4.763486,3.266846,6.106686,8.321531
3,0,uganda,7,645322.479649,2.059006e+06,158620.088334,1.150285e+06,513.677153,522218.102852,2.962959e+06,...,3.869481,0.490684,13.903196,2.842882,24.266033,5.649851,5.123842,3.411741,6.439193,8.651555
4,0,uganda,8,647798.760608,2.066907e+06,159228.757514,1.154699e+06,515.648274,524221.998246,2.974329e+06,...,3.995632,0.497946,13.811942,2.859282,24.309797,5.855234,5.409655,3.591142,6.808903,8.982613

# Indoor air pollution benef

Health co-benefit from reduced household air pollution

To monetize the health benefits of reducing indoor air pollution from the use of traditional biomass stoves, we drew on estimates from the BAR-HAP model (The Benefits of Action to Reduce Household Air Pollution; WHO, 2021).
The study reports cost-effectiveness ratios ranging from 674 – 869 USD per DALY avoided for clean cooking interventions in Nepal, meaning that each avoided disability-adjusted life year (DALY) costs approximately 700 USD.

To adapt this metric to Uganda, we scaled the cost-effectiveness ratio by the relative difference in GDP per capita between Nepal (~1,450 USD) and Uganda (~1,070 USD), yielding an adjusted range of ≈ 500–640 USD per DALY avoided.
Assuming that the transition from solid fuels to clean cooking solutions avoids about 0.1 DALY per person per year, the implied annual health benefit equals 50–64 USD per person.

Given an average household size of five, this corresponds to an estimated 250–320 USD per household per year in health-related economic benefits.

This adjusted value was used in the cost–benefit analysis as the annual household health co-benefit of eliminating exposure to indoor air pollution from firewood and other solid fuels in Uganda.

In [13]:
import pandas as pd
import numpy as np

# parameters
benefit_per_person = 320   # USD/person/year. 
years = np.arange(4, 56)

# ['primary_id', 'time_period', 'population_gnrl_total']

# baseline
baseline = ssp_data[ssp_data['primary_id'] == 0][['time_period', 'population_gnrl_total', 'frac_scoe_heat_energy_residential_solid_biomass']]
baseline = baseline.rename(columns={'population_gnrl_total': 'population_baseline'})
baseline = baseline.rename(columns={'frac_scoe_heat_energy_residential_solid_biomass': 'frac_scoe_heat_energy_residential_solid_biomass_baseline'})

baseline.head()

,time_period,population_baseline,frac_scoe_heat_energy_residential_solid_biomass_baseline
0,4,39853824,0.960324
1,5,40996690,0.932779
2,6,42172327,0.901015
3,7,43381679,0.901015
4,8,44625710,0.901015

In [14]:
# baseline merge
merged = ssp_data[ssp_data['primary_id'] != 0][['primary_id', 'time_period', 'population_gnrl_total', 
                                                'frac_scoe_heat_energy_residential_solid_biomass']].merge(baseline, 
                                                                                                          on='time_period', how='left')
merged.tail(50)

,primary_id,time_period,population_gnrl_total,frac_scoe_heat_energy_residential_solid_biomass,population_baseline,frac_scoe_heat_energy_residential_solid_biomass_baseline
106,750075,6,42172327,0.901015,42172327,0.901015
107,750075,7,43381679,0.901015,43381679,0.901015
108,750075,8,44625710,0.901015,44625710,0.901015
109,750075,9,45905416,0.901015,45905416,0.901015
110,750075,10,47221819,0.901015,47221819,0.901015
111,750075,11,48562777,0.901015,48562777,0.901015
112,750075,12,49928247,0.881160,49928247,0.892538
113,750075,13,51318160,0.850218,51318160,0.879923
114,750075,14,52732427,0.803123,52732427,0.861368
115,750075,15,54170936,0.734175,54170936,0.834544
116,750075,16,55633552,0.639178,55633552,0.796717
117,750075,17,57118968,0.519451,57118968,0.745199
118,750075,18,58626908,0.385762,58626908,0.678266
119,750075,19,60157070,0.257217,60157070,0.596441
120,750075,20,61709123,0.152539,61709123,0.503533
121,750075,21,63282705,0.080378,63282705,0.406492
122,750075,22,64877430,0.037714,64877430,0.313584
123,750075,23,66492878,0.015671,66492878,0.231759
124,750075,24,68128603,0.005564,68128603,0.164826
125,750075,25,69784128,0.001444,69784128,0.113308
126,750075,26,71458947,0.000000,71458947,0.075481
127,750075,27,73013306,0.000000,73013306,0.048657
128,750075,28,74582504,0.000000,74582504,0.030102
129,750075,29,76162092,0.000000,76162092,0.017487
130,750075,30,77745983,0.000000,77745983,0.009010
131,750075,31,79337720,0.000000,79337720,0.009010
132,750075,32,80943325,0.000000,80943325,0.009010
133,750075,33,82560132,0.000000,82560132,0.009010
134,750075,34,84179703,0.000000,84179703,0.009010
135,750075,35,85801427,0.000000,85801427,0.009010
136,750075,36,87428891,0.000000,87428891,0.009010
137,750075,37,89064421,0.000000,89064421,0.009010
138,750075,38,90709186,0.000000,90709186,0.009010
139,750075,39,92356737,0.000000,92356737,0.009010
140,750075,40,94002404,0.000000,94002404,0.009010
141,750075,41,95647230,0.000000,95647230,0.009010
142,750075,42,97294463,0.000000,97294463,0.009010
143,750075,43,98943854,0.000000,98943854,0.009010
144,750075,44,100590482,0.000000,100590482,0.009010
145,750075,45,102228430,0.000000,102228430,0.009010
146,750075,46,103867064,0.000000,103867064,0.009010
147,750075,47,105508460,0.000000,105508460,0.009010
148,750075,48,107140913,0.000000,107140913,0.009010
149,750075,49,108767599,0.000000,108767599,0.009010
150,750075,50,110385692,0.000000,110385692,0.009010
151,750075,51,111995359,0.000000,111995359,0.009010
152,750075,52,113599053,0.000000,113599053,0.009010
153,750075,53,115193414,0.000000,115193414,0.009010
154,750075,54,116777146,0.000000,116777146,0.009010
155,750075,55,118356823,0.000000,118356823,0.009010

In [15]:
# frac_scoe_heat_energy_residential_solid_biomass 
merged['pop_diff'] = (merged['frac_scoe_heat_energy_residential_solid_biomass_baseline'] - merged['frac_scoe_heat_energy_residential_solid_biomass'] ) * merged['population_gnrl_total']

In [16]:
# difference calculation
merged['value'] =  merged['pop_diff'] * benefit_per_person

In [17]:
merged.head(30)

,primary_id,time_period,population_gnrl_total,frac_scoe_heat_energy_residential_solid_biomass,population_baseline,frac_scoe_heat_energy_residential_solid_biomass_baseline,pop_diff,value
0,700070,4,39853824,0.960324,39853824,0.960324,0.000000e+00,0.000000e+00
1,700070,5,40996690,0.932779,40996690,0.932779,0.000000e+00,0.000000e+00
2,700070,6,42172327,0.901015,42172327,0.901015,0.000000e+00,0.000000e+00
3,700070,7,43381679,0.901015,43381679,0.901015,0.000000e+00,0.000000e+00
4,700070,8,44625710,0.901015,44625710,0.901015,0.000000e+00,0.000000e+00
5,700070,9,45905416,0.901015,45905416,0.901015,0.000000e+00,0.000000e+00
6,700070,10,47221819,0.901015,47221819,0.901015,0.000000e+00,0.000000e+00
7,700070,11,48562777,0.901015,48562777,0.901015,0.000000e+00,0.000000e+00
8,700070,12,49928247,0.892538,49928247,0.892538,0.000000e+00,0.000000e+00
9,700070,13,51318160,0.879923,51318160,0.879923,0.000000e+00,0.000000e+00
10,700070,14,52732427,0.840869,52732427,0.861368,1.080952e+06,3.459045e+08
11,700070,15,54170936,0.794824,54170936,0.834544,2.151685e+06,6.885392e+08
12,700070,16,55633552,0.739839,55633552,0.796717,3.164352e+06,1.012592e+09
13,700070,17,57118968,0.674267,57118968,0.745199,4.051532e+06,1.296490e+09
14,700070,18,58626908,0.597570,58626908,0.678266,4.730967e+06,1.513910e+09
15,700070,19,60157070,0.511295,60157070,0.596441,5.122136e+06,1.639083e+09
16,700070,20,61709123,0.419680,61709123,0.503533,5.174459e+06,1.655827e+09
17,700070,21,63282705,0.329145,63282705,0.406492,4.894751e+06,1.566320e+09
18,700070,22,64877430,0.246477,64877430,0.313584,4.353730e+06,1.393194e+09
19,700070,23,66492878,0.176678,66492878,0.231759,3.662496e+06,1.171999e+09
20,700070,24,68128603,0.121767,68128603,0.164826,2.933563e+06,9.387400e+08
21,700070,25,69784128,0.081054,69784128,0.113308,2.250829e+06,7.202653e+08
22,700070,26,71458947,0.052247,71458947,0.075481,1.660245e+06,5.312785e+08
23,700070,27,73013306,0.032577,73013306,0.048657,1.174016e+06,3.756852e+08
24,700070,28,74582504,0.019501,74582504,0.030102,7.906773e+05,2.530167e+08
25,700070,29,76162092,0.010985,76162092,0.017487,4.952312e+05,1.584740e+08
26,700070,30,77745983,0.005533,77745983,0.009010,2.703711e+05,8.651876e+07
27,700070,31,79337720,0.005328,79337720,0.009010,2.921364e+05,9.348364e+07
28,700070,32,80943325,0.005123,80943325,0.009010,3.146068e+05,1.006742e+08
29,700070,33,82560132,0.004919,82560132,0.009010,3.377799e+05,1.080896e+08

In [18]:
merged = merged.merge(att_primary[['primary_id', 'strategy_id', 'future_id']], on='primary_id', how='left')
merged = merged.merge(att_strategy[['strategy_id', 'strategy_code']], on='strategy_id', how='left')

In [19]:
#merged.to_csv(os.path.join(CB_OUTPUT, "cba_indoor_air_pollution.csv"), index = False)

In [20]:
merged['region']='uganda'
merged['difference_variable'] ='frac_scoe_heat_energy_residential_solid_biomass'
merged['difference_value'] = 'pop_diff'
merged['variable'] ='cb:scoe:indoor_air_pollution'

In [21]:
merged = merged[['strategy_code', 'future_id', 'region', 'time_period', 'difference_variable', 'value','variable']]
merged.head()

,strategy_code,future_id,region,time_period,difference_variable,value,variable
0,PFLO:HBLE,0,uganda,4,frac_scoe_heat_energy_residential_solid_biomass,0.0,cb:scoe:indoor_air_pollution
1,PFLO:HBLE,0,uganda,5,frac_scoe_heat_energy_residential_solid_biomass,0.0,cb:scoe:indoor_air_pollution
2,PFLO:HBLE,0,uganda,6,frac_scoe_heat_energy_residential_solid_biomass,0.0,cb:scoe:indoor_air_pollution
3,PFLO:HBLE,0,uganda,7,frac_scoe_heat_energy_residential_solid_biomass,0.0,cb:scoe:indoor_air_pollution
4,PFLO:HBLE,0,uganda,8,frac_scoe_heat_energy_residential_solid_biomass,0.0,cb:scoe:indoor_air_pollution

In [22]:
#merged.to_csv(os.path.join(CB_OUTPUT, "cba_indoor_air_pollution.csv"), index = False)

In [23]:
results_all_pp_shifted= pd.concat([results_all_pp_shifted, merged], ignore_index = True)

In [24]:
results_all_pp_shifted.head()

,strategy_code,future_id,region,time_period,difference_variable,variable_value_baseline,variable_value_pathway,difference_value,variable,value
0,PFLO:HBLE,0,uganda,4,pop_unimproved_rural,1.932346e+07,1.932346e+07,0.0,cb:wali:technical_cost:sanitation:unimp_rural,0.0
1,PFLO:HBLE,0,uganda,5,pop_unimproved_rural,1.951974e+07,1.951974e+07,0.0,cb:wali:technical_cost:sanitation:unimp_rural,0.0
2,PFLO:HBLE,0,uganda,6,pop_unimproved_rural,1.896047e+07,1.896047e+07,0.0,cb:wali:technical_cost:sanitation:unimp_rural,0.0
3,PFLO:HBLE,0,uganda,7,pop_unimproved_rural,1.837001e+07,1.837001e+07,0.0,cb:wali:technical_cost:sanitation:unimp_rural,0.0
4,PFLO:HBLE,0,uganda,8,pop_unimproved_rural,1.774752e+07,1.774752e+07,0.0,cb:wali:technical_cost:sanitation:unimp_rural,0.0

In [25]:
results_all_pp_shifted.tail()

,strategy_code,future_id,region,time_period,difference_variable,variable_value_baseline,variable_value_pathway,difference_value,variable,value
42627,PFLO:NDC_2_2025_TUNED,0,uganda,51,frac_scoe_heat_energy_residential_solid_biomass,NaN,NaN,NaN,cb:scoe:indoor_air_pollution,3.229103e+08
42628,PFLO:NDC_2_2025_TUNED,0,uganda,52,frac_scoe_heat_energy_residential_solid_biomass,NaN,NaN,NaN,cb:scoe:indoor_air_pollution,3.275342e+08
42629,PFLO:NDC_2_2025_TUNED,0,uganda,53,frac_scoe_heat_energy_residential_solid_biomass,NaN,NaN,NaN,cb:scoe:indoor_air_pollution,3.321311e+08
42630,PFLO:NDC_2_2025_TUNED,0,uganda,54,frac_scoe_heat_energy_residential_solid_biomass,NaN,NaN,NaN,cb:scoe:indoor_air_pollution,3.366974e+08
42631,PFLO:NDC_2_2025_TUNED,0,uganda,55,frac_scoe_heat_energy_residential_solid_biomass,NaN,NaN,NaN,cb:scoe:indoor_air_pollution,3.412520e+08

## Reshape to load into tableau

In [26]:
# --- Read cost-benefit data ---
cb_data = results_all_pp_shifted.copy()

# Split 'variable' into components: name, sector, cb_type, item_1, item_2
# (Assumes exactly 5 colon-separated parts; if there are more colons inside the last field,
# they will be kept in item_2 thanks to n=4)
cb_chars = cb_data["variable"].astype(str).str.split(":", n=4, expand=True)
cb_chars.columns = ["name", "sector", "cb_type", "item_1", "item_2"]
cb_data = pd.concat([cb_data, cb_chars], axis=1)

In [27]:
cb_data.head()

,strategy_code,future_id,region,time_period,difference_variable,variable_value_baseline,variable_value_pathway,difference_value,variable,value,name,sector,cb_type,item_1,item_2
0,PFLO:HBLE,0,uganda,4,pop_unimproved_rural,1.932346e+07,1.932346e+07,0.0,cb:wali:technical_cost:sanitation:unimp_rural,0.0,cb,wali,technical_cost,sanitation,unimp_rural
1,PFLO:HBLE,0,uganda,5,pop_unimproved_rural,1.951974e+07,1.951974e+07,0.0,cb:wali:technical_cost:sanitation:unimp_rural,0.0,cb,wali,technical_cost,sanitation,unimp_rural
2,PFLO:HBLE,0,uganda,6,pop_unimproved_rural,1.896047e+07,1.896047e+07,0.0,cb:wali:technical_cost:sanitation:unimp_rural,0.0,cb,wali,technical_cost,sanitation,unimp_rural
3,PFLO:HBLE,0,uganda,7,pop_unimproved_rural,1.837001e+07,1.837001e+07,0.0,cb:wali:technical_cost:sanitation:unimp_rural,0.0,cb,wali,technical_cost,sanitation,unimp_rural
4,PFLO:HBLE,0,uganda,8,pop_unimproved_rural,1.774752e+07,1.774752e+07,0.0,cb:wali:technical_cost:sanitation:unimp_rural,0.0,cb,wali,technical_cost,sanitation,unimp_rural

In [28]:
cb_data['strategy_code'].unique()

array(['PFLO:HBLE', 'PFLO:NDC_2_2020_TUNED', 'PFLO:NDC_2_2025_TUNED'],
      dtype=object)

In [29]:
# Scale value from USD to billions (divide by 1e9)
if "value" in cb_data.columns:
    cb_data["value"] = cb_data["value"] / 1e9

# --- Remove "shifted" entries ---
# Remove rows where item_2 contains "shifted"
cb_data = cb_data[~cb_data["item_2"].astype(str).str.contains("shifted", na=False)]

# Remove any remaining rows where variable contains "shifted2"
cb_data = cb_data[~cb_data["variable"].astype(str).str.contains("shifted2", na=False)]

# --- Add Year column (Year = time_period + 2015) ---
cb_data["Year"] = cb_data["time_period"] + 2015

**This Section Needs Manual Tunnning**

In [30]:
cb_data.strategy_code.unique()

array(['PFLO:HBLE', 'PFLO:NDC_2_2020_TUNED', 'PFLO:NDC_2_2025_TUNED'],
      dtype=object)

In [31]:
# Harmonize strategy name changes with a single mapping (no duplicate replacements)
strategy_name_map = {
    "PFLO:HBLE": "PFLO:HBLE",
    "PFLO:NDC_2_2020_TUNED": "PFLO:NDC_2_2020_TUNED",
    "PFLO:NDC_2_2025_TUNED": "PFLO:NDC_2_2025_TUNED",
}

cb_data["strategy"] = (
    cb_data["strategy_code"].astype(str).map(strategy_name_map).fillna(cb_data["strategy_code"])
)
print(cb_data["strategy"].unique())

['PFLO:HBLE' 'PFLO:NDC_2_2020_TUNED' 'PFLO:NDC_2_2025_TUNED']

In [32]:
# --- Strategy ID mapping based on strategy_code ---
def map_strategy_id(code: str):
    if code == "BASE":
        return 0
    if code == "PFLO:HBLE":
        return 6004
    if code == "PFLO:NDC_2_2020_TUNED":
        return 6008
    if code == "PFLO:NDC_2_2025_TUNED":
        return 6009
    return code  # keep original if not matched

cb_data["strategy_id"] = cb_data["strategy_code"].astype(str).map(map_strategy_id)

In [33]:
ssp_data.primary_id.unique()

array([     0, 700070, 740074, 750075])

In [34]:
def map_primary_id(code: str):
    if code == "BASE":
        return 0
    if code == "PFLO:HBLE":
        return 700070
    if code == "PFLO:NDC_2_2020_TUNED":
        return 740074
    if code == "PFLO:NDC_2_2025_TUNED":
        return 750075
    return code  # keep original if not matched

cb_data["primary_id"] = cb_data["strategy_code"].astype(str).map(map_primary_id)

**Manual Tunning Ends Here**

In [35]:
# --- Create ids (variable:strategy_id) ---
cb_data["ids"] = cb_data["variable"].astype(str) + ":" + cb_data["strategy_id"].astype(str)

In [36]:
cb_data.head()

,strategy_code,future_id,region,time_period,difference_variable,variable_value_baseline,variable_value_pathway,difference_value,variable,value,name,sector,cb_type,item_1,item_2,Year,strategy,strategy_id,primary_id,ids
0,PFLO:HBLE,0,uganda,4,pop_unimproved_rural,1.932346e+07,1.932346e+07,0.0,cb:wali:technical_cost:sanitation:unimp_rural,0.0,cb,wali,technical_cost,sanitation,unimp_rural,2019,PFLO:HBLE,6004,700070,cb:wali:technical_cost:sanitation:unimp_rural:...
1,PFLO:HBLE,0,uganda,5,pop_unimproved_rural,1.951974e+07,1.951974e+07,0.0,cb:wali:technical_cost:sanitation:unimp_rural,0.0,cb,wali,technical_cost,sanitation,unimp_rural,2020,PFLO:HBLE,6004,700070,cb:wali:technical_cost:sanitation:unimp_rural:...
2,PFLO:HBLE,0,uganda,6,pop_unimproved_rural,1.896047e+07,1.896047e+07,0.0,cb:wali:technical_cost:sanitation:unimp_rural,0.0,cb,wali,technical_cost,sanitation,unimp_rural,2021,PFLO:HBLE,6004,700070,cb:wali:technical_cost:sanitation:unimp_rural:...
3,PFLO:HBLE,0,uganda,7,pop_unimproved_rural,1.837001e+07,1.837001e+07,0.0,cb:wali:technical_cost:sanitation:unimp_rural,0.0,cb,wali,technical_cost,sanitation,unimp_rural,2022,PFLO:HBLE,6004,700070,cb:wali:technical_cost:sanitation:unimp_rural:...
4,PFLO:HBLE,0,uganda,8,pop_unimproved_rural,1.774752e+07,1.774752e+07,0.0,cb:wali:technical_cost:sanitation:unimp_rural,0.0,cb,wali,technical_cost,sanitation,unimp_rural,2023,PFLO:HBLE,6004,700070,cb:wali:technical_cost:sanitation:unimp_rural:...

In [37]:
cb_data.strategy.unique()

array(['PFLO:HBLE', 'PFLO:NDC_2_2020_TUNED', 'PFLO:NDC_2_2025_TUNED'],
      dtype=object)

In [38]:
cb_data.strategy_code.unique()

array(['PFLO:HBLE', 'PFLO:NDC_2_2020_TUNED', 'PFLO:NDC_2_2025_TUNED'],
      dtype=object)

In [39]:
# --- Read GDP and merge ---
# Keep only needed columns
gdp = ssp_data.loc[:, ["primary_id", "time_period", "gdp_mmm_usd"]]
gdp.head(100)

    primary_id  time_period  gdp_mmm_usd
0            0            4    96.640000
1            0            5    99.490000
2            0            6   103.010000
3            0            7   107.730000
4            0            8   113.483902
..         ...          ...          ...
95      700070           47   885.672553
96      700070           48   903.386004
97      700070           49   921.453724
98      700070           50   939.882799
99      700070           51   958.680455

[100 rows x 3 columns]

In [40]:
gdp[gdp['primary_id']== 750075]

     primary_id  time_period  gdp_mmm_usd
156      750075            4    96.640000
157      750075            5    99.490000
158      750075            6   103.010000
159      750075            7   107.730000
160      750075            8   113.483902
161      750075            9   120.406420
162      750075           10   128.353244
163      750075           11   137.787207
164      750075           12   150.256950
165      750075           13   165.012182
166      750075           14   182.090943
167      750075           15   200.536755
168      750075           16   217.217552
169      750075           17   235.175966
170      750075           18   254.500096
171      750075           19   275.283299
172      750075           20   297.630005
173      750075           21   321.646185
174      750075           22   347.444033
175      750075           23   375.142250
176      750075           24   404.866352
177      750075           25   434.618551
178      750075           26   464.059057
179      750075           27   492.826532
180      750075           28   520.544691
181      750075           29   546.829850
182      750075           30   571.299252
183      750075           31   593.579923
184      750075           32   615.601738
185      750075           33   637.270920
186      750075           34   658.492041
187      750075           35   679.168691
188      750075           36   699.204168
189      750075           37   718.502203
190      750075           38   736.967709
191      750075           39   754.507541
192      750075           40   771.031256
193      750075           41   786.451881
194      750075           42   802.180919
195      750075           43   818.224537
196      750075           44   834.589028
197      750075           45   851.280808
198      750075           46   868.306425
199      750075           47   885.672553
200      750075           48   903.386004
201      750075           49   921.453724
202      750075           50   939.882799
203      750075           51   958.680455
204      750075           52   977.854064
205      750075           53   997.411145
206      750075           54  1017.359368
207      750075           55  1037.706555

In [41]:
# Merge cb_data with gdp on primary_id and time_period
cb_data = cb_data.merge(gdp, on=["primary_id", "time_period"], how="left")
cb_data

,strategy_code,future_id,region,time_period,difference_variable,variable_value_baseline,variable_value_pathway,difference_value,variable,value,...,sector,cb_type,item_1,item_2,Year,strategy,strategy_id,primary_id,ids,gdp_mmm_usd
0,PFLO:HBLE,0,uganda,4,pop_unimproved_rural,1.932346e+07,1.932346e+07,0.0,cb:wali:technical_cost:sanitation:unimp_rural,0.000000,...,wali,technical_cost,sanitation,unimp_rural,2019,PFLO:HBLE,6004,700070,cb:wali:technical_cost:sanitation:unimp_rural:...,96.640000
1,PFLO:HBLE,0,uganda,5,pop_unimproved_rural,1.951974e+07,1.951974e+07,0.0,cb:wali:technical_cost:sanitation:unimp_rural,0.000000,...,wali,technical_cost,sanitation,unimp_rural,2020,PFLO:HBLE,6004,700070,cb:wali:technical_cost:sanitation:unimp_rural:...,99.490000
2,PFLO:HBLE,0,uganda,6,pop_unimproved_rural,1.896047e+07,1.896047e+07,0.0,cb:wali:technical_cost:sanitation:unimp_rural,0.000000,...,wali,technical_cost,sanitation,unimp_rural,2021,PFLO:HBLE,6004,700070,cb:wali:technical_cost:sanitation:unimp_rural:...,103.010000
3,PFLO:HBLE,0,uganda,7,pop_unimproved_rural,1.837001e+07,1.837001e+07,0.0,cb:wali:technical_cost:sanitation:unimp_rural,0.000000,...,wali,technical_cost,sanitation,unimp_rural,2022,PFLO:HBLE,6004,700070,cb:wali:technical_cost:sanitation:unimp_rural:...,107.730000
4,PFLO:HBLE,0,uganda,8,pop_unimproved_rural,1.774752e+07,1.774752e+07,0.0,cb:wali:technical_cost:sanitation:unimp_rural,0.000000,...,wali,technical_cost,sanitation,unimp_rural,2023,PFLO:HBLE,6004,700070,cb:wali:technical_cost:sanitation:unimp_rural:...,113.483902
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38187,PFLO:NDC_2_2025_TUNED,0,uganda,51,frac_scoe_heat_energy_residential_solid_biomass,NaN,NaN,NaN,cb:scoe:indoor_air_pollution,0.322910,...,scoe,indoor_air_pollution,None,None,2066,PFLO:NDC_2_2025_TUNED,6009,750075,cb:scoe:indoor_air_pollution:6009,958.680455
38188,PFLO:NDC_2_2025_TUNED,0,uganda,52,frac_scoe_heat_energy_residential_solid_biomass,NaN,NaN,NaN,cb:scoe:indoor_air_pollution,0.327534,...,scoe,indoor_air_pollution,None,None,2067,PFLO:NDC_2_2025_TUNED,6009,750075,cb:scoe:indoor_air_pollution:6009,977.854064
38189,PFLO:NDC_2_2025_TUNED,0,uganda,53,frac_scoe_heat_energy_residential_solid_biomass,NaN,NaN,NaN,cb:scoe:indoor_air_pollution,0.332131,...,scoe,indoor_air_pollution,None,None,2068,PFLO:NDC_2_2025_TUNED,6009,750075,cb:scoe:indoor_air_pollution:6009,997.411145
38190,PFLO:NDC_2_2025_TUNED,0,uganda,54,frac_scoe_heat_energy_residential_solid_biomass,NaN,NaN,NaN,cb:scoe:indoor_air_pollution,0.336697,...,scoe,indoor_air_pollution,None,None,2069,PFLO:NDC_2_2025_TUNED,6009,750075,cb:scoe:indoor_air_pollution:6009,1017.359368
38191,PFLO:NDC_2_2025_TUNED,0,uganda,55,frac_scoe_heat_energy_residential_solid_biomass,NaN,NaN,NaN,cb:scoe:indoor_air_pollution,0.341252,...,scoe,indoor_air_pollution,None,None,2070,PFLO:NDC_2_2025_TUNED,6009,750075,cb:scoe:indoor_air_pollution:6009,1037.706555

In [42]:
cb_data.isna().sum()

strategy_code                 0
future_id                     0
region                        0
time_period                   0
difference_variable           0
variable_value_baseline     156
variable_value_pathway      312
difference_value            156
variable                      0
value                         0
name                          0
sector                        0
cb_type                       0
item_1                      156
item_2                     2612
Year                          0
strategy                      0
strategy_id                   0
primary_id                    0
ids                           0
gdp_mmm_usd                   0
dtype: int64

In [43]:
# Save the results
cb_data.to_csv(os.path.join(CB_OUTPUT, "cba_data_air_pollution.csv"), index = False)